### ISSUE TITLE
Mask R-CNN fails when running model_eval.py on Metal backend

### ISSUE THREAD

**Issue by danhipke** [tinygrad/tinygrad#1121]
I'm trying to run the eval for `mrcnn` using a Metal backend and getting errors:

```
% METAL=1 MODEL=mrcnn python3 examples/mlperf/model_eval.py
```

I'm running on an Apple M1 Max chip (2021 Macbook Pro). Changing `OPT` doesn't fix, but increasing it does slightly reduce the number of errors. Disabling method cache also does not fix (suggested in [#884](https://github.com/geohot/tinygrad/pull/884#issuecomment-1605175791)).

I'll continue to debug using `DEBUG=5`, but opening an issue in case someone with more Metal expertise sees something obvious as I ramp up on Metal. I'm guessing it's something with buffer limits, as it looks like we're creating 201 buffers.

<details>
  <summary>Error logs</summary>

```
% METAL=1 MODEL=mrcnn python3 examples/mlperf/model_eval.py
eval mrcnn
  0%|                                                                                                                                           | 0/5000 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/Users/dhipke/git/tinygrad/examples/mlperf/model_eval.py", line 244, in <module>
    globals()[nm]()
  File "/Users/dhipke/git/tinygrad/examples/mlperf/model_eval.py", line 221, in eval_mrcnn
    batch_result = compute_prediction_batched(batch_imgs, mdl)
  File "/Users/dhipke/git/tinygrad/examples/mask_rcnn.py", line 197, in compute_prediction_batched
    predictions = model(image)
  File "/Users/dhipke/git/tinygrad/models/mask_rcnn.py", line 1265, in __call__
    proposals, _ = self.rpn(images, features)
  File "/Users/dhipke/git/tinygrad/models/mask_rcnn.py", line 712, in __call__
    boxes = self.box_selector_test(anchors, objectness, rpn_box_regression)
  File "/Users/dhipke/git/tinygrad/models/mask_rcnn.py", line 667, in __call__
    sampled_boxes.append(self.forward_for_single_feature_map(a, o, b))
  File "/Users/dhipke/git/tinygrad/models/mask_rcnn.py", line 652, in forward_for_single_feature_map
    boxlist = remove_small_boxes(boxlist, self.min_size)
  File "/Users/dhipke/git/tinygrad/models/mask_rcnn.py", line 586, in remove_small_boxes
    if keep.sum().numpy() == len(boxlist):
  File "/Users/dhipke/git/tinygrad/tinygrad/tensor.py", line 111, in numpy
    def numpy(self) -> np.ndarray: return self.lazydata.toCPU()
  File "/Users/dhipke/git/tinygrad/tinygrad/lazy.py", line 158, in toCPU
    realized = self.cast(dtypes.from_np(self.dtype.np)).contiguous().realize().realized
  File "/Users/dhipke/git/tinygrad/tinygrad/lazy.py", line 114, in realize
    elif self.optype is LoadOps: LOAD_OPS_DISPATCHER[cast(LoadOps, self.op.op)](self)
  File "/Users/dhipke/git/tinygrad/tinygrad/lazy.py", line 306, in _realize_contiguous
    realized = buffer.op.src[0].realize().realized
  File "/Users/dhipke/git/tinygrad/tinygrad/lazy.py", line 117, in realize
    for x in self.op.buffers: x.realize()
  File "/Users/dhipke/git/tinygrad/tinygrad/lazy.py", line 117, in realize
    for x in self.op.buffers: x.realize()
  File "/Users/dhipke/git/tinygrad/tinygrad/lazy.py", line 117, in realize
    for x in self.op.buffers: x.realize()
  [Previous line repeated 22 more times]
  File "/Users/dhipke/git/tinygrad/tinygrad/lazy.py", line 127, in realize
    self.realized = Device[self.device].exec_ast(self.op, output=self, **self._device_extra_args())
  File "/Users/dhipke/git/tinygrad/tinygrad/ops.py", line 183, in exec_ast
    if k.key not in self.method_cache: self.method_cache[k.key] = k.codegen().build(self.runtime)
  File "/Users/dhipke/git/tinygrad/tinygrad/ops.py", line 133, in build
    self.clprg = runtime(self.name, self.prg, **self.runtime_args)
  File "/Users/dhipke/git/tinygrad/tinygrad/runtime/ops_metal.py", line 49, in __init__
    self.library = unwrap(METAL.device.newLibraryWithSource_options_error_(prg, options, None))
  File "/Users/dhipke/git/tinygrad/tinygrad/runtime/ops_metal.py", line 36, in unwrap
    assert err is None, str(err)
AssertionError: Error Domain=MTLLibraryErrorDomain Code=3 "Compilation failed:

program_source:3:896: error: no 'buffer' resource location available for 'data31'
program_source:3:924: error: no 'buffer' resource location available for 'data32'
program_source:3:952: error: no 'buffer' resource location available for 'data33'
program_source:3:980: error: no 'buffer' resource location available for 'data34'
program_source:3:1008: error: no 'buffer' resource location available for 'data35'
program_source:3:1036: error: no 'buffer' resource location available for 'data36'
program_source:3:1064: error: no 'buffer' resource location available for 'data37'
program_source:3:1092: error: no 'buffer' resource location available for 'data38'
program_source:3:1120: error: no 'buffer' resource location available for 'data39'
program_source:3:1148: error: no 'buffer' resource location available for 'data40'
program_source:3:1176: error: no 'buffer' resource location available for 'data41'
program_source:3:1204: error: no 'buffer' resource location available for 'data42'
program_source:3:1232: error: no 'buffer' resource location available for 'data43'
program_source:3:1260: error: no 'buffer' resource location available for 'data44'
program_source:3:1288: error: no 'buffer' resource location available for 'data45'
program_source:3:1316: error: no 'buffer' resource location available for 'data46'
program_source:3:1344: error: no 'buffer' resource location available for 'data47'
program_source:3:1372: error: no 'buffer' resource location available for 'data48'
program_source:3:1400: error: no 'buffer' resource location available for 'data49'
program_source:3:1428: error: no 'buffer' resource location available for 'data50'
program_source:3:1456: error: no 'buffer' resource location available for 'data51'
program_source:3:1484: error: no 'buffer' resource location available for 'data52'
program_source:3:1512: error: no 'buffer' resource location available for 'data53'
program_source:3:1540: error: no 'buffer' resource location available for 'data54'
program_source:3:1568: error: no 'buffer' resource location available for 'data55'
program_source:3:1596: error: no 'buffer' resource location available for 'data56'
program_source:3:1624: error: no 'buffer' resource location available for 'data57'
program_source:3:1652: error: no 'buffer' resource location available for 'data58'
program_source:3:1680: error: no 'buffer' resource location available for 'data59'
program_source:3:1708: error: no 'buffer' resource location available for 'data60'
program_source:3:1736: error: no 'buffer' resource location available for 'data61'
program_source:3:1764: error: no 'buffer' resource location available for 'data62'
program_source:3:1792: error: no 'buffer' resource location available for 'data63'
program_source:3:1820: error: no 'buffer' resource location available for 'data64'
program_source:3:1848: error: no 'buffer' resource location available for 'data65'
program_source:3:1876: error: no 'buffer' resource location available for 'data66'
program_source:3:1904: error: no 'buffer' resource location available for 'data67'
program_source:3:1932: error: no 'buffer' resource location available for 'data68'
program_source:3:1960: error: no 'buffer' resource location available for 'data69'
program_source:3:1988: error: no 'buffer' resource location available for 'data70'
program_source:3:2016: error: no 'buffer' resource location available for 'data71'
program_source:3:2044: error: no 'buffer' resource location available for 'data72'
program_source:3:2072: error: no 'buffer' resource location available for 'data73'
program_source:3:2100: error: no 'buffer' resource location available for 'data74'
program_source:3:2128: error: no 'buffer' resource location available for 'data75'
program_source:3:2156: error: no 'buffer' resource location available for 'data76'
program_source:3:2184: error: no 'buffer' resource location available for 'data77'
program_source:3:2212: error: no 'buffer' resource location available for 'data78'
program_source:3:2240: error: no 'buffer' resource location available for 'data79'
program_source:3:2268: error: no 'buffer' resource location available for 'data80'
program_source:3:2296: error: no 'buffer' resource location available for 'data81'
...
program_source:3:5583: error: no 'buffer' resource location available for 'data195'
program_source:3:5612: error: no 'buffer' resource location available for 'data196'
program_source:3:5641: error: no 'buffer' resource location available for 'data197'
program_source:3:5670: error: no 'buffer' resource location available for 'data198'
program_source:3:5699: error: no 'buffer' resource location available for 'data199'
program_source:3:5728: error: no 'buffer' resource location available for 'data200'
}
```

</details>

**Comment by geohot** [comment]
Yea, I think METAL has a limit to the number of buffers. On M1, you can use `GPU=1` instead.

Too many buffers in METAL is a real issue though and a fix would be great!

**Comment by danhipke** [comment]
I also get a similar issue with `GPU=1`. One of the kernels has 2602 kernel parameters which doesn't work (CL_DEVICE_MAX_PARAMETER_SIZE is 4119 on my machine) and `clCreateKernel` returns an INVALID_KERNEL error.

Setting to `OPT=1` fixes, as that uses a much more reasonable number of kernel parameters.  I'll take a look the issue for METAL backend.

<details>
  <summary>Error logs</summary>

```
% GPU=1 MODEL=mrcnn python3 examples/mlperf/model_eval.py

eval mrcnn
  0%|                                                                                                                                                                       | 0/5000 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/lib/python3.10/site-packages/pyopencl/__init__.py", line 459, in __getattr__
    knl = Kernel(self, attr)
  File "/opt/homebrew/anaconda3/lib/python3.10/site-packages/pyopencl/__init__.py", line 811, in kernel_init
    kernel_old_init(self, prg, name)
pyopencl._cl.LogicError: clCreateKernel failed: INVALID_KERNEL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dhipke/git/tinygrad/examples/mlperf/model_eval.py", line 244, in <module>
    globals()[nm]()
  File "/Users/dhipke/git/tinygrad/examples/mlperf/model_eval.py", line 221, in eval_mrcnn
    batch_result = compute_prediction_batched(batch_imgs, mdl)
  File "/Users/dhipke/git/tinygrad/examples/mask_rcnn.py", line 197, in compute_prediction_batched
    predictions = model(image)
  File "/Users/dhipke/git/tinygrad/models/mask_rcnn.py", line 1265, in __call__
    proposals, _ = self.rpn(images, features)
  File "/Users/dhipke/git/tinygrad/models/mask_rcnn.py", line 712, in __call__
    boxes = self.box_selector_test(anchors, objectness, rpn_box_regression)
  File "/Users/dhipke/git/tinygrad/models/mask_rcnn.py", line 667, in __call__
    sampled_boxes.append(self.forward_for_single_feature_map(a, o, b))
  File "/Users/dhipke/git/tinygrad/models/mask_rcnn.py", line 652, in forward_for_single_feature_map
    boxlist = remove_small_boxes(boxlist, self.min_size)
  File "/Users/dhipke/git/tinygrad/models/mask_rcnn.py", line 586, in remove_small_boxes
    if keep.sum().numpy() == len(boxlist):
  File "/Users/dhipke/git/tinygrad/tinygrad/tensor.py", line 111, in numpy
    def numpy(self) -> np.ndarray: return self.lazydata.toCPU()
  File "/Users/dhipke/git/tinygrad/tinygrad/lazy.py", line 158, in toCPU
    realized = self.cast(dtypes.from_np(self.dtype.np)).contiguous().realize().realized
  File "/Users/dhipke/git/tinygrad/tinygrad/lazy.py", line 114, in realize
    elif self.optype is LoadOps: LOAD_OPS_DISPATCHER[cast(LoadOps, self.op.op)](self)
  File "/Users/dhipke/git/tinygrad/tinygrad/lazy.py", line 306, in _realize_contiguous
    realized = buffer.op.src[0].realize().realized
  File "/Users/dhipke/git/tinygrad/tinygrad/lazy.py", line 117, in realize
    for x in self.op.buffers: x.realize()
  File "/Users/dhipke/git/tinygrad/tinygrad/lazy.py", line 127, in realize
    self.realized = Device[self.device].exec_ast(self.op, output=self, **self._device_extra_args())
  File "/Users/dhipke/git/tinygrad/tinygrad/ops.py", line 183, in exec_ast
    if k.key not in self.method_cache: self.method_cache[k.key] = k.codegen().build(self.runtime)
  File "/Users/dhipke/git/tinygrad/tinygrad/ops.py", line 133, in build
    self.clprg = runtime(self.name, self.prg, **self.runtime_args)
  File "/Users/dhipke/git/tinygrad/tinygrad/runtime/ops_gpu.py", line 65, in __init__
    self.clprg = self._clprg.__getattr__(name)
  File "/opt/homebrew/anaconda3/lib/python3.10/site-packages/pyopencl/__init__.py", line 476, in __getattr__
    raise AttributeError("'%s' was not found as a program "
AttributeError: 'r_250_4n2' was not found as a program info attribute or as a kernel name
```

</details>

**Comment by wozeparrot** [comment]
The CL param limit has an open issue here: https://github.com/geohot/tinygrad/issues/953

**Comment by chenyuxyz** [comment]
i can run `METAL=1 MODEL=mrcnn python3 examples/mlperf/model_eval.py` on master. while we don't have general per kernel buffer limiting yet, the `OPT` options discussed here have been deprecated, so i am closing this as not planned and will use a different issue to track buffer limiting. feel free to open a new issue if master does not work for you
