### ISSUE TITLE
Out Of Memory error on Mac M1 Pro, 32GB memory when running examples/stable_diffusion.py

### ISSUE THREAD

**Issue by beachwood23** [tinygrad/tinygrad#1400]
Saw two Mac crashes from an OOM when trying to run `python3 examples/stable_diffusion.py`. 

Running with a Mac M1 Pro, 32GB of memory. 

Running on basic `Terminal.app`. Here's an example of the output where the program freezes, and I was able to `ctrl-c` before it killed the computer again:

```
(venv) [~/github/tinygrad]$ python3 examples/stable_diffusion.py                                     [master]
ram used:  4.26 GB, cond_stage_model.transformer.text_model.final_layer_norm.bias: 100%|█| 1131/1131 [00:00<00
loaded weights in 146.54 ms, 4.26 GB loaded at 29.10 GB/s
got CLIP context (1, 77, 768)
got unconditional CLIP context (1, 77, 768)
running for [1, 201, 401, 601, 801] timesteps
  0   1: 100%|██████████████████████████████████████████████████████████████████| 5/5 [00:11<00:00,  2.26s/it]
decode (1, 512, 64, 64)
decode (1, 512, 128, 128)
decode (1, 512, 256, 256)
decode (1, 256, 512, 512)
(512, 512, 3)

^C^C^C^C^CTraceback (most recent call last):
  File "/Users/b23/github/tinygrad/examples/stable_diffusion.py", line 673, in <module>
    im = Image.fromarray(x.numpy())
                         ^^^^^^^^^
  File "/Users/b23/github/tinygrad/tinygrad/tensor.py", line 112, in numpy
    def numpy(self) -> np.ndarray: return self.lazydata.toCPU()
                                          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/b23/github/tinygrad/tinygrad/lazy.py", line 190, in toCPU
    ret = cast(RawBuffer, realized).toCPU().reshape(self.shape)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/b23/github/tinygrad/tinygrad/runtime/lib.py", line 50, in toCPU
    self._copyout(x)
  File "/Users/b23/github/tinygrad/tinygrad/runtime/ops_gpu.py", line 52, in _copyout
    mapped = cl.enqueue_map_buffer(CL.cl_queue[self._buf.device], buf, cl.map_flags.WRITE, 0, self.size, dtype=self.dtype.np)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

Is there a recommended amount of memory to run these examples on an M1? I assume 32GB should be plenty. 

Will take a look later at trying to get around this one, since most of the code seems to be internal to the project.

**Comment by wozeparrot** [comment]
Huh, yea I see this as well, I'll prioritize fixing this.

**Comment by geohot** [comment]
Hmm, works fine for me

**Comment by wozeparrot** [comment]
This should be on the GPU backend.
