### ISSUE TITLE
metal tensor core wmma does not handle const buffers well?

### ISSUE THREAD

**Issue by bogdad** [tinygrad/tinygrad#1585]
The following test fails with TC=1 on METAL (added to test_ops)
```
  def test_matmul_const(self):
    helper_test_op([], lambda: torch.ones(8,8).matmul(torch.ones(8,8)), lambda: Tensor.ones(8,8).matmul(Tensor.ones(8,8)), forward_only=True)
```

```
env DEBUG=10 METAL=1 TC=1 PYTHONPATH=. python3 test/test_ops.py -k "test_matmul_const"
...
======================================================================
ERROR: test_matmul_const (__main__.TestOps.test_matmul_const)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/vladimir/workspace/tinygrad/test/test_ops.py", line 32, in compare
    np.testing.assert_allclose(x,y, atol=atol, rtol=rtol)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/tinygrad3/lib/python3.11/site-packages/numpy/testing/_private/utils.py", line 1508, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/opt/homebrew/Caskroom/miniconda/base/envs/tinygrad3/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/tinygrad3/lib/python3.11/site-packages/numpy/testing/_private/utils.py", line 801, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.001, atol=1e-06

Mismatched elements: 64 / 64 (100%)
Max absolute difference: 8.
Max relative difference: 1.
 x: array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],...
 y: array([[8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8.],...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vladimir/workspace/tinygrad/test/test_ops.py", line 1167, in test_matmul_const
    helper_test_op([], lambda: torch.ones(8,8).matmul(torch.ones(8,8)), lambda: Tensor.ones(8,8).matmul(Tensor.ones(8,8)), forward_only=True)
  File "/Users/vladimir/workspace/tinygrad/test/test_ops.py", line 40, in helper_test_op
    compare("forward pass", ret.numpy(), out.detach().numpy(), atol=atol, rtol=rtol)
  File "/Users/vladimir/workspace/tinygrad/test/test_ops.py", line 34, in compare
    raise Exception(f"{s} failed shape {x.shape}")
Exception: forward pass failed shape (8, 8)

----------------------------------------------------------------------
Ran 1 test in 0.249s
```

It looks like because tensor cores WMMA op is not generated:
```
#include <metal_stdlib>
using namespace metal;
kernel void r_1_2_2_4_2_8_2(device float* data0, uint3 gid [[threadgroup_position_in_grid]], uint3 lid [[thread_position_in_threadgroup]]) {
threadgroup float ldata1[1];
threadgroup float ldata2[1];
{
  { int lidx1 = lid.z;  /* 2 */
  { int lidx2 = lid.y;  /* 2 */
  { int lidx3 = (lid.x/2);  /* 4 */
  { int lidx4 = (lid.x%2);  /* 2 */
    float acc0_0 = 0.0f;
    float acc0_1 = 0.0f;
      threadgroup_barrier(mem_flags::mem_threadgroup);
      float const1_0 = 1.0f;
     /* reduce */
    *(data0+(lidx1*4)+(lidx2*32)+(lidx4*16)+lidx3) = acc0_0;
    *(data0+(lidx1*4)+(lidx2*32)+(lidx4*16)+8+lidx3) = acc0_1;
  }}}}} /* global+local */
}
```

If both const buffer for ones(..) is replaced with ones(…).contigous() mem buff it gets generated and the test passes:
```
helper_test_op([], lambda: torch.ones(8,8).matmul(torch.ones(8,8)), lambda: Tensor.ones(8,8).contiguous().matmul(Tensor.ones(8,8).contiguous()), forward_only=True)
...
#include <metal_stdlib>
using namespace metal;
kernel void r_1_1_2_2_4_2_8_2(device float* data0, const device float* data1, const device float* data2, uint3 gid [[threadgroup_position_in_grid]], uint3 lid [[thread_position_in_threadgroup]]) {
threadgroup float ldata1[64];
threadgroup float ldata2[64];
{
{
  { int lidx2 = lid.z;  /* 2 */
  { int lidx3 = lid.y;  /* 2 */
  { int lidx4 = (lid.x/2);  /* 4 */
  { int lidx5 = (lid.x%2);  /* 2 */
    float2 acc0_0 = float2(0.0f,0.0f);
      threadgroup_barrier(mem_flags::mem_threadgroup);
      float2 val1_0 = (float2)(*((device float2*)(data1+(lidx2*32)+(lidx3*4)+(lidx4*8)+(lidx5*2))));
      float2 val2_0 = (float2)(*((device float2*)(data2+(lidx2*32)+(lidx3*4)+(lidx4*8)+(lidx5*2))));
      { simdgroup_float8x8 a,b,c;
      a.thread_elements()[0] = val1_0.x; a.thread_elements()[1] = val1_0.y;
      b.thread_elements()[0] = val2_0.x; b.thread_elements()[1] = val2_0.y;
      c.thread_elements()[0] = acc0_0.x; c.thread_elements()[1] = acc0_0.y;
      simdgroup_multiply_accumulate(c, a, b, c);
      acc0_0.x = c.thread_elements()[0]; acc0_0.y = c.thread_elements()[1]; }
     /* reduce */
    *((device float2*)(data0+(lidx2*32)+(lidx3*4)+(lidx4*8)+(lidx5*2))) = (float2)acc0_0;
  }}}}}} /* global+local */
}
```

It does pass with TC=0
```
env DEBUG=10 METAL=1 TC=0 PYTHONPATH=. python3 test/test_ops.py -k "test_matmul_const"
Ran 1 test in 0.250s
OK
```

If test is modified to have one buffer .contiguous(), it fails before generating:
```
helper_test_op([], lambda: torch.ones(8,8).matmul(torch.ones(8,8)), lambda: Tensor.ones(8,8).contiguous().matmul(Tensor.ones(8,8)), forward_only=True)
```
```
FAIL: test_matmul_const (__main__.TestOps.test_matmul_const)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/vladimir/workspace/tinygrad/test/test_ops.py", line 1167, in test_matmul_const
    helper_test_op([], lambda: torch.ones(8,8).matmul(torch.ones(8,8)), lambda: Tensor.ones(8,8).contiguous().matmul(Tensor.ones(8,8)), forward_only=True)
  File "/Users/vladimir/workspace/tinygrad/test/test_ops.py", line 25, in helper_test_op
    ret = tinygrad_fxn(*tst).realize()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vladimir/workspace/tinygrad/tinygrad/tensor.py", line 94, in realize
    self.lazydata.realize()
  File "/Users/vladimir/workspace/tinygrad/tinygrad/lazy.py", line 148, in realize
    for x in self.op.buffers: x.realize()
                              ^^^^^^^^^^^
  File "/Users/vladimir/workspace/tinygrad/tinygrad/lazy.py", line 158, in realize
    self.realized = Device[self.device].exec_ast(self.op, output=self, **self._device_extra_args())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vladimir/workspace/tinygrad/tinygrad/ops.py", line 202, in exec_ast
    if k.key not in self.method_cache: self.method_cache[k.key] = get_program()
                                                                  ^^^^^^^^^^^^^
  File "/Users/vladimir/workspace/tinygrad/tinygrad/ops.py", line 198, in get_program
    elif not getenv("NOOPT"): hand_coded_optimizations(k)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vladimir/workspace/tinygrad/tinygrad/codegen/optimizer.py", line 200, in hand_coded_optimizations
    k.upcast()
  File "/Users/vladimir/workspace/tinygrad/tinygrad/codegen/linearizer.py", line 591, in upcast
    assert self.full_shape[-1] != 1, "can't upcast a dimension with size 1"
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can't upcast a dimension with size 1
```

**Comment by bogdad** [comment]
this seems fixed! closing.

does not fail anymore
```
vladimir@FT751F6N7D ~/w/tinygrad (master) [1]> env DEBUG=10 METAL=1 METAL_XCODE=1 TC=1 PYTHONPATH=. CACHELEVEL=0 python test/test_ops.py -k "test_matmul_const"                                                                (tinygrad3)
test_matmul_const (__main__.TestOps) ... st simplify : View(shape=(8, 8, 8), strides=(0, 0, 0), offset=0, mask=None, contiguous=False) + View(shape=(8, 8, 8), strides=(64, 8, 1), offset=0, mask=None, contiguous=True) = View(shape=(8, 8, 8), strides=(0, 0, 0), offset=0, mask=None, contiguous=False)
st simplify : View(shape=(8, 8, 8), strides=(0, 0, 0), offset=0, mask=None, contiguous=False) + View(shape=(8, 8, 8), strides=(64, 8, 1), offset=0, mask=None, contiguous=True) = View(shape=(8, 8, 8), strides=(0, 0, 0), offset=0, mask=None, contiguous=False)
  0 ━┳ STORE MemBuffer(idx=0, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(8, 8, 1), strides=(8, 1, 0), offset=0, mask=None, contiguous=True),)))
  1  ┗━┳ SUM (8, 8, 1)
  2    ┗━┳ MUL
  3      ┣━━ CONST ConstBuffer(val=1.0, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(8, 8, 8), strides=(0, 0, 0), offset=0, mask=None, contiguous=False),)))
  4      ┗━━ CONST ConstBuffer(val=1.0, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(8, 8, 8), strides=(0, 0, 0), offset=0, mask=None, contiguous=False),)))
   0 UOps.DEFINE_GLOBAL  : ptr.dtypes.float          []                               data0
   1 UOps.SPECIAL        : dtypes.int                []                               (0, 'gidx0', 2)
   2 UOps.SPECIAL        : dtypes.int                []                               (0, 'lidx1', 32)
   3 UOps.DEFINE_ACC     : dtypes.float              []                               0.0
   4 UOps.CONST          : dtypes.float              []                               1.0
   5 UOps.ALU            : dtypes.float              [4, 4, 3]                        TernaryOps.MULACC
   6 UOps.ALU            : dtypes.float              [4, 4, 5]                        TernaryOps.MULACC
   7 UOps.ALU            : dtypes.float              [4, 4, 6]                        TernaryOps.MULACC
   8 UOps.ALU            : dtypes.float              [4, 4, 7]                        TernaryOps.MULACC
   9 UOps.ALU            : dtypes.float              [4, 4, 8]                        TernaryOps.MULACC
  10 UOps.ALU            : dtypes.float              [4, 4, 9]                        TernaryOps.MULACC
  11 UOps.ALU            : dtypes.float              [4, 4, 10]                       TernaryOps.MULACC
  12 UOps.ALU            : dtypes.float              [4, 4, 11]                       TernaryOps.MULACC
  13 UOps.CONST          : dtypes.int                []                               32
  14 UOps.ALU            : dtypes.int                [1, 13]                          BinaryOps.MUL
  15 UOps.ALU            : dtypes.int                [14, 2]                          BinaryOps.ADD
  16 UOps.STORE          :                           [0, 15, 12]                      None
#include <metal_stdlib>
using namespace metal;
kernel void r_2_32_8(device float* data0, uint3 gid [[threadgroup_position_in_grid]], uint3 lid [[thread_position_in_threadgroup]]) {
  int gidx0 = gid.x; /* 2 */
  int lidx1 = lid.x; /* 32 */
  float acc0 = 0.0f;
  *(data0+(gidx0*32)+lidx1) = ((1.0f*1.0f)+((1.0f*1.0f)+((1.0f*1.0f)+((1.0f*1.0f)+((1.0f*1.0f)+((1.0f*1.0f)+((1.0f*1.0f)+((1.0f*1.0f)+acc0))))))));
}
xxx libptr 0x600003acb340
compute shader:
   0: f2010000             get_sr           r0.cache, sr0 (threadgroup_position_in_grid.x)
   4: 8e010000ac000000     iadd             r0.cache, 0, r0.discard, lsl 1
   c: 8e0100002c002000     iadd             r0.cache, 0, r0.discard, lsl 4
  14: 620d00000041         mov_imm          r3, 1090519040, 0b0
  1a: 8e0380016c001000     iadd             r0_r1.cache, u0, r0.discard.sx, lsl 2
  22: 72093000             get_sr           r2, sr48 (thread_position_in_threadgroup.x)
  26: 0e05c22218000000     iadd             r1, r1.discard, u1
  2e: 4519400400c01200     device_store     0, i32, x, r3, r0_r1, r2, signed, 0
  36: 8800                 stop


*** METAL      1 r_2_32_8                              arg   1 mem  0.00 GB tm     12.12us/     0.01ms (    0.08 GFLOPS,    0.02 GB/s)
[[8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]]
[[8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]]

testing                                       []   torch/tinygrad fp: 0.39 / 277.22 ms  bp: nan / nan ms ok

----------------------------------------------------------------------
Ran 1 test in 0.282s

```
