### ISSUE TITLE
Eval RNN-T fails: JIT "some input tensors not found" 

### ISSUE THREAD

**Issue by gml16** [tinygrad/tinygrad#1701]
Hello, when running RNN-T in `examples.mlperf.model_eval` I get the following traceback:
```
> python3 -m examples.mlperf.model_eval
eval rnnt
using devices: [('v1', 'NVIDIA Corporation', 4318, 'NVIDIA GeForce RTX 3050 Laptop GPU', 'OpenCL 3.0 CUDA')]
there are 2703 samples in the dataset
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File ./tinygrad/examples/mlperf/model_eval.py", line 246, in <module>
    globals()[nm]()
  File "./tinygrad/examples/mlperf/model_eval.py", line 149, in eval_rnnt
    tt = mdl.decode(Tensor(X[0]), Tensor([X[1]]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./tinygrad/models/rnnt.py", line 28, in decode
    seq = self._greedy_decode(inseq, int(np.ceil(logit_len.numpy()).item()))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./tinygrad/models/rnnt.py", line 45, in _greedy_decode
    jhc = self._pred_joint(Tensor(logit.numpy()), label, hc, mask)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./tinygrad/jit.py", line 52, in __call__
    assert set([x[0] for x in self.input_replace.values()]) == set(input_rawbuffers.keys()), "some input tensors not found"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: some input tensors not found
```
Is this expected?

Let me know if I can provide any other info.

**Comment by scottrcarlson** [comment]
Where did you get the data?

I ran this first;
python extra/datasets/imagenet_download.py

Then:
python3 -m examples.mlperf.model_eval

Seems to be working on NVIDIA 3090 (still running)

**Comment by wozeparrot** [comment]
Can confirm.

Something that needs to be done now that symbolic jit stuff is merged is to get the entirety of rnn-t jitted with it.

**Comment by ZenginU** [comment]
```
  File "./tinygrad/examples/mlperf/model_eval.py", line 149, in eval_rnnt
    tt = mdl.decode(Tensor(X[0]), Tensor([X[1]]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Dont have the dataset but just by looking at it can you update,
`mdl.decode(Tensor(X[0]), Tensor([X[1]])) -> mdl.decode(Tensor([X[0]]), Tensor([X[1]]))`

**Comment by chenyuxyz** [comment]
on latest master i got this jit error:
```
AssertionError: mismatch of sts, expected ((1, ShapeTracker(views=(View(shape=(1, 1, 1024), strides=(0, 0, 1), offset=0, mask=None, contiguous=True),)), dtypes.float), (2, ShapeTracker(views=(View(shape=(1, 1), strides=(0, 0), offset=0, mask=None, contiguous=True),)), dtypes.float), (3, ShapeTracker(views=(View(shape=(2, 2, 320), strides=(0, 0, 0), offset=0, mask=None, contiguous=False),)), dtypes.float), (4, ShapeTracker(views=(View(shape=(1,), strides=(0,), offset=0, mask=None, contiguous=True),)), dtypes.float)) got ((1, ShapeTracker(views=(View(shape=(1, 1, 1024), strides=(0, 0, 1), offset=0, mask=None, contiguous=True),)), dtypes.float), (2, ShapeTracker(views=(View(shape=(1, 1), strides=(0, 0), offset=0, mask=None, contiguous=True),)), dtypes.float), (3, ShapeTracker(views=(View(shape=(2, 2, 320), strides=(640, 320, 1), offset=0, mask=None, contiguous=True),)), dtypes.float), (4, ShapeTracker(views=(View(shape=(1,), strides=(0,), offset=0, mask=None, contiguous=True),)), dtypes.float))
```

**Comment by chenyuxyz** [comment]
closing as stale, rnn-t example is old, and removed from mlperf
