### ISSUE TITLE
examples/stable_diffusion.py attempts to allocate an 18GB array

### ISSUE THREAD

**Issue by kiwidrew** [tinygrad/tinygrad#1853]
Trying to run the example stable_diffusion.py script (using the SD 1.4 checkpoint) results in the Linux OOM killer terminating tinygrad.  The machine has 16GB of RAM.  Setting `ulimit -H -v 12000000` (~12GB vm limit) and running with `DEBUG=3` produces the following output:

```
*** copy CPU <- DISK:sd-v1-4.ckpt size 768 dtype dtypes.float
ram used:  4.26 GB, cond_stage_model.transformer.text_model.final_layer_norm.bias: 100%
loaded weights in 157.62 ms, 4.26 GB loaded at 27.06 GB/s
*** exec  4.26 GB    0.02 ms op: MovementOps.RESHAPE  out(float): (1, 1, 1)                      in(1): [()] (1, 1, 1)
*** exec  4.28 GB    0.04 ms op: MovementOps.EXPAND   out(float): (1, 77, 49408)                 in(1): [(1, 1, 1)] (1, 77, 49408)
*** exec  4.28 GB    0.01 ms op: MovementOps.RESHAPE  out(float): (1,)                           in(1): [()] (1,)
*** exec  4.28 GB    0.01 ms op: MovementOps.EXPAND   out(float): (49408,)                       in(1): [(1,)] (49408,)
*** exec  4.28 GB    0.09 ms op: MovementOps.PAD      out(float): (98815,)                       in(1): [(49408,)] ((49407, 0),)
*** exec  4.28 GB    0.01 ms op: MovementOps.RESHAPE  out(float): (1, 98815)                     in(1): [(98815,)] (1, 98815)
*** exec 23.81 GB    0.01 ms op: MovementOps.EXPAND   out(float): (49409, 98815)                 in(1): [(1, 98815)] (49409, 98815)
Traceback (most recent call last):
  File "stable_diffusion.py", line 588, in <module>
    context = model.cond_stage_model.transformer.text_model(prompt).realize()
  File "tinygrad/tensor.py", line 86, in realize
    self.lazydata.realize()
  File "tinygrad/lazy.py", line 152, in realize
    for x in self.op.buffers: x.realize()
  File "tinygrad/lazy.py", line 152, in realize
    for x in self.op.buffers: x.realize()
  File "tinygrad/lazy.py", line 152, in realize
    for x in self.op.buffers: x.realize()
  [Previous line repeated 60 more times]
  File "tinygrad/lazy.py", line 162, in realize
    self.realized = Device[self.device].exec_ast(self.op, output=self, **self._device_extra_args())
  File "tinygrad/ops.py", line 106, in exec_ast
    ret = self.from_underlying(self.fxn_for_op[ast.op](*([self.to_underlying(x) for x in srcs] + ([ast.arg] if ast.arg is not None else []))))
  File "tinygrad/runtime/ops_cpu.py", line 16, in <lambda>
    MovementOps.RESHAPE: lambda x, arg: x.reshape(arg), MovementOps.SHRINK: lambda x, arg: x[tuple(slice(p[0], p[1], None) for p in arg)],
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 18.2 GiB for an array with shape (49409, 98815) and data type float32
```

Why is it attempting to allocate an 18.2 GiB array?  The array dimension of 49409 looks to come from the `CLIPTextEmbeddings` class which needs an `Embedding(49408, 768)` so where does the 98815 dimension come from?

This is happening on the current HEAD (c91b44f7).  First time using tinygrad, so kind of expected the included examples to work out of the box.  ~Haven't had a chance to try older revisions yet.~  EDIT:  the Stable Diffusion example script *works without issue in v0.6.0* and does not work (same error) in v0.7.0

**Comment by kiwidrew** [comment]
Commit 35bc462 updated `examples/stable_diffusion.py` to use `tinygrad.nn.Embedding` and is the source of this issue.  Using the `stable_diffusion.py` script from just prior to that commit (and tweaking the `import tinygrad.state` line to be `import tinygrad.nn.state`) results in a Stable Diffusion example that works with current tinygrad HEAD.

**Comment by geohot** [comment]
Are you trying to run on CPU backend? Why?
