### ISSUE TITLE
examples/whisper.py doesn't work

### ISSUE THREAD

**Issue by nextgens** [tinygrad/tinygrad#2048]
I have first tried:
```
PYTHONPATH=. CPU=1 DEBUG=1 python3 examples/whisper.py  ../T-22050.wav 
ram used:  0.08 GB, decoder.ln.bias                                   : 100%|██████████████████████████████████████████| 167/167 [00:00<00:00, 4705.07it/s]
loaded weights in 37.21 ms, 0.08 GB loaded at 2.03 GB/s
Traceback (most recent call last):
  File "examples/whisper.py", line 198, in <module>
    waveform, sample_rate = librosa.load(sys.argv[1], normalize=True)
TypeError: load() got an unexpected keyword argument 'normalize'
```

Then without normalize:
```
PYTHONPATH=. python3 examples/whisper.py  ../T-22050.wav 
ram used:  0.11 GB, decoder.ln.bias                                   : 100%|██████████████████████████████████████████| 167/167 [00:00<00:00, 1818.19it/s]
loaded weights in 93.72 ms, 0.11 GB loaded at 1.16 GB/s
/home/rocm-user/.local/lib/python3.8/site-packages/librosa/core/spectrum.py:362: ComplexWarning: Casting complex values to real discards the imaginary part
  stft_matrix[..., :off_start] = fft.rfft(fft_window * y_frames_pre, axis=-2)
/home/rocm-user/.local/lib/python3.8/site-packages/librosa/core/spectrum.py:366: ComplexWarning: Casting complex values to real discards the imaginary part
  stft_matrix[..., -off_end:] = fft.rfft(fft_window * y_frames_post, axis=-2)
/home/rocm-user/.local/lib/python3.8/site-packages/librosa/core/spectrum.py:378: ComplexWarning: Casting complex values to real discards the imaginary part
  stft_matrix[..., bl_s + off_start : bl_t + off_start] = fft.rfft(
Traceback (most recent call last):
  File "examples/whisper.py", line 201, in <module>
    dat = model.encoder(Tensor(log_spec)).realize()
  File "examples/whisper.py", line 71, in __call__
    x = self.conv1(x).gelu()
  File "/app/tinygrad/tinygrad/nn/__init__.py", line 52, in __call__
    return x.conv2d(self.weight, self.bias, padding=self.padding, stride=self.stride, dilation=self.dilation, groups=self.groups)
  File "/app/tinygrad/tinygrad/tensor.py", line 517, in conv2d
    assert groups*cin == cin_ and len(self.shape) == len(weight.shape), f"Input Tensor shape {self.shape} does not match the shape of the weights {weight.shape}. ({groups*cin} vs. {cin_})"
AssertionError: Input Tensor shape (80, 124) does not match the shape of the weights (384, 80, 3). (80 vs. 124)
```

librosa doesn't expect normalize; Can you fix it please?

**Comment by nextgens** [comment]
@lusk4r Thank you for looking into this.

I have now retried with current master and the above patch and I get:
```
$PYTHONPATH=. python3 examples/whisper.py /app/test.wav 
ram used:  0.11 GB, decoder.ln.bias                                   : 100%|███████████████████| 167/167 [00:00<00:00, 2051.79it/s]
loaded weights in 83.21 ms, 0.11 GB loaded at 1.30 GB/s
/home/rocm-user/.local/lib/python3.8/site-packages/librosa/core/spectrum.py:362: ComplexWarning: Casting complex values to real discards the imaginary part
  stft_matrix[..., :off_start] = fft.rfft(fft_window * y_frames_pre, axis=-2)
/home/rocm-user/.local/lib/python3.8/site-packages/librosa/core/spectrum.py:366: ComplexWarning: Casting complex values to real discards the imaginary part
  stft_matrix[..., -off_end:] = fft.rfft(fft_window * y_frames_post, axis=-2)
/home/rocm-user/.local/lib/python3.8/site-packages/librosa/core/spectrum.py:378: ComplexWarning: Casting complex values to real discards the imaginary part
  stft_matrix[..., bl_s + off_start : bl_t + off_start] = fft.rfft(
(1, 80, 53641)
Traceback (most recent call last):
  File "examples/whisper.py", line 202, in <module>
    dat = model.encoder(Tensor(log_spec)).realize()
  File "examples/whisper.py", line 74, in __call__
    x = x + self.positional_embedding[:x.shape[1]]
  File "/app/tinygrad/tinygrad/tensor.py", line 679, in __add__
    def __add__(self, x) -> Tensor: return self.add(x)
  File "/app/tinygrad/tinygrad/tensor.py", line 639, in add
    def add(self, x:Union[Tensor, float], reverse=False) -> Tensor: return mlops.Add.apply(*self._broadcasted(x, reverse)) if x.__class__ is Tensor or x else self
  File "/app/tinygrad/tinygrad/tensor.py", line 636, in _broadcasted
    if yshape != shape_ret: y = y.expand(shape_ret)
  File "/app/tinygrad/tinygrad/tensor.py", line 252, in expand
    def expand(self, shape, *args) -> Tensor: return mlops.Expand.apply(self, shape=tuple([x if x != -1 else s for s,x in zip(self.shape, argfix(shape, *args))]))
  File "/app/tinygrad/tinygrad/tensor.py", line 30, in apply
    ret = Tensor(ctx.forward(*[t.lazydata for t in x], **kwargs), device=ctx.device, requires_grad=ctx.requires_grad)
  File "/app/tinygrad/tinygrad/mlops.py", line 166, in forward
    return x.expand(shape)
  File "/app/tinygrad/tinygrad/lazy.py", line 275, in expand
    return self._movement_op(self.st.expand(arg), MovementOps.EXPAND, arg)
  File "/app/tinygrad/tinygrad/shape/shapetracker.py", line 183, in expand
    return ShapeTracker(self.views[0:-1] + (self.views[-1].expand(new_shape), ))
  File "/app/tinygrad/tinygrad/shape/view.py", line 77, in expand
    assert all(is_sym_int(x) and (s == x or (s == 1 and st == 0)) for s,x,st in zip(self.shape, new_shape, self.strides)), f"can't expand {self.shape} into {new_shape}"
AssertionError: can't expand (1, 1500, 384) into (1, 26821, 384)
```

My test file:
```
$file ../test.wav 
../test.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 16000 Hz
```

**Comment by mmmkkaaayy** [comment]
Try https://github.com/tinygrad/tinygrad/pull/2042

**Comment by nextgens** [comment]
Hmm, running [6e4a12a](https://github.com/tinygrad/tinygrad/commit/6e4a12ab68810ba7150a719ae4c2c274df587db9) I still get the same error.

I think it's the length of the wav file that is problematic: two different files of the same type/encoding with different lengths:
```
PYTHONPATH=. DEBUG=1 python3 examples/whisper.py ../test.wav 
using devices: [('v1', 'Advanced Micro Devices, Inc.', 4098, 'gfx1100', 'OpenCL 2.0 ')]
ram used:  0.11 GB, decoder.ln.bias                                   : 100%|████████████████████████████| 167/167 [00:00<00:00, 1973.87it/s]
loaded weights in 86.55 ms, 0.11 GB loaded at 1.25 GB/s
/home/rocm-user/.local/lib/python3.8/site-packages/librosa/core/spectrum.py:362: ComplexWarning: Casting complex values to real discards the imaginary part
  stft_matrix[..., :off_start] = fft.rfft(fft_window * y_frames_pre, axis=-2)
/home/rocm-user/.local/lib/python3.8/site-packages/librosa/core/spectrum.py:366: ComplexWarning: Casting complex values to real discards the imaginary part
  stft_matrix[..., -off_end:] = fft.rfft(fft_window * y_frames_post, axis=-2)
/home/rocm-user/.local/lib/python3.8/site-packages/librosa/core/spectrum.py:378: ComplexWarning: Casting complex values to real discards the imaginary part
  stft_matrix[..., bl_s + off_start : bl_t + off_start] = fft.rfft(
Traceback (most recent call last):
  File "examples/whisper.py", line 237, in <module>
    transcribe_file(model, enc, sys.argv[1])
  File "examples/whisper.py", line 221, in transcribe_file
    dat = model.encoder(Tensor(log_spec)).realize()
  File "examples/whisper.py", line 74, in __call__
    x = x + self.positional_embedding[:x.shape[1]]
  File "/app/tinygrad/tinygrad/tensor.py", line 679, in __add__
    def __add__(self, x) -> Tensor: return self.add(x)
  File "/app/tinygrad/tinygrad/tensor.py", line 639, in add
    def add(self, x:Union[Tensor, float], reverse=False) -> Tensor: return mlops.Add.apply(*self._broadcasted(x, reverse)) if x.__class__ is Tensor or x else self
  File "/app/tinygrad/tinygrad/tensor.py", line 636, in _broadcasted
    if yshape != shape_ret: y = y.expand(shape_ret)
  File "/app/tinygrad/tinygrad/tensor.py", line 252, in expand
    def expand(self, shape, *args) -> Tensor: return mlops.Expand.apply(self, shape=tuple([x if x != -1 else s for s,x in zip(self.shape, argfix(shape, *args))]))
  File "/app/tinygrad/tinygrad/tensor.py", line 30, in apply
    ret = Tensor(ctx.forward(*[t.lazydata for t in x], **kwargs), device=ctx.device, requires_grad=ctx.requires_grad)
  File "/app/tinygrad/tinygrad/mlops.py", line 166, in forward
    return x.expand(shape)
  File "/app/tinygrad/tinygrad/lazy.py", line 275, in expand
    return self._movement_op(self.st.expand(arg), MovementOps.EXPAND, arg)
  File "/app/tinygrad/tinygrad/shape/shapetracker.py", line 183, in expand
    return ShapeTracker(self.views[0:-1] + (self.views[-1].expand(new_shape), ))
  File "/app/tinygrad/tinygrad/shape/view.py", line 77, in expand
    assert all(is_sym_int(x) and (s == x or (s == 1 and st == 0)) for s,x,st in zip(self.shape, new_shape, self.strides)), f"can't expand {self.shape} into {new_shape}"
AssertionError: can't expand (1, 1500, 384) into (1, 19462, 384)
```

```
PYTHONPATH=. DEBUG=1 python3 examples/whisper.py ../test2.wav 
using devices: [('v1', 'Advanced Micro Devices, Inc.', 4098, 'gfx1100', 'OpenCL 2.0 ')]
ram used:  0.11 GB, decoder.ln.bias                                   : 100%|████████████████████████████| 167/167 [00:00<00:00, 1847.22it/s]
loaded weights in 92.35 ms, 0.11 GB loaded at 1.18 GB/s
/home/rocm-user/.local/lib/python3.8/site-packages/librosa/core/spectrum.py:362: ComplexWarning: Casting complex values to real discards the imaginary part
  stft_matrix[..., :off_start] = fft.rfft(fft_window * y_frames_pre, axis=-2)
/home/rocm-user/.local/lib/python3.8/site-packages/librosa/core/spectrum.py:366: ComplexWarning: Casting complex values to real discards the imaginary part
  stft_matrix[..., -off_end:] = fft.rfft(fft_window * y_frames_post, axis=-2)
/home/rocm-user/.local/lib/python3.8/site-packages/librosa/core/spectrum.py:378: ComplexWarning: Casting complex values to real discards the imaginary part
  stft_matrix[..., bl_s + off_start : bl_t + off_start] = fft.rfft(
Traceback (most recent call last):
  File "examples/whisper.py", line 237, in <module>
    transcribe_file(model, enc, sys.argv[1])
  File "examples/whisper.py", line 221, in transcribe_file
    dat = model.encoder(Tensor(log_spec)).realize()
  File "examples/whisper.py", line 74, in __call__
    x = x + self.positional_embedding[:x.shape[1]]
  File "/app/tinygrad/tinygrad/tensor.py", line 679, in __add__
    def __add__(self, x) -> Tensor: return self.add(x)
  File "/app/tinygrad/tinygrad/tensor.py", line 639, in add
    def add(self, x:Union[Tensor, float], reverse=False) -> Tensor: return mlops.Add.apply(*self._broadcasted(x, reverse)) if x.__class__ is Tensor or x else self
  File "/app/tinygrad/tinygrad/tensor.py", line 636, in _broadcasted
    if yshape != shape_ret: y = y.expand(shape_ret)
  File "/app/tinygrad/tinygrad/tensor.py", line 252, in expand
    def expand(self, shape, *args) -> Tensor: return mlops.Expand.apply(self, shape=tuple([x if x != -1 else s for s,x in zip(self.shape, argfix(shape, *args))]))
  File "/app/tinygrad/tinygrad/tensor.py", line 30, in apply
    ret = Tensor(ctx.forward(*[t.lazydata for t in x], **kwargs), device=ctx.device, requires_grad=ctx.requires_grad)
  File "/app/tinygrad/tinygrad/mlops.py", line 166, in forward
    return x.expand(shape)
  File "/app/tinygrad/tinygrad/lazy.py", line 275, in expand
    return self._movement_op(self.st.expand(arg), MovementOps.EXPAND, arg)
  File "/app/tinygrad/tinygrad/shape/shapetracker.py", line 183, in expand
    return ShapeTracker(self.views[0:-1] + (self.views[-1].expand(new_shape), ))
  File "/app/tinygrad/tinygrad/shape/view.py", line 77, in expand
    assert all(is_sym_int(x) and (s == x or (s == 1 and st == 0)) for s,x,st in zip(self.shape, new_shape, self.strides)), f"can't expand {self.shape} into {new_shape}"
AssertionError: can't expand (1, 1500, 384) into (1, 5559, 384)
```

**Comment by lusk4r** [comment]
@nextgens, in  #2068 I tried to split the waveform in chunks in order to fit the required dimensions

**Comment by nextgens** [comment]
Thank you.

That works when applied on top of master!

It seems real slow compared to the original but it does output something :tada:

**Comment by nextgens** [comment]
Looks like there was #1410 too that was WIP on this

**Comment by mmmkkaaayy** [comment]
#2378 adds support for >30s audio transcription

**Comment by nextgens** [comment]
Great, thank you.

This is solved
