### ISSUE TITLE
ValueError accessing element of a padded Tensor

### ISSUE THREAD

**Issue by andresgit** [tinygrad/tinygrad#2177]
The command `Tensor([5,6]).pad(((1,0),))[0].numpy()` gives me a `ValueError`.

I'm running Arch Linux on an Intel based laptop. I installed a fresh ubuntu:latest docker container, then using apt installed git, python3 and python3-pip, then did the "Installation From source" instructions from the tinygrad GitHub Readme. This is what I get:

```python
>>> from tinygrad.tensor import Tensor
>>> Tensor([5,6]).pad(((1,0),)).numpy()
array([0., 5., 6.], dtype=float32)
>>> Tensor([5,6]).pad(((1,0),))[1].numpy()
array(5., dtype=float32)
>>> Tensor([5,6]).pad(((1,0),))[2].numpy()
array(6., dtype=float32)
>>> Tensor([5,6]).pad(((1,0),))[0].numpy()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/tinygrad/tinygrad/tensor.py", line 126, in numpy
    return self.detach().cast(dtypes.from_np(self.dtype.np)).contiguous().to('CPU').realize().lazydata.realized.toCPU().reshape(self.shape)
  File "/root/tinygrad/tinygrad/tensor.py", line 105, in realize
    run_schedule(self.lazydata.schedule())
  File "/root/tinygrad/tinygrad/realize.py", line 27, in run_schedule
    si.out.realized = Device[si.out.device].exec_ast(si.ast, output=si.out, inputs=si.inputs, var_vals=si.var_vals, **si.out._device_extra_args())
  File "/root/tinygrad/tinygrad/ops.py", line 133, in exec_ast
    srcs = [self.exec_ast(cast(LazyOp, x), inputs=inputs, context=context, **kwargs) for x in ast.src]
  File "/root/tinygrad/tinygrad/ops.py", line 133, in <listcomp>
    srcs = [self.exec_ast(cast(LazyOp, x), inputs=inputs, context=context, **kwargs) for x in ast.src]
  File "/root/tinygrad/tinygrad/ops.py", line 126, in exec_ast
    for mop,arg in ast.arg.st.to_movement_ops(): buf = self.fxn_for_op[mop](buf, arg)
  File "/root/tinygrad/tinygrad/runtime/ops_cpu.py", line 41, in <lambda>
    MovementOps.AS_STRIDED: lambda x, arg: np.ndarray(arg[0], buffer=np.require(x, requirements='C'), dtype=x.dtype, offset=arg[2]*x.dtype.itemsize, strides=tuple(y*x.dtype.itemsize for y in arg[1])),
ValueError: strides is incompatible with shape of requested array and size of buffer
```

**Comment by andresgit** [comment]
I ran git bisect between the current head (gives the error above) and v0.7.0 (works) and I got that the problem starts with commit 73a6ed78627cfa7b022fce6b32cfd6501c0c65b7

**Comment by barathsku** [comment]
The issue can be reproduced on Windows (miniconda, Python 3.10) using CPU=1 flag.

**Comment by imaolo** [comment]
Pretty sure this is only a problem with interpreted backends.

**Comment by chenyuxyz** [comment]
`Tensor([5,6]).pad(((1,0),))[0].numpy()` still fails for interpreted backends

**Comment by andresgit** [comment]
For me it now works on master after PR #2529 with both device CPU and TORCH (returns an array with 0.0).

The CI has this test now, which is similar to that case (with value=0) and passes on the CI:

```python
helper_test_op([(4)], lambda x: torch.nn.functional.pad(x,(1,0), value=value)[0], lambda x: x.pad(((1,0),), value=value)[0])
```

Does this test pass on your computer?

**Comment by chenyuxyz** [comment]
my bad, it works now on master for me. closing this one as complete. thanks for fixing the issue!
