### ISSUE TITLE
Extra not Found

### ISSUE THREAD

**Issue by kid-gorgeous** [tinygrad/tinygrad#2202]
Extra is not found??????????? ?R >AJalskHuH?djA?

Sorry for spam like formatting, its how my brain reacted to this. I think its just python being pythonic

```shell

using GPU backend
using gpt2-medium
Traceback (most recent call last):
  File "/Users/evan/tinygrad/examples/gpt2.py", line 214, in <module>
    gpt2 = GPT2.build(args.model_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/evan/tinygrad/examples/gpt2.py", line 151, in build
    from extra.utils import fetch_as_file
ModuleNotFoundError: No module named 'extra'

```

I've also tried appending the file path with:
```python3
import sys
sys.path.append('/Users/<name>/tinygrad/extra')
```

**Comment by geohot** [comment]
`sys.path.append('/Users/<name>/tinygrad')`
