### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by merajhasan88** [tinygrad/tinygrad#2229]
Ran the basic [demo matmul](https://github.com/tinygrad/tinygrad#quick-example-comparing-to-pytorch) stored in tinygrad_demo.py. Using `Windows 10` and running `python 3.11` in a `virutalenv`.

It was working fine yesterday but then this error started occurring:

```
Traceback (most recent call last):
  File "C:\Users\MerajHasan\tiny1\tinygrad\tinygrad_demo.py", line 8, in <module>
    print(x.grad.numpy())  # dz/dx
          ^^^^^^^^^^^^^^
  File "C:\Users\MerajHasan\tiny1\tinygrad\tinygrad\tensor.py", line 126, in numpy
    return self.detach().cast(dtypes.from_np(self.dtype.np)).contiguous().to('CPU').realize().lazydata.realized.toCPU().reshape(self.shape)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MerajHasan\tiny1\tinygrad\tinygrad\tensor.py", line 105, in realize
    run_schedule(self.lazydata.schedule())
  File "C:\Users\MerajHasan\tiny1\tinygrad\tinygrad\realize.py", line 27, in run_schedule
    si.out.realized = Device[si.out.device].exec_ast(si.ast, output=si.out, inputs=si.inputs, var_vals=si.var_vals, **si.out._device_extra_args())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MerajHasan\tiny1\tinygrad\tinygrad\ops.py", line 292, in exec_ast
    if ast not in self.method_cache: self.method_cache[ast] = get_program()
                                                              ^^^^^^^^^^^^^
  File "C:\Users\MerajHasan\tiny1\tinygrad\tinygrad\ops.py", line 289, in get_program
    return self.to_program(k)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\MerajHasan\tiny1\tinygrad\tinygrad\ops.py", line 239, in to_program
    display_name=k.display_name, runtime_args=runtime_args).build(self.compiler, self.runtime)
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MerajHasan\tiny1\tinygrad\tinygrad\ops.py", line 193, in build
    self.lib = compiler.__wrapped__(self.prg) if getenv("DISABLE_COMPILER_CACHE") else compiler(self.prg)
                                                                                       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\MerajHasan\tiny1\tinygrad\tinygrad\helpers.py", line 206, in wrapper
    return diskcache_put(table, key, func(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MerajHasan\tiny1\tinygrad\tinygrad\helpers.py", line 190, in diskcache_put
    conn = db_connection()
           ^^^^^^^^^^^^^^^
  File "C:\Users\MerajHasan\tiny1\tinygrad\tinygrad\helpers.py", line 167, in db_connection
    _db_connection = sqlite3.connect(CACHEDB)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
```

Runs fine on my `ubuntu 22.04`.

**Comment by wozeparrot** [comment]
https://github.com/tinygrad/tinygrad/issues/1377#issuecomment-1658900746

But it does seem like there are some other issues with sqlite: https://canary.discord.com/channels/1068976834382925865/1070745817025106080/1171354825552834580

**Comment by merajhasan88** [comment]
Works like a charm now. Thanks @2-5
