### ISSUE TITLE
Error in LLaMA Example with Quantization: KeyError on <BufferOps.CONST: 2>

### ISSUE THREAD

**Issue by nsosio** [tinygrad/tinygrad#2381]
**Bug Description:**

When running the llama example with quantisation (with CUDA on a A100) using the command:

```bash
python examples/llama.py --quantize
```

the script raises an error with the following traceback:

```bash
using GPU backend
using LLaMA-7B model
Traceback (most recent call last):
  File "/home/paperspace/repositories/benchmarks/bench_tinygrad/tinygrad/examples/llama.py", line 496, in <module>
    llama = LLaMa.build(MODEL_PATH, TOKENIZER_PATH, model_gen=args.gen, model_size=args.size, quantize=args.quantize)
  File "/home/paperspace/repositories/benchmarks/bench_tinygrad/tinygrad/examples/llama.py", line 298, in build
    for _, v in weights.items(): v.realize()
  File "/home/paperspace/repositories/benchmarks/bench_tinygrad/tinygrad/tinygrad/tensor.py", line 103, in realize
    run_schedule(self.lazydata.schedule())
  ...
  KeyError: <BufferOps.CONST: 2>
```

**Error Details:**

The error occurs during the realization of weights in the llama example. The script attempts to interpret an abstract syntax tree (AST), and a KeyError is raised for the operation <BufferOps.CONST: 2>.

**Comment by chenyuxyz** [comment]
likely stale, feel free to open a new issue
