### ISSUE TITLE
Bug in comparator for SumNodes containing MulNodes

### ISSUE THREAD

**Issue by PaulGustafson** [tinygrad/tinygrad#2449]
The following well-typed unit test fails 

```
  def test_sumnode_mulnode_lt(self):
    a = Variable("a", 1, 2)
    b = Variable("b", 1, 2)
    c = Variable("c", 1, 2)
    x = SumNode([MulNode(a, b), c])

    assert isinstance((x < 1), Node)
```
with error message
```
Traceback (most recent call last):
  File "/Users/paul/Developer/tinygrad/test/unit/test_symbolic.py", line 403, in test_sumnode_mulnode_lt
    assert isinstance((x < 1), Node)
  File "/Users/paul/Developer/tinygrad/tinygrad/shape/symbolic.py", line 293, in __lt__
    for x in muls: mul_gcd = gcd(mul_gcd, x.b)  # type: ignore  # mypy cannot tell x.b is int here
TypeError: 'Variable' object cannot be interpreted as an integer
```

Proposed solution:

Add a gcd method to the Node class.

**Comment by PaulGustafson** [comment]
I put in a minimal PR #2450 that just checks if the argument is an int, which fixes the bug.    I could also write gcd for Node if people think it would be useful to have more reductions.
