### ISSUE TITLE
pyopencl._cl.LogicError: clCreateProgramWithBinary failed: INVALID_VALUE when executing examples/coder.py 

### ISSUE THREAD

**Issue by piqoni** [tinygrad/tinygrad#2486]
OS: Mac OS Sonoma Version 14.1.1
Laptop: Apple M1, 16 GB RAM
tinygrad==0.7.0

How to reproduce:
```
python examples/coder.py
```
tinygrad|master ⇒ python3 examples/coder.py
create model: 182.90 ms
creating model cache at /tmp/cached_openhermes.safetensors
download weights: 169.46 ms
ram used:  0.00 GB, layers.0.attention.wq.weight                      :   0%|                  | 0/292 [00:00<?, ?it/s]
loaded weights in 170.69 ms, 0.10 GB loaded at 0.59 GB/s
weights -> model: 175.03 ms
Traceback (most recent call last):
  File "/Users/pers/ai/tinygrad/examples/coder.py", line 48, in <module>
    if not os.path.isfile(cached_model): create_model_cache(cached_model, model)
  File "/Users/pers/ai/tinygrad/examples/coder.py", line 31, in create_model_cache
    nn.state.load_state_dict(model, convert_from_huggingface(part1, model, 32, 8), strict=False)
  File "/Users/pers/ai/tinygrad/tinygrad/nn/state.py", line 60, in load_state_dict
    v.assign(state_dict[k].to(v.device)).realize()
  File "/Users/pers/ai/tinygrad/tinygrad/tensor.py", line 104, in realize
    run_schedule(self.lazydata.schedule())
  File "/Users/pers/ai/tinygrad/tinygrad/realize.py", line 41, in run_schedule
    Device[si.out.device].get_runner(si.ast).exec([si.out.realized] + [x.realized for x in si.inputs], si.var_vals)
  File "/Users/pers/ai/tinygrad/tinygrad/ops.py", line 277, in get_runner
    def get_runner(self, ast:LazyOp) -> CompiledASTRunner: return self.to_program(_get_optimized_linearizer(self.linearizer_opts, ast))
  File "/Users/pers/ai/tinygrad/tinygrad/ops.py", line 274, in to_program
    return CompiledASTRunner(k.ast, k.name, src, k.global_size, k.local_size, runtime_args).build(self.compiler, self.runtime)
  File "/Users/pers/ai/tinygrad/tinygrad/ops.py", line 245, in build
    self.clprg = runtime(self.name, self.lib)
  File "/Users/pers/ai/tinygrad/tinygrad/runtime/ops_gpu.py", line 75, in __init__
    self.name, self.clprograms = name, [cl.Program(ctx, ctx.devices, [prg]*len(ctx.devices)) for ctx in CL.cl_ctxs]
  File "/Users/pers/ai/tinygrad/tinygrad/runtime/ops_gpu.py", line 75, in <listcomp>
    self.name, self.clprograms = name, [cl.Program(ctx, ctx.devices, [prg]*len(ctx.devices)) for ctx in CL.cl_ctxs]
  File "/opt/homebrew/lib/python3.10/site-packages/pyopencl/__init__.py", line 421, in __init__
    self._prg = _cl._Program(context, device, binaries)
pyopencl._cl.LogicError: clCreateProgramWithBinary failed: INVALID_VALUE

**Comment by geohot** [comment]
That's probably not enough RAM

**Comment by chenyuxyz** [comment]
Closing this as obsolete. We don't use `pyopencl` anymore.
