### ISSUE TITLE
getitem does not match torch/numpy

### ISSUE THREAD

**Issue by chenyuxyz** [tinygrad/tinygrad#2511]
will look into adding numpy/torch test cases before trying to fix this
(https://github.com/pytorch/pytorch/blob/main/test/test_indexing.py)

reproduce
```
from tinygrad import Tensor
import torch
import numpy as np

a = np.ones((3, 3))
print(f"{a[:, [2]]=}")

a = torch.ones((3, 3))
print(f"{a[:, [2]]=}")

a = Tensor.ones((3, 3))
print(f"{a[:, [2]]=}")
```

output
```
a[:, [2]]=array([[1.],
       [1.],
       [1.]])
a[:, [2]]=tensor([[1.],
        [1.],
        [1.]])
Traceback (most recent call last):
  File "/Users/chenyu/code/tinygrad/extra/slice_to_st.py", line 12, in <module>
    print(f"{a[:, [2]]=}")
             ~^^^^^^^^
  File "/Users/chenyu/code/tinygrad/tinygrad/tensor.py", line 339, in __getitem__
    dim_shape = next(it_shape)
                ^^^^^^^^^^^^^^
StopIteration
```

**Comment by chenyuxyz** [comment]
roughly the things we need
(1) index with a list, with this we can enable a lot more tests
(2) better errors, IndexError ValueError, for now it's all from a StopIteration
(3) getitem returns the same Tensor with a shapetracker if possible
(4) setitem
(4) setitem in-place assigns if possible (ultimate goal)
