### ISSUE TITLE
AttributeError: 'Buffer' object has no attribute 'allocator'

### ISSUE THREAD

**Issue by okias** [tinygrad/tinygrad#2658]
On arm64 + freedreno (Adreno 630) it fails like this, on x86_64 with iris (Intel) it works well
```
RUSTICL_ENABLE=msm GPU=1 PYTHONPATH="." JIT=0 python examples/gpt2.p
y --model_size=gpt2 --prompt "Hello." --count 10 --temperature 0 --timing
using GPU backend
using gpt2
ram used:  0.00 GB, wte.weight                                        :   0%| | 0/149 [00:00<?,
loaded weights in 115.66 ms, 0.00 GB loaded at 0.00 GB/s
Traceback (most recent call last):
  File "/home/user/tinygrad/examples/gpt2.py", line 188, in <module>
    gpt2 = GPT2.build(args.model_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tinygrad/examples/gpt2.py", line 133, in build
    load_state_dict(model, weights)
  File "/home/user/tinygrad/tinygrad/nn/state.py", line 61, in load_state_dict
    v.assign(state_dict[k].to(v.device)).realize()
  File "/home/user/tinygrad/tinygrad/tensor.py", line 105, in realize
    run_schedule(self.lazydata.schedule())
  File "/home/user/tinygrad/tinygrad/realize.py", line 32, in run_schedule
    Buffer(si.out.device, prod((s if isinstance(s, int) else s.max for s in si.out.shape)), si.out.dtype)
  File "/home/user/tinygrad/tinygrad/device.py", line 68, in __init__
    self.allocator = Device[self.device].allocator
                     ~~~~~~^^^^^^^^^^^^^
  File "/home/user/tinygrad/tinygrad/device.py", line 19, in __getitem__
    def __getitem__(self, ix:str) -> Union[Interpreted, Compiled]: return self.__get_canonicalized_item(self.canonicalize(ix))
                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tinygrad/tinygrad/device.py", line 24, in __get_canonicalized_item
    if isinstance(ret, type): ret = ret(ix)
                                    ^^^^^^^
  File "/home/user/tinygrad/tinygrad/runtime/ops_gpu.py", line 91, in __init__
    self.queue = checked(cl.clCreateCommandQueue(self.context, self.device_id, cl.CL_QUEUE_PROFILING_ENABLE, ctypes.byref(status)), status)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tinygrad/tinygrad/runtime/ops_gpu.py", line 14, in checked
    def checked(ret, status): return (check(status.value), ret)[1]
                                      ^^^^^^^^^^^^^^^^^^^
  File "/home/user/tinygrad/tinygrad/runtime/ops_gpu.py", line 13, in check
    if status != 0: raise RuntimeError(f"OpenCL Error {status}")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: OpenCL Error -35
Exception ignored in: <function Buffer.__del__ at 0xffff937b8ae0>
Traceback (most recent call last):
  File "/home/user/tinygrad/tinygrad/device.py", line 76, in __del__
    else: self.allocator.free(self._buf, self.size * self.dtype.itemsize)
          ^^^^^^^^^^^^^^
AttributeError: 'Buffer' object has no attribute 'allocator'
```

**Comment by okias** [comment]
Thank you! I'll check it.
