### ISSUE TITLE
pyo3_runtime.PanicException: no entry found for key

### ISSUE THREAD

**Issue by okias** [tinygrad/tinygrad#2661]
- System: OnePlus 6
- Distro: Alpine; aarch64

Problem: 1/5 it passes, 4/5 this error:
```
RUST_BACKTRACE=full GPU=0 PYTHONPATH="." JIT=0 python examples/gpt2.py --model_size=gpt2 --prompt "Hello." --count 1 --temperature 0 --timing
using GPU backend
using gpt2
ram used:  0.50 GB, lm_head.weight                                    : 100%|██████████████████████████████████████████████████████████████████████████████| 149/149 [00:00<00:00, 1000.89it/s]
loaded weights in 156.46 ms, 0.65 GB loaded at 4.17 GB/s

ran model in 527.45 ms
total 1758.13 ms
thread '<unnamed>' panicked at src/lib.rs:201:64:
no entry found for key
stack backtrace:
   0:     0xffff79d3eb78 - std::backtrace_rs::backtrace::libunwind::trace::hdafb053dc2cfd244
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0xffff79d3eb78 - std::backtrace_rs::backtrace::trace_unsynchronized::h424e135f3d95adc0
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0xffff79d3eb78 - std::sys_common::backtrace::_print_fmt::hbc6d5d3582b82108
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:67:5
   3:     0xffff79d3eb78 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcedd63c5a711f6d7
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:44:22
   4:     0xffff79d5ab88 - core::fmt::rt::Argument::fmt::h7f031064eb6d9013
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/rt.rs:138:9
   5:     0xffff79d5ab88 - core::fmt::write::h8217a0a05b5238cb
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:1114:21
   6:     0xffff79d3c784 - std::io::Write::write_fmt::hc7cb54c2ed744e33
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/io/mod.rs:1763:15
   7:     0xffff79d3e9ac - std::sys_common::backtrace::_print::hf0252308a448fa19
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:47:5
   8:     0xffff79d3e9ac - std::sys_common::backtrace::print::h7d57eb694a692b20
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:34:9
   9:     0xffff79d3fd04 - std::panicking::default_hook::{{closure}}::h370986151e806b93
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:272:22
  10:     0xffff79d3fa18 - std::panicking::default_hook::h17c6d453318c43b5
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:292:9
  11:     0xffff79d403e0 - std::panicking::rust_panic_with_hook::hde5858b3e3164837
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:731:13
  12:     0xffff79d40194 - std::panicking::begin_panic_handler::{{closure}}::h54807ec82fc9149c
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:609:13
  13:     0xffff79d3f05c - std::sys_common::backtrace::__rust_end_short_backtrace::h6989cb4cbf00473e
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:170:18
  14:     0xffff79d3feec - rust_begin_unwind
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
  15:     0xffff79c443a8 - core::panicking::panic_fmt::h07ff1ea62161dfce
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
  16:     0xffff79c44374 - core::panicking::panic_display::h67c99dbafaba0ad6
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:168:5
  17:     0xffff79c44374 - core::panicking::panic_str::h58ea9a0936e291d7
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:152:5
  18:     0xffff79c44374 - core::option::expect_failed::h23b70782e17c5172
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/option.rs:1988:5
  19:     0xffff79c46350 - _tiktoken::CoreBPE::_decode_native::hf165e3108f34bafb
  20:     0xffff79c4aa54 - _tiktoken::_::<impl _tiktoken::CoreBPE>::__pymethod_decode_bytes__::h12c81175794eebd2
  21:     0xffff79c45a80 - pyo3::impl_::trampoline::fastcall_with_keywords::hd04f9149c7c01d49
  22:     0xffff8c59ab30 - <unknown>
  23:     0xffff8c56be80 - PyObject_Vectorcall
  24:     0xffff8c55cf44 - _PyEval_EvalFrameDefault
  25:     0xffff8c55a340 - <unknown>
  26:     0xffff8c5f9ce8 - PyEval_EvalCode
  27:     0xffff8c62359c - <unknown>
  28:     0xffff8c61e5e4 - <unknown>
  29:     0xffff8c63b87c - <unknown>
  30:     0xffff8c63aabc - _PyRun_SimpleFileObject
  31:     0xffff8c63a540 - _PyRun_AnyFileObject
  32:     0xffff8c63255c - Py_RunMain
  33:     0xffff8c5e6f5c - Py_BytesMain
  34:     0xffff8c9d6544 - <unknown>
Traceback (most recent call last):
  File "/home/user/tinygrad/examples/gpt2.py", line 197, in <module>
    texts = gpt2.greedy_until(args.prompt, args.count, args.temperature, timing=args.timing, batch_size=args.batch_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tinygrad/examples/gpt2.py", line 161, in greedy_until
    output = [self.tokenizer.decode(x) for x in toks]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tinygrad/examples/gpt2.py", line 161, in <listcomp>
    output = [self.tokenizer.decode(x) for x in toks]
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/tiktoken/core.py", line 254, in decode
    return self._core_bpe.decode_bytes(tokens).decode("utf-8", errors=errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: no entry found for key
```

**Comment by okias** [comment]
for `IMAGE=2` so far `-40` = `CL_INVALID_IMAGE_SIZE`, but I guess this can be fixed within Mesa3D :)
