### ISSUE TITLE
CUDA Jit Error

### ISSUE THREAD

**Issue by reddyn12** [tinygrad/tinygrad#3016]
```python
from tinygrad import Tensor
from tinygrad.jit import TinyJit


N = 1024#*16
X = Tensor.kaiming_uniform(N, N)#.realize()
W = Tensor.kaiming_uniform(N, N)#.realize()

@TinyJit
def testFunc(x,y):
    t = x@y
    t = t.sum(1)
    return t.realize()
O = testFunc(X, W)
```

ERROR:
```
[nr620@gpu009 tinygrad]$ DEBUG=3 CUDA=1 python3 examples/testMulti.py 
*** CUDA   rand  seed 1704423797 size 1048576         dtype dtypes.float
  0 ━┳ STORE MemBuffer(idx=0, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(1024, 1024), strides=(1024, 1), offset=0, mask=None, contiguous=True),)))
  1  ┗━┳ ADD 
  2    ┣━┳ MUL 
  3    ┃ ┣━━ CONST ConstBuffer(val=0.15308545484255376, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(1024, 1024), strides=(0, 0), offset=0, mask=None, contiguous=False),)))
  4    ┃ ┗━━ LOAD MemBuffer(idx=1, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(1024, 1024), strides=(1024, 1), offset=0, mask=None, contiguous=True),)))
  5    ┗━━ CONST ConstBuffer(val=-0.07654272742127688, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(1024, 1024), strides=(0, 0), offset=0, mask=None, contiguous=False),)))
Traceback (most recent call last):
  File "/cache/home/nr620/tinygrad/examples/testMulti.py", line 50, in <module>
    O = testFunc(X, W)
  File "/cache/home/nr620/tinygrad/tinygrad/jit.py", line 54, in __call__
    input_tensors: Dict[Union[int, str], LazyBuffer] = {cast(Union[int, str], k):v.realize().lazydata for k,v in itertools.chain(enumerate(args), kwargs.items()) if v.__class__ is Tensor}  # noqa: E501
  File "/cache/home/nr620/tinygrad/tinygrad/jit.py", line 54, in <dictcomp>
    input_tensors: Dict[Union[int, str], LazyBuffer] = {cast(Union[int, str], k):v.realize().lazydata for k,v in itertools.chain(enumerate(args), kwargs.items()) if v.__class__ is Tensor}  # noqa: E501
  File "/cache/home/nr620/tinygrad/tinygrad/tensor.py", line 110, in realize
    run_schedule(self.lazydata.schedule())
  File "/cache/home/nr620/tinygrad/tinygrad/realize.py", line 30, in run_schedule
    prg = lower_schedule_item(si)
  File "/cache/home/nr620/tinygrad/tinygrad/realize.py", line 21, in lower_schedule_item
    return Device[si.out.device].get_runner(si.ast)
  File "/cache/home/nr620/tinygrad/tinygrad/device.py", line 321, in get_runner
    def get_runner(self, ast:LazyOp) -> CompiledASTRunner: return self.to_program(self.get_linearizer(ast))
  File "/cache/home/nr620/tinygrad/tinygrad/device.py", line 293, in to_program
    return CompiledASTRunner(k.ast, k.name, src, lib, k.global_size, k.local_size).build(self.runtime)
  File "/cache/home/nr620/tinygrad/tinygrad/device.py", line 255, in build
    self.clprg = runtime(self.name, self.lib)
  File "/cache/home/nr620/tinygrad/tinygrad/runtime/ops_cuda.py", line 48, in __init__
    self.module = init_c_var(cuda.CUmodule(), lambda x: check(cuda.cuModuleLoadData(ctypes.byref(x), lib)))
  File "/cache/home/nr620/tinygrad/tinygrad/helpers.py", line 182, in init_c_var
    def init_c_var(ctypes_var, creat_cb): return (creat_cb(ctypes_var), ctypes_var)[1]
  File "/cache/home/nr620/tinygrad/tinygrad/runtime/ops_cuda.py", line 48, in <lambda>
    self.module = init_c_var(cuda.CUmodule(), lambda x: check(cuda.cuModuleLoadData(ctypes.byref(x), lib)))
  File "/cache/home/nr620/tinygrad/tinygrad/runtime/ops_cuda.py", line 28, in check
    if status != 0: raise RuntimeError(f"CUDA Error {status}, {ctypes.string_at(init_c_var(ctypes.POINTER(ctypes.c_char)(), lambda x: cuda.cuGetErrorString(status, ctypes.byref(x)))).decode()}")  # noqa: E501
RuntimeError: CUDA Error 218, a PTX JIT compilation failed
Exception ignored in: <function CUDAProgram.__del__ at 0x7fe3737caaf0>
Traceback (most recent call last):
  File "/cache/home/nr620/tinygrad/tinygrad/runtime/ops_cuda.py", line 53, in __del__
    if not CUDACPU: check(cuda.cuModuleUnload(self.module))
AttributeError: 'CUDAProgram' object has no attribute 'module'
```

**Comment by reddyn12** [comment]
self.module is never instantiated in the init method

**Comment by reddyn12** [comment]
So it works with N=16, but that doesn't explain why the code runs with GPU=1. It the data was too big, shouldn't it fail in both GPU and CUDA = 1?

**Comment by TGower** [comment]
That code snippet works for me, but I was seeing similar errors when I had the wrong Cuda version installed. Are you on Cuda Toolkit 12.3?

**Comment by chenyuxyz** [comment]
likely stale. feel free to reopen if error persists on master
