### ISSUE TITLE
hlb_cifar10 out of memory for RX 7600

### ISSUE THREAD

**Issue by helperfunc** [tinygrad/tinygrad#3117]
```
$ python examples/hlb_cifar10.py
```
output
```
999  193.25 ms run,    6.97 ms python,  186.28 ms CL,  486.66 loss, 0.000086 LR, 4.56 GB used,   3515.05 GFLOPS,    679.28 GOPS
shuffling test dataset in 897.79 ms (0)
Traceback (most recent call last):
  File "/home/hui/tinygrad/examples/hlb_cifar10.py", line 428, in <module>
    train_cifar()
  File "/home/hui/tinygrad/examples/hlb_cifar10.py", line 368, in train_cifar
    correct, loss = eval_step_jitted(model, Xt, Yt)
  File "/home/hui/tinygrad/tinygrad/jit.py", line 114, in __call__
    self.ret = self.fxn(*args, **kwargs)
  File "/home/hui/tinygrad/examples/hlb_cifar10.py", line 336, in eval_step
    return correct.realize(), loss.realize()
  File "/home/hui/tinygrad/tinygrad/tensor.py", line 113, in realize
    run_schedule(self.lazydata.schedule())
  File "/home/hui/tinygrad/tinygrad/realize.py", line 43, in run_schedule
    Buffer(si.out.device, si.out.size, si.out.dtype, "PLACEHOLDER" if isinstance(prg, InterpretedASTRunner) else None)
  File "/home/hui/tinygrad/tinygrad/device.py", line 74, in __init__
    self._buf = opaque if opaque is not None else self.allocator.alloc(dtype if isinstance(dtype, ImageDType) else size * dtype.itemsize)
  File "/home/hui/tinygrad/tinygrad/device.py", line 157, in alloc
    return super().alloc(size)
  File "/home/hui/tinygrad/tinygrad/device.py", line 144, in alloc
    return self._alloc_image(size) if isinstance(size, ImageDType) else self._alloc(size)
  File "/home/hui/tinygrad/tinygrad/runtime/ops_hip.py", line 51, in _alloc
    return init_c_var(hip.hipDeviceptr_t(), lambda x: check(hip.hipMalloc(ctypes.byref(x), size)))
  File "/home/hui/tinygrad/tinygrad/helpers.py", line 192, in init_c_var
    def init_c_var(ctypes_var, creat_cb): return (creat_cb(ctypes_var), ctypes_var)[1]
  File "/home/hui/tinygrad/tinygrad/runtime/ops_hip.py", line 51, in <lambda>
    return init_c_var(hip.hipDeviceptr_t(), lambda x: check(hip.hipMalloc(ctypes.byref(x), size)))
  File "/home/hui/tinygrad/tinygrad/runtime/ops_hip.py", line 15, in check
    if status != 0: raise RuntimeError(f"HIP Error {status}, {ctypes.string_at(hip.hipGetErrorString(status)).decode()}")
RuntimeError: HIP Error 2, out of memory
```

**Comment by g1y5x3** [comment]
have you tried to reduce the batch size? like `BS=128 python examples/hlb_cifar10.py`

**Comment by helperfunc** [comment]
Solved it.
