### ISSUE TITLE
IMAGE=1 and 2: TypeError: 'SumNode' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by okias** [tinygrad/tinygrad#3263]
```shell
$ IMAGE=1 RUSTICL_ENABLE=msm GPU=1 PYTHONPATH="." JIT=0 python examples/gpt2.py --model_size=gpt2 --prompt "Describe a penguin." --count 3 --temperature 0
```

same applies for Intel (iris).

```
using GPU backend
using gpt2
ram used:  0.00 GB, wte.weight                                        :   0%|      | 0/149 [00:00<?, ?it/s]
ram used:  0.50 GB, lm_head.weight                                    : 100%|█| 149/149 [00:00<00:00, 687.8
loaded weights in 220.99 ms, 0.65 GB loaded at 2.95 GB/s
  8%|█████▍                                                                 | 1/13 [00:01<00:13,  1.10s/it]
Traceback (most recent call last):
  File "/home/projects/tinygrad/examples/gpt2.py", line 201, in <module>
    texts = gpt2.generate(args.prompt, args.count, args.temperature, timing=args.timing, batch_size=args.batch_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/projects/tinygrad/examples/gpt2.py", line 167, in generate
    tok = self.model(tokens, Variable("start_pos", 1 if start_pos else 0, MAX_CONTEXT).bind(start_pos), temperature).numpy().tolist()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/projects/tinygrad/examples/gpt2.py", line 115, in __call__
    return forward(tokens, start_pos, temperature)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/projects/tinygrad/examples/gpt2.py", line 97, in forward
    for hi in self.h: h = hi(h, start_pos, mask)
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/projects/tinygrad/examples/gpt2.py", line 68, in __call__
    h = x + self.attn(self.ln_1(x), start_pos, mask).float()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/projects/tinygrad/examples/gpt2.py", line 50, in __call__
    return self.c_proj(xq.scaled_dot_product_attention(keys, values, mask).transpose(1, 2).reshape(bsz, seqlen, self.dim))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/projects/tinygrad/tinygrad/tensor.py", line 914, in scaled_dot_product_attention
    qk = self @ key.transpose(-2,-1) / math.sqrt(self.shape[-1])
         ~~~~~^~~~~~~~~~~~~~~~~~~~~~
  File "/home/projects/tinygrad/tinygrad/tensor.py", line 858, in __matmul__
    def __matmul__(self, x) -> Tensor: return self.matmul(x)
                                              ^^^^^^^^^^^^^^
  File "/home/projects/tinygrad/tinygrad/tensor.py", line 697, in matmul
    return x.dot(self, acc_dtype=acc_dtype) if reverse else self.dot(x, acc_dtype=acc_dtype)
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/projects/tinygrad/tinygrad/features/image.py", line 20, in image_dot
    return image_conv2d(cx, cw, groups=groups, acc_dtype=acc_dtype).reshape(out_shape_t).transpose(self.ndim-1, self.ndim-2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/projects/tinygrad/tinygrad/features/image.py", line 79, in image_conv2d
    ret = ret.reshape(bs, oy, ox, groups, rcout)[:, :, :, :, :-added_output_channels]
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/projects/tinygrad/tinygrad/tensor.py", line 388, in __getitem__
    s, e, st = index.indices(self.shape[dim])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'SumNode' object cannot be interpreted as an integer
```

**Comment by okias** [comment]
Bisected to a753c8e07150bb7dfeb83efc801ea2706316f50e @chenyuxyz

**Comment by chenyuxyz** [comment]
yea IMAGE with symbolic shape is not supported
