### ISSUE TITLE
_posixshmem Module Error: Whisper.py

### ISSUE THREAD

**Issue by 1997MarsRover** [tinygrad/tinygrad#3381]
```yaml
6691aa14d8822fac7d9d27d5dc00b4ca2826dd03/tiny.en.pt: 100%|█████████████████████████████████| 75.6M/75.6M [02:42<00:00, 465kB/s]
ram used:  0.00 GB, encoder.conv1.weight                              :   0%|                                                                                                         | 0/168 [00:00<?, ?it/s]
loaded weights in  10.64 ms, 0.00 GB loaded at 0.00 GB/s
Traceback (most recent call last):
  File "c:\Users\Admin\IdeaProjects\tiny_whisper.py", line 322, in <module>
    model, enc = init_whisper("small.en" if getenv("SMALL") else "tiny.en", batch_size=1)
  File "c:\Users\Admin\IdeaProjects\tiny_whisper.py", line 241, in init_whisper
    load_state_dict(model, state['model_state_dict'], strict=False)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tinygrad\nn\state.py", line 71, in load_state_dict
    v.assign(state_dict[k].shard(mlb.device, mlb.axis) if isinstance((mlb:=v.lazydata), MultiLazyBuffer) else state_dict[k].to(v.device)).realize()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tinygrad\tensor.py", line 130, in realize
    Tensor.corealize([self])
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tinygrad\tensor.py", line 127, in corealize
    run_schedule(create_schedule(flatten([x.lazydata.lbs if isinstance(x.lazydata, MultiLazyBuffer) else [x.lazydata] for x in lst])))
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tinygrad\realize.py", line 67, in run_schedule
    Buffer(si.out.device, si.out.size, si.out.dtype, "PLACEHOLDER" if isinstance(prg, InterpretedASTRunner) else None, options=options)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tinygrad\device.py", line 78, in __init__
    self.device, self.size, self.dtype, self.d, self.options = device, size, dtype, Device[device], options
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tinygrad\device.py", line 24, in __getitem__
    def __getitem__(self, ix:str) -> Union[Interpreted, Compiled]: return self.__get_canonicalized_item(self.canonicalize(ix))
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tinygrad\device.py", line 28, in __get_canonicalized_item   
    return [cls for cname, cls in inspect.getmembers(importlib.import_module(f'tinygrad.runtime.ops_{x.lower()}')) if (cname.lower() == x.lower() + "device") and x in self._devices][0](ix)  # noqa: E501
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tinygrad\runtime\ops_disk.py", line 1, in <module>
    import os, mmap, _posixshmem, io
ModuleNotFoundError: No module named '_posixshmem'
```

**Comment by wozeparrot** [comment]
windows isn't an officially supported platform, but you can use WSL.

**Comment by 1997MarsRover** [comment]
oh ok ,,thanks
