### ISSUE TITLE
IndexError: store out of bounds

### ISSUE THREAD

**Issue by Max-We** [tinygrad/tinygrad#3432]
This issue describes the problem I mentioned in #3384. Various operations that rely on `reduce` operations don't work on my machine for tensors with dimensions that are multiple of `16`. For example:

```
t = Tensor.arange(16).realize()
```

and running it via

```
PYTHON=1 python3 example.py
```

This throws the error, which looks like:

```
Traceback (most recent call last):
  File "test/wth.py", line 3, in <module>
    t = Tensor.arange(16).realize()
  File "/home/mw/Documents/tinygrad/tinygrad/tensor.py", line 116, in realize
    run_schedule(self.lazydata.schedule())
  File "/home/mw/Documents/tinygrad/tinygrad/realize.py", line 68, in run_schedule
    if prg: prg.exec(cast(List[Buffer], real_buffers), si.var_vals)
  File "/home/mw/Documents/tinygrad/tinygrad/device.py", line 47, in exec
    et = self(rawbufs, var_vals)
  File "/home/mw/Documents/tinygrad/tinygrad/device.py", line 308, in __call__
    et = self.clprg(*[x._buf for x in rawbufs], **lra, vals=tuple(var_vals[k] for k in self.vars), wait=wait or DEBUG>=2)
  File "/home/mw/Documents/tinygrad/tinygrad/runtime/ops_python.py", line 78, in __call__
    for m,o,v in zip(*inp): _store(m, o, v)
  File "/home/mw/Documents/tinygrad/tinygrad/runtime/ops_python.py", line 44, in _store
    if i<0 or i>=len(m): raise IndexError(f"store out of bounds, size is {len(m)}, access is {i}, value is {v}")
IndexError: store out of bounds, size is 4, access is 4, value is 0
```

Now, this issue disappears when omitting the `PYTHON=1` flag. The issue also doesn't exist in Colab, so I figure that this problem is platform-dependent. This can only be fixed by changing the logic inside `kernel.py`. For example, by changing the 16 in the following line makes the problem disappear for all tensors with a shape multiple of 16, but of course, the problem will re-appear for the new value you'll enter as a replacement.

```
for sz in (([256, 16]) if prod(self.sts[0].shape[:self.first_reduce]) <= 32 else [16]):
```

Some information about my local setup

- Fedora Linux 39 (Workstation)
- 12th Gen Intel(R) Core(TM) i5-1240P
- Anaconda env. with Python 3.8.18

I don't understand tinygrad well enough so far to be able to solve this here, hence the issue.

**Comment by Max-We** [comment]
Thanks, this was the issue ^^ Didn't sync my fork with master...
