### ISSUE TITLE
examples/gpt2.py doesn't work with GPU=1 on m1

### ISSUE THREAD

**Issue by certik** [tinygrad/tinygrad#3482]
```console
$ GPU=1 python examples/gpt2.py --model_size=gpt2
using GPU backend
using gpt2
ram used:  0.50 GB, lm_head.weight                                    : 100%|█████████████████████████████████████████████████████████████████████████████| 149/149 [00:00<00:00, 1575.12it/s]
loaded weights in 101.92 ms, 0.65 GB loaded at 6.40 GB/s
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:06<00:00, 14.38it/s]
thread '<unnamed>' panicked at src/lib.rs:201:64:
no entry found for key
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/ondrej/repos/tinygrad/examples/gpt2.py", line 201, in <module>
    texts = gpt2.generate(args.prompt, args.count, args.temperature, timing=args.timing, batch_size=args.batch_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ondrej/repos/tinygrad/examples/gpt2.py", line 170, in generate
    return [self.tokenizer.decode(x) for x in toks]
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ondrej/mambaforge/envs/tinygrad/lib/python3.12/site-packages/tiktoken/core.py", line 258, in decode
    return self._core_bpe.decode_bytes(tokens).decode("utf-8", errors=errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: no entry found for key
```

**Comment by fijal** [comment]
The problem is loading uchar from disk using METAL. Trying to debug

**Comment by fijal** [comment]
Specifically, it hits https://github.com/tinygrad/tinygrad/blob/358a24eae634f1b6240579eaf1b96a1416326a3f/tinygrad/runtime/ops_disk.py#L56 with what I believe is not a bitcast (uchar to float)

**Comment by vladov3000** [comment]
Here is a minimal reproduction:
```
from tinygrad import Tensor
from tinygrad.helpers import fetch
from tinygrad.nn.state import torch_load, load_state_dict

import numpy as	np

weights = torch_load(fetch(f'https://huggingface.co/gpt2/resolve/main/pytorch_model.bin'))
weight  = weights["wte.weight"]
tensor  = Tensor.empty(*weight.shape)

tensor.replace(weight.to(tensor.device)).realize()

print(tensor)
print(weight)

print("Nans", np.sum(np.isnan(tensor.numpy())))
```

**Comment by vladov3000** [comment]
Metal takes [this branch](https://github.com/tinygrad/tinygrad/blob/e213bea426d1b40038c04d51fb6f60bf0d127c57/tinygrad/engine/realize.py#L133). OpenCL takes [this branch](https://github.com/tinygrad/tinygrad/blob/e213bea426d1b40038c04d51fb6f60bf0d127c57/tinygrad/engine/realize.py#L135). I have verified that `src.as_buffer` looks good by loading it with `numpy.from_buffer`. So that narrows it down to OpenCL's [copyin](https://github.com/tinygrad/tinygrad/blob/e213bea426d1b40038c04d51fb6f60bf0d127c57/tinygrad/runtime/ops_gpu.py#L72) or [copyout](https://github.com/tinygrad/tinygrad/blob/e213bea426d1b40038c04d51fb6f60bf0d127c57/tinygrad/runtime/ops_gpu.py#L79) being broken. However, the code looks correct.
