### ISSUE TITLE
diskcache table name needs sanitization

### ISSUE THREAD

**Issue by Marandil** [tinygrad/tinygrad#3538]
Example running the "README" example ("Quick example comparing to PyTorch") on current master (b05776ef3e746f9ca17735d55ac4919c27788097), having a Radeon RX 5700XT (gfx1010) connected:

```
(venv) marcin@learning-platform:~/tinygrad$ python3 quick-example.py 
Traceback (most recent call last):
  File "/home/marcin/tinygrad/quick-example.py", line 8, in <module>
    print(x.grad.numpy())  # dz/dx
  File "/home/marcin/tinygrad/tinygrad/tensor.py", line 172, in numpy
    return np.frombuffer(self._data(), dtype=self.dtype.np).reshape(self.shape)
  File "/home/marcin/tinygrad/tinygrad/tensor.py", line 159, in _data
    return cast(Buffer, t.cast(t.dtype.scalar()).contiguous().realize().lazydata.base.realized).as_buffer()
  File "/home/marcin/tinygrad/tinygrad/tensor.py", line 133, in realize
    Tensor.corealize([self])
  File "/home/marcin/tinygrad/tinygrad/tensor.py", line 130, in corealize
    run_schedule(create_schedule(flatten([x.lazydata.lbs if isinstance(x.lazydata, MultiLazyBuffer) else [x.lazydata] for x in lst])))
  File "/home/marcin/tinygrad/tinygrad/realize.py", line 56, in run_schedule
    prg = lower_schedule_item(si)
  File "/home/marcin/tinygrad/tinygrad/realize.py", line 47, in lower_schedule_item
    return Device[si.out.device].get_runner(si.ast)
  File "/home/marcin/tinygrad/tinygrad/device.py", line 273, in get_runner
    def get_runner(self, ast:LazyOp) -> CompiledASTRunner: return self.to_program(self.get_linearizer(ast))
  File "/home/marcin/tinygrad/tinygrad/device.py", line 238, in to_program
    ret = CompiledASTRunner(k.ast, k.name, self.compiler.render(to_function_name(k.name), k.uops), self, k.global_size, k.local_size)
  File "/home/marcin/tinygrad/tinygrad/device.py", line 196, in __init__
    lib:bytes = precompiled if precompiled is not None else self.device.compiler.compile_cached(prg)
  File "/home/marcin/tinygrad/tinygrad/device.py", line 184, in compile_cached
    if self.cachekey is not None: diskcache_put(self.cachekey, src, lib)
  File "/home/marcin/tinygrad/tinygrad/helpers.py", line 159, in diskcache_put
    cur.execute(f"CREATE TABLE IF NOT EXISTS {table}_{VERSION} ({ltypes}, val blob, PRIMARY KEY ({', '.join(key.keys())}))")
sqlite3.OperationalError: near ":xnack": syntax error
```

The error is caused by the following query:
`CREATE TABLE IF NOT EXISTS compile_hip_gfx1010:xnack-_12 (key text, val blob, PRIMARY KEY (key))`,
more precisely the `gfx1010:xnack-` part.

Simple solution: replace all ` {table}_{VERSION} ` with ` '{table}_{VERSION}' ` in helpers.py which seems to work:

```diff
diff --git a/tinygrad/helpers.py b/tinygrad/helpers.py
index 2d0f93fc..d19236de 100644
--- a/tinygrad/helpers.py
+++ b/tinygrad/helpers.py
@@ -141,7 +141,7 @@ def diskcache_get(table:str, key:Union[Dict, str, int]) -> Any:
   conn = db_connection()
   cur = conn.cursor()
   try:
-    res = cur.execute(f"SELECT val FROM {table}_{VERSION} WHERE {' AND '.join([f'{x}=?' for x in key.keys()])}", tuple(key.values()))
+    res = cur.execute(f"SELECT val FROM '{table}_{VERSION}' WHERE {' AND '.join([f'{x}=?' for x in key.keys()])}", tuple(key.values()))
   except sqlite3.OperationalError:
     return None  # table doesn't exist
   if (val:=res.fetchone()) is not None: return pickle.loads(val[0])
@@ -156,9 +156,9 @@ def diskcache_put(table:str, key:Union[Dict, str, int], val:Any):
   if table not in _db_tables:
     TYPES = {str: "text", bool: "integer", int: "integer", float: "numeric", bytes: "blob"}
     ltypes = ', '.join(f"{k} {TYPES[type(key[k])]}" for k in key.keys())
-    cur.execute(f"CREATE TABLE IF NOT EXISTS {table}_{VERSION} ({ltypes}, val blob, PRIMARY KEY ({', '.join(key.keys())}))")
+    cur.execute(f"CREATE TABLE IF NOT EXISTS '{table}_{VERSION}' ({ltypes}, val blob, PRIMARY KEY ({', '.join(key.keys())}))")
     _db_tables.add(table)
-  cur.execute(f"REPLACE INTO {table}_{VERSION} ({', '.join(key.keys())}, val) VALUES ({', '.join(['?']*len(key.keys()))}, ?)", tuple(key.values()) + (pickle.dumps(val), ))  # noqa: E501
+  cur.execute(f"REPLACE INTO '{table}_{VERSION}' ({', '.join(key.keys())}, val) VALUES ({', '.join(['?']*len(key.keys()))}, ?)", tuple(key.values()) + (pickle.dumps(val), ))  # noqa: E501
   conn.commit()
   cur.close()
   return val
```

```
(venv) marcin@learning-platform:~/tinygrad$ python3 quick-example.py 
[[ 2.  2.  2.]
 [ 0.  0.  0.]
 [-2. -2. -2.]]
[[1. 1. 1.]]
```

More complex solution would be to fully sanitize `table` s.t. it doesn't contain unexpected symbols, such as `:`.

**Comment by geohot** [comment]
I'd merge that PR, and if needed, bump the database number.

**Comment by Marandil** [comment]
> I'd merge that PR, and if needed, bump the database number.

Which would you prefer? Simply escaping/quoting table name (as in the diff above) - should not require version change - or some sort of `[a-zA-Z_][a-zA-Z_0-9]*` sanitizer?
