### ISSUE TITLE
AttributeError: module 'tinygrad.runtime.autogen.cuda' has no attribute 'nvrtcCreateProgram'

### ISSUE THREAD

**Issue by argosopentech** [tinygrad/tinygrad#3606]
```
$ python translate.py 
  0%|                                                                                                                | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/argosopentech/tinytranslate/translate.py", line 100, in <module>
    train(model, X_train, Y_train, optim, TRAIN_STEPS, BS=64)
  File "/home/argosopentech/tinygrad/extra/training.py", line 32, in train
    loss, accuracy = train_step(x, y)
  File "/home/argosopentech/tinygrad/tinygrad/features/jit.py", line 133, in __call__
    self.ret = self.fxn(*args, **kwargs)
  File "/home/argosopentech/tinygrad/extra/training.py", line 18, in train_step
    optim.step()
  File "/home/argosopentech/tinygrad/tinygrad/nn/optim.py", line 74, in step
    self.realize([self.t] + self.m + self.v)
  File "/home/argosopentech/tinygrad/tinygrad/nn/optim.py", line 23, in realize
    Tensor.corealize(extra + self.params + self.buffers if extra is not None else self.params + self.buffers)
  File "/home/argosopentech/tinygrad/tinygrad/tensor.py", line 130, in corealize
    run_schedule(create_schedule(flatten([x.lazydata.lbs if isinstance(x.lazydata, MultiLazyBuffer) else [x.lazydata] for x in lst])))
  File "/home/argosopentech/tinygrad/tinygrad/realize.py", line 56, in run_schedule
    prg = lower_schedule_item(si)
  File "/home/argosopentech/tinygrad/tinygrad/realize.py", line 47, in lower_schedule_item
    return Device[si.out.device].get_runner(si.ast)
  File "/home/argosopentech/tinygrad/tinygrad/device.py", line 271, in get_runner
    def get_runner(self, ast:LazyOp) -> CompiledASTRunner: return self.to_program(self.get_linearizer(ast))
  File "/home/argosopentech/tinygrad/tinygrad/device.py", line 241, in to_program
    ret = CompiledASTRunner(k.name, self.compiler.render(to_function_name(k.name), k.uops.uops), self, k.global_size, k.local_size,
  File "/home/argosopentech/tinygrad/tinygrad/device.py", line 199, in __init__
    lib:bytes = precompiled if precompiled is not None else self.device.compiler.compile_cached(prg)
  File "/home/argosopentech/tinygrad/tinygrad/device.py", line 185, in compile_cached
    lib = self.compile(src)
  File "/home/argosopentech/tinygrad/tinygrad/runtime/ops_cuda.py", line 45, in compile
    check(cuda.nvrtcCreateProgram(ctypes.byref(prog := cuda.nvrtcProgram()), src.encode(), "<null>".encode(), 0, None, None))
AttributeError: module 'tinygrad.runtime.autogen.cuda' has no attribute 'nvrtcCreateProgram'

```
```
~/tinytranslate$ nvidia-smi
Mon Mar  4 17:49:33 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3070        On  | 00000000:06:00.0 Off |                  N/A |
| 30%   39C    P8              24W / 220W |      2MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 3070        On  | 00000000:21:00.0 Off |                  N/A |
| 30%   32C    P8              18W / 220W |      2MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

**Comment by flammit** [comment]
Probably need to have libnvrtc in the LD_LIBRARY_PATH... and better error message too.

**Comment by argosopentech** [comment]
> Probably need to have libnvrtc in the LD_LIBRARY_PATH... and better error message too.

Thanks - Installing `nvidia-cuda-dev` seems to fix the issue:
```
sudo apt install nvidia-cuda-dev
```
