### ISSUE TITLE
`Tensor.randn` gives a size mismatch error with `dtypes.bfloat16`

### ISSUE THREAD

**Issue by skoshx** [tinygrad/tinygrad#3653]
Repro:
```python
from tinygrad import Tensor, dtypes

y = Tensor.rand((2, 128, 128), dtype=dtypes.bfloat16)
y.realize().numpy()
```

Error:
```python
Traceback (most recent call last):
  File "/Users/rasmus/Desktop/DEV/AI/tinygrad/repro.py", line 4, in <module>
    y.realize().numpy()
  File "/Users/rasmus/Desktop/DEV/AI/tinygrad/tinygrad/tensor.py", line 135, in realize
    Tensor.corealize([self])
  File "/Users/rasmus/Desktop/DEV/AI/tinygrad/tinygrad/tensor.py", line 132, in corealize
    run_schedule(create_schedule(flatten([x.lazydata.lbs if isinstance(x.lazydata, MultiLazyBuffer) else [x.lazydata] for x in lst])))
  File "/Users/rasmus/Desktop/DEV/AI/tinygrad/tinygrad/realize.py", line 76, in run_schedule
    if prg: prg.exec(cast(List[Buffer], real_buffers), si.var_vals)
  File "/Users/rasmus/Desktop/DEV/AI/tinygrad/tinygrad/device.py", line 49, in exec
    et = self(rawbufs, var_vals)
  File "/Users/rasmus/Desktop/DEV/AI/tinygrad/tinygrad/realize.py", line 19, in __call__
    def __call__(self, rawbufs:List[Buffer], var_vals:Dict[Variable, int], wait=False, jit=False): self.fxn(*rawbufs)
  File "/Users/rasmus/Desktop/DEV/AI/tinygrad/tinygrad/tensor.py", line 1018, in custom_random
    out.copyin(rng_np_buffer.data)
  File "/Users/rasmus/Desktop/DEV/AI/tinygrad/tinygrad/device.py", line 100, in copyin
    assert len(mv) == self.nbytes, f"size mismatch, {len(mv)=} != {self.dtype=} {self.size=}"
AssertionError: size mismatch, len(mv)=262144 != self.dtype=dtypes.bfloat16 self.size=32768
```

**Comment by jermwatt** [comment]
Same issue on Mac M2.  Other dtypes - e.g., float16/32 etc., work fine.
