### ISSUE TITLE
TestDTypeALU.test_float_midcast_int32 failing on 7900XTX HIP

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#3663]
Repro with `PYTHONPATH="." python3 test/test_dtype_alu.py TestDTypeALU.test_float_midcast_int32`

```
======================================================================
FAIL: test_float_midcast_int32 (__main__.TestDTypeALU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tiny/tinygrad/test/test_dtype_alu.py", line 147, in test_float_midcast_int32
    strat.floats(width=32, min_value=0, max_value=10.0) if skip_overflow else ht.float32,
  File "/home/tiny/.local/lib/python3.10/site-packages/hypothesis/core.py", line 1597, in wrapped_test
    raise the_error_hypothesis_found
  File "/home/tiny/tinygrad/test/test_dtype_alu.py", line 149, in test_float_midcast_int32
    def test_float_midcast_int32(self, a, b, c, op1, op2): universal_test_midcast(a, b, c, op1, op2, dtypes.float32, dtypes.int32)
  File "/home/tiny/tinygrad/test/test_dtype_alu.py", line 90, in universal_test_midcast
    np.testing.assert_allclose(tensor_value, numpy_value, rtol=1e-6 if getenv("PTX") else 1e-7)
  File "/home/tiny/.local/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 1504, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/tiny/.local/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 797, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 1 / 1 (100%)
Max absolute difference: 1
Max relative difference: -4.65661287e-10
 x: array([2147483647], dtype=int32)
 y: array([-2147483648], dtype=int32)
Falsifying example: test_float_midcast_int32(
    self=<__main__.TestDTypeALU testMethod=test_float_midcast_int32>,
    a=0.0,
    b=2147483648.0,
    c=0,
    op1=add,
    op2=add,
)
Explanation:
    These lines were always and only run by failing examples:
        /home/tiny/.local/lib/python3.10/site-packages/numpy/core/_ufunc_config.py:120
        /home/tiny/.local/lib/python3.10/site-packages/numpy/core/arrayprint.py:1225
        /home/tiny/.local/lib/python3.10/site-packages/numpy/core/arrayprint.py:1226
        /home/tiny/.local/lib/python3.10/site-packages/numpy/core/arrayprint.py:1476
        /home/tiny/.local/lib/python3.10/site-packages/numpy/core/arrayprint.py:542
        (and 10 more with settings.verbosity >= verbose)

----------------------------------------------------------------------
Ran 1 test in 1.532s

FAILED (failures=1)
```

**Comment by cesar-guibo** [comment]
I was able to reproduce the failure running in my machine with a RTX 4060Ti. Here, the problem is happening because the GPU is making the type conversion with the instruction ```F2I.TRUNC.NTZ R11, R0``` which unlike the instruction CVTTSS2SI used by x86 results in the int 0x7FFFFFFF for overflows. The overflows for x86 result in the integer 0x80000000.

**Comment by jaredeh** [comment]
As stated CUDA fails this in the same way too.  My Rust backend produces reads identical to the C code but enforces different assumptions about overflow than C, which seem to agree with the GPU behavior of truncating to INT_MAX instead of going negative.

When I look at the test I see we're just testing against the numpy behavior here, which in this case is probably just C + CPU ISA defaults passing through rather than an actual numpy default. @chenyuxyz suggests this is probably undefined, which I tend to agree with.

So is this a bad test?  Or do we stick with x86 numpy as the standard?
