### ISSUE TITLE
CUDA float16 conversion not working for coder.py

### ISSUE THREAD

**Issue by vish-pr** [tinygrad/tinygrad#3835]
python3 tinygrad/examples/coder.py                                                                                                                                                      [44/175]
create model: 240.74 ms                                                                                  
https://huggingface.co/teknium/OpenHermes-2.5-Mistral-7B/resolve/main/pytorch_model-00001-of-00002.bin?download=true: 100%|███████████████████████████████████████████████████| 9.94G/9.94G [03:14<00:00, 51.2MB/s]
https://huggingface.co/teknium/OpenHermes-2.5-Mistral-7B/resolve/main/pytorch_model-00002-of-00002.bin?download=true: 100%|███████████████████████████████████████████████████| 4.54G/4.54G [01:34<00:00, 47.8MB/s]
download weights: 310327.98 ms                                                                           
ram used:  0.00 GB, layers.0.attention.wq.weight                      :   0%|                                                                                                              | 0/292 [00:00<?, ?it/s]
loaded weights in 222.70 ms, 0.03 GB loaded at 0.15 GB/s                                                 
weights -> model: 241.17 ms                                                                              
Traceback (most recent call last):                                                                       
  File "/root/tinygrad/examples/coder.py", line 37, in <module>                                          
    nn.state.load_state_dict(model, fix_bf16(convert_from_huggingface(part1, model, 32, 8)), strict=False)                                                                                                         
  File "/root/tinygrad/tinygrad/nn/state.py", line 71, in load_state_dict                                
    v.replace(state_dict[k].shard(mlb.device, mlb.axis) if isinstance((mlb:=v.lazydata), MultiLazyBuffer) else state_dict[k].to(v.device)).realize()                                                               
  File "/root/tinygrad/tinygrad/tensor.py", line 138, in realize                                         
    Tensor.corealize([self])                                                                                                                                                                                       
  File "/root/tinygrad/tinygrad/tensor.py", line 135, in corealize                                                                                                                                                 
    run_schedule(create_schedule(flatten([x.lazydata.lbs if isinstance(x.lazydata, MultiLazyBuffer) else [x.lazydata] for x in lst])))                                                                             
  File "/root/tinygrad/tinygrad/realize.py", line 52, in run_schedule                                    
    prg = lower_schedule_item(si)                                                                        
  File "/root/tinygrad/tinygrad/realize.py", line 31, in lower_schedule_item                             
    if si.ast[0].op is BufferOps.STORE: return Device[si.outputs[0].device].get_runner(*si.ast)                                                                                                                    
  File "/root/tinygrad/tinygrad/device.py", line 284, in get_runner                                      
    def get_runner(self, *ast:LazyOp) -> CompiledASTRunner: return self.to_program(self.get_linearizer(*ast))                                                                                                      
  File "/root/tinygrad/tinygrad/device.py", line 254, in to_program                                                                                                                                                
    ret = CompiledASTRunner(k.name, self.compiler.render(to_function_name(k.name), k.uops), self.dname, k.global_size, k.local_size,                                                                               
  File "/root/tinygrad/tinygrad/device.py", line 205, in __init__                                                                                                                                                  
    lib:bytes = precompiled if precompiled is not None else self.device.compiler.compile_cached(prg)                                                                                                               
  File "/root/tinygrad/tinygrad/device.py", line 191, in compile_cached                                                                                                                                            
    lib = self.compile(src)                                                                              
  File "/root/tinygrad/tinygrad/runtime/ops_cuda.py", line 59, in compile                                
    if status != 0: raise RuntimeError(f"compile failed: {_get_bytes(prog, cuda.nvrtcGetProgramLog, cuda.nvrtcGetProgramLogSize, check).decode()}")                                                                
RuntimeError: compile failed: <null>(21): error: more than one user-defined conversion from "nv_bfloat16" to "half" applies:                                                                                       
            function "__half::__half(float)"                                                             
/usr/local/cuda/include/cuda_fp16.hpp(201): here                                                                                                                                                                   
            function "__half::__half(short)"                                                                                                                                                                       
/usr/local/cuda/include/cuda_fp16.hpp(214): here                                                         
            function "__half::__half(unsigned short)"                                                                                                                                                              
/usr/local/cuda/include/cuda_fp16.hpp(215): here                                                                                                                                                                   
            function "__half::__half(int)"      
/usr/local/cuda/include/cuda_fp16.hpp(216): here                                                                                                                                                                   
            function "__half::__half(unsigned int)"                                                                                                                                                                
/usr/local/cuda/include/cuda_fp16.hpp(217): here                                                         
            function "__half::__half(long long)"                                                         
/usr/local/cuda/include/cuda_fp16.hpp(218): here                                                         
            function "__half::__half(unsigned long long)"                                                
/usr/local/cuda/include/cuda_fp16.hpp(219): here                                                         

<null>(21): error: more than one user-defined conversion from "nv_bfloat16" to "half" applies:
            function "__half::__half(float)"
/usr/local/cuda/include/cuda_fp16.hpp(201): here
            function "__half::__half(short)"
/usr/local/cuda/include/cuda_fp16.hpp(214): here
            function "__half::__half(unsigned short)"
/usr/local/cuda/include/cuda_fp16.hpp(215): here
/usr/local/cuda/include/cuda_fp16.hpp(216): here
            function "__half::__half(unsigned int)"
/usr/local/cuda/include/cuda_fp16.hpp(217): here
            function "__half::__half(long long)"
/usr/local/cuda/include/cuda_fp16.hpp(218): here
            function "__half::__half(unsigned long long)"
/usr/local/cuda/include/cuda_fp16.hpp(219): here

<null>(21): error: more than one user-defined conversion from "nv_bfloat16" to "half" applies:
            function "__half::__half(float)"
/usr/local/cuda/include/cuda_fp16.hpp(201): here
            function "__half::__half(short)"
/usr/local/cuda/include/cuda_fp16.hpp(214): here
            function "__half::__half(unsigned short)"
/usr/local/cuda/include/cuda_fp16.hpp(215): here
            function "__half::__half(int)"
/usr/local/cuda/include/cuda_fp16.hpp(216): here
            function "__half::__half(unsigned int)"
/usr/local/cuda/include/cuda_fp16.hpp(217): here
            function "__half::__half(long long)"
/usr/local/cuda/include/cuda_fp16.hpp(218): here
            function "__half::__half(unsigned long long)"
/usr/local/cuda/include/cuda_fp16.hpp(219): here

<null>(21): error: more than one user-defined conversion from "nv_bfloat16" to "half" applies:
            function "__half::__half(float)"
/usr/local/cuda/include/cuda_fp16.hpp(201): here
            function "__half::__half(short)"
/usr/local/cuda/include/cuda_fp16.hpp(214): here
            function "__half::__half(unsigned short)"
/usr/local/cuda/include/cuda_fp16.hpp(215): here
            function "__half::__half(int)"
/usr/local/cuda/include/cuda_fp16.hpp(216): here
            function "__half::__half(unsigned int)"
/usr/local/cuda/include/cuda_fp16.hpp(217): here
            function "__half::__half(long long)"
/usr/local/cuda/include/cuda_fp16.hpp(218): here
            function "__half::__half(unsigned long long)"
/usr/local/cuda/include/cuda_fp16.hpp(219): here

**Comment by vish-pr** [comment]
CUDA: 12.2 1x RTX A5000
I am just renting gpu on vast.ai, I have tried multiple new instances, simple git clone tingrad, pip install sentencepiece, and run coder.py. Consistently getting same error.

**Comment by ahadrana** [comment]
If you look at the compiled cuda code for the cast from bf16 to "half" or fp16, you will see that it is doing an implicit cast from bf16 to fp16. Looking at <cuda_bf16.h>, it doesn't actually directly support a conversion from bf16 to fp16 (probably for good reason, as it probably has some precision loss somewhere). The llama.py example code in tinygrad is converting the tensors from bf16 to half/fp16 because of this comment .. "without casting to float16, 70B llama OOM on tinybox.". I don't see "fix_bf16" used in that many places, so I am assuming the cast from bf16 to fp16 doesn't have proper coverage across all platforms. It breaks on the LLVM backend for me too. Using an A5000 box, which is 24GB, you probably need that conversion, but I don't know what the most efficient / proper way to do this conversion would in cuda. 

> #define INFINITY (__int_as_float(0x7f800000))
> #define NAN (__int_as_float(0x7fffffff))
> 
> #include <cuda_fp16.h>
> 
> struct half4 {
>     half x, y, z, w;
> };
> 
> __device__ half4 make_half4(half x, half y, half z, half w) {
>     half4 r = {x, y, z, w};
>     return r;
> }
> 
> struct half8 {
>     half x, y, z, w, a, b, c, d;
> };
> 
> __device__ half8 make_half8(half x, half y, half z, half w, half a, half b, half c, half d) {
>     half8 r = {x, y, z, w, a, b, c, d};
>     return r;
> }
> 
> #include <cuda_bf16.h>
> 
> struct bfloat164 {
>     nv_bfloat16 x, y, z, w;
> };
> 
> __device__ bfloat164 make_bfloat164(nv_bfloat16 x, nv_bfloat16 y, nv_bfloat16 z, nv_bfloat16 w) {
>     bfloat164 r = {x, y, z, w};
>     return r;
> }
> 
> struct bfloat168 {
>     nv_bfloat16 x, y, z, w, a, b, c, d;
> };
> 
> __device__ bfloat168 make_bfloat168(nv_bfloat16 x, nv_bfloat16 y, nv_bfloat16 z, nv_bfloat16 w, nv_bfloat16 a, nv_bfloat16 b, nv_bfloat16 c, nv_bfloat16 d) {
>     bfloat168 r = {x, y, z, w, a, b, c, d};
>     return r;
> }
> 
> extern "C" __global__ void E_32768_32_4(half* data0, const nv_bfloat16* data1) {
>     int gidx0 = blockIdx.x; // 32768
>     int lidx1 = threadIdx.x; // 32
>     int alu0 = ((gidx0*128)+(lidx1*4));
> 
>     nv_bfloat16 val0 = data1[alu0];
>     nv_bfloat16 val1 = data1[alu0+1];
>     nv_bfloat16 val2 = data1[alu0+2];
>     nv_bfloat16 val3 = data1[alu0+3];
> 
>     *((half4*)(data0+alu0)) = make_half4((half)(val0), (half)(val1), (half)(val2), (half)(val3));
> }
>

**Comment by chenyuxyz** [comment]
it works in 3090 and 4090, but i can reproduce on A5000.

you can either try `SUPPORT_BF16=0` or change the `fix_bf16` from `v.cast(dtypes.float16)` to `v.float().half()`

**Comment by ahadrana** [comment]
Upon further reading, it is still very strange how the code in fix_bf16 is working on some devices. I believe bf16 to fp16 is not explicitly supported in implicitly even in tinygrad's type promotion lattice. As @chenyuxyz said, you have to upcast to fp32 then to fp16 but then you are potentially getting range truncation.

**Comment by blueridanus** [comment]
Reproduced on an A40 rig.
```sh
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

**Comment by gip** [comment]
Reproduced on an H100

```
git log --pretty=format:'%h' -n 1
942c58be

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
```

**Comment by divinity76** [comment]
can you check if GH-8935 fixes it?

**Comment by chenyuxyz** [comment]
closing as stale, feel free to open new issues
