### ISSUE TITLE
RuntimeError: compile failed: nvrtc: error: invalid value for --gpu-architecture (-arch)

### ISSUE THREAD

**Issue by georgehu0815** [tinygrad/tinygrad#4175]
When run python command as following using WSL on Windows with 4060GPU:

  506  python examples/stable_diffusion.py 
  501  python examples/gpt2.py 

python examples/stable_diffusion.py 
https://github.com/openai/CLIP/raw/main/clip/bpe_simple_vocab_16e6.txt.gz: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.36M/1.36M [00:00<00:00, 12.5MB/s]
https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4.ckpt: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 4.27G/4.27G [02:40<00:00, 26.6MB/s]
ram used:  4.26 GB, cond_stage_model.transformer.text_model.final_layer_norm.bias: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 1131/1131 [00:03<00:00, 311.35it/s]
loaded weights in 3634.93 ms, 4.26 GB loaded at 1.17 GB/s
Traceback (most recent call last):
  File "/mnt/a/tinygrad/examples/stable_diffusion.py", line 609, in <module>
    context = model.cond_stage_model.transformer.text_model(prompt).realize()
  File "/mnt/a/tinygrad/tinygrad/tensor.py", line 144, in realize
    Tensor.corealize([self])
  File "/mnt/a/tinygrad/tinygrad/tensor.py", line 141, in corealize
    run_schedule(*create_schedule_with_vars(flatten([x.lazydata.lbs for x in lst])))
  File "/mnt/a/tinygrad/tinygrad/engine/realize.py", line 45, in run_schedule
    for ei in lower_schedule(schedule):
  File "/mnt/a/tinygrad/tinygrad/engine/realize.py", line 40, in lower_schedule
    while len(schedule): yield ExecItem(lower_schedule_item(si:=schedule.pop(0)), list(si.outputs+si.inputs))
  File "/mnt/a/tinygrad/tinygrad/engine/realize.py", line 28, in lower_schedule_item
    if si.ast[0].op is BufferOps.STORE: return Device[si.outputs[0].device].get_runner(*si.ast)
  File "/mnt/a/tinygrad/tinygrad/device.py", line 262, in get_runner
    method_cache[(self.dname.split(":")[0], ast, True)] = method_cache[(self.dname, ast, False)] = ret = self.to_program(self.get_linearizer(*ast))
  File "/mnt/a/tinygrad/tinygrad/device.py", line 222, in to_program
    ret = CompiledRunner(k.name, self.compiler.render(to_function_name(k.name), k.uops), self.dname, k.global_size, k.local_size,
  File "/mnt/a/tinygrad/tinygrad/device.py", line 167, in __init__
    lib:bytes = precompiled if precompiled is not None else self.device.compiler.compile_cached(prg)
  File "/mnt/a/tinygrad/tinygrad/device.py", line 153, in compile_cached
    lib = self.compile(src)
  File "/mnt/a/tinygrad/tinygrad/runtime/ops_cuda.py", line 79, in compile
    if status != 0: raise RuntimeError(f"compile failed: {_get_bytes(prog, cuda.nvrtcGetProgramLog, cuda.nvrtcGetProgramLogSize, check).decode()}")
RuntimeError: compile failed: nvrtc: error: invalid value for --gpu-architecture (-arch)

**Comment by georgehu0815** [comment]
pip show torch
Name: torch
Version: 2.1.2
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/bochuxt/.local/lib/python3.10/site-packages
Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-nccl-cu12, nvidia-nvtx-cu12, sympy, triton, typing-extensions
Required-by: accelerate, auditnlg, auto-gptq, basicsr, captum, ctgan, deepecho, deepspeed, detoxify, effdet, exllamav2, fairscale, fastai, flexgen, invisible-watermark, kornia, lightning, lightning-flash, linear-operator, llama-recipes, lm-eval, lmflow, medusa-llm, optimum, parlai, peft, pretrainedmodels, promptflow-gui, pystiche, sentence-transformers, SwissArmyTransformer, test-tube, timm, torchaudio, torchvision, trl, vllm, xformers

**Comment by georgehu0815** [comment]
bochuxt@george-nv:/mnt/a/tinygrad$ DEBUG=3 python3 -c "from tinygrad import Tensor;
N = 1024; a, b = Tensor.rand(N, N), Tensor.rand(N, N);
c = (a.reshape(N, 1, N) * b.T.reshape(1, N, N)).sum(axis=2);
print((c.numpy() - (a.numpy() @ b.numpy())).mean())"
opening device METAL from pid:8758
opening device HSA from pid:8758
opening device CUDA from pid:8758
opening device NPY from pid:8758
scheduled 4 kernels
*** CUDA   rand  seed 1713187816 size 1048576         dtype dtypes.float
*** CUDA   rand  seed 1713187817 size 1048576         dtype dtypes.float
  0 ━┳ STORE MemBuffer(idx=0, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(1024, 1024, 1), strides=(1024, 1, 0), offset=0, mask=None, contiguous=True),)))
  1  ┗━┳ SUM ((2,), dtypes.float)
  2    ┗━┳ MUL 
  3      ┣━━ LOAD MemBuffer(idx=1, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(1024, 1024, 1024), strides=(1024, 0, 1), offset=0, mask=None, contiguous=False),)))
  4      ┗━━ LOAD MemBuffer(idx=2, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(1024, 1024, 1024), strides=(0, 1, 1024), offset=0, mask=None, contiguous=False),)))
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/mnt/a/tinygrad/tinygrad/tensor.py", line 194, in numpy
    return np.frombuffer(self._data(), dtype=self.dtype.np).reshape(self.shape)
  File "/mnt/a/tinygrad/tinygrad/tensor.py", line 177, in _data
    cpu = self.cast(self.dtype.scalar()).contiguous().to("CLANG").realize()
  File "/mnt/a/tinygrad/tinygrad/tensor.py", line 144, in realize
    Tensor.corealize([self])
  File "/mnt/a/tinygrad/tinygrad/tensor.py", line 141, in corealize
    run_schedule(*create_schedule_with_vars(flatten([x.lazydata.lbs for x in lst])))
  File "/mnt/a/tinygrad/tinygrad/engine/realize.py", line 45, in run_schedule
    for ei in lower_schedule(schedule):
  File "/mnt/a/tinygrad/tinygrad/engine/realize.py", line 40, in lower_schedule
    while len(schedule): yield ExecItem(lower_schedule_item(si:=schedule.pop(0)), list(si.outputs+si.inputs))
  File "/mnt/a/tinygrad/tinygrad/engine/realize.py", line 28, in lower_schedule_item
    if si.ast[0].op is BufferOps.STORE: return Device[si.outputs[0].device].get_runner(*si.ast)
  File "/mnt/a/tinygrad/tinygrad/device.py", line 262, in get_runner
    method_cache[(self.dname.split(":")[0], ast, True)] = method_cache[(self.dname, ast, False)] = ret = self.to_program(self.get_linearizer(*ast))
  File "/mnt/a/tinygrad/tinygrad/device.py", line 222, in to_program
    ret = CompiledRunner(k.name, self.compiler.render(to_function_name(k.name), k.uops), self.dname, k.global_size, k.local_size,
  File "/mnt/a/tinygrad/tinygrad/device.py", line 167, in __init__
    lib:bytes = precompiled if precompiled is not None else self.device.compiler.compile_cached(prg)
  File "/mnt/a/tinygrad/tinygrad/device.py", line 153, in compile_cached
    lib = self.compile(src)
  File "/mnt/a/tinygrad/tinygrad/runtime/ops_cuda.py", line 79, in compile
    if status != 0: raise RuntimeError(f"compile failed: {_get_bytes(prog, cuda.nvrtcGetProgramLog, cuda.nvrtcGetProgramLogSize, check).decode()}")
RuntimeError: compile failed: nvrtc: error: invalid value for --gpu-architecture (-arch)

**Comment by georgehu0815** [comment]
>>> import torch
>>> torch.__version__
'2.1.2+cu121'

**Comment by georgehu0815** [comment]
feel free to close it now.
