### ISSUE TITLE
Opening devices from child with CUDA & BEAM, when loading from NPY

### ISSUE THREAD

**Issue by PhillCli** [tinygrad/tinygrad#4438]
Hi,

I'm hitting an assert introduced here: https://github.com/tinygrad/tinygrad/pull/4425

example.py that reproduces on a host with CUDA (V100)
```python
import numpy as np
from tqdm import tqdm
import os
from itertools import product
from tinygrad import Tensor, Device, dtypes

device = "CUDA" if os.getenv("CUDA") else "CLANG"
source_dtype = (
    dtypes.float16
    if os.getenv("HALF")
    else dtypes.bfloat16
    if os.getenv("BFLOAT16")
    else dtypes.float32
)

np.savez_compressed("example", z_pq=np.random.rand(50, 50), x_1=np.random.rand(50, 5))

with np.load("example.npz") as data:
    _z_pq = data["z_pq"]
    _x_1 = data["x_1"]
    z_pq = (
        Tensor(_z_pq.astype("float32"), device=device, requires_grad=True)
        .cast(source_dtype)
        .realize()
    )
    x_1 = (
        Tensor(_x_1.astype("float32"), device=device, requires_grad=True)
        .cast(source_dtype)
        .realize()
    )

for p, q in tqdm(product(range(x_1.shape[1]), range(x_1.shape[1])), total=5 ** 2):
    thc = (
        Tensor.einsum(
            "Pp,Pq,PQ,Qr,Qs->pqrs", x_1[:, p : p + 1], x_1[:, q : q + 1], z_pq, x_1, x_1
        )
        .realize()
        .numpy()
    )
```

works fine with
```
CUDA=1 BEAM=0 DEBUG=2 python3 example.py
...
avg:     1.92 GFLOPS     0.07 GB/s           total:    52 kernels     0.01 GOPS     0.00 GB     4.06 ms
```
fails with the below (has to be CTRL-C'ed, otherwise keeps spawning children),
```
CUDA=1 BEAM=1 DEBUG=2 python3 example.py
opening device NPY from pid:8148
opening device CUDA from pid:8148
*** CUDA       1 copy    10000,    CUDA <- NPY          arg   2 mem  0.00 GB tm   1077.89us/     1.08ms (    0.00 GFLOPS,    0.01 GB/s)
*** CUDA       2 copy     1000,    CUDA <- NPY          arg   2 mem  0.00 GB tm    117.75us/     1.20ms (    0.00 GFLOPS,    0.01 GB/s)
  0%|                                                                                                                                                                                       | 0/25 [00:00<?, ?it/s]   0.00s:                 from   1 ->   1 actions    5    5   50   50 
opening device NPY from pid:8167
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/justnex/software/python-vens/conda-04052024-3.12/lib/python3.12/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justnex/software/python-vens/conda-04052024-3.12/lib/python3.12/multiprocessing/spawn.py", line 131, in _main
    prepare(preparation_data)
  File "/home/justnex/software/python-vens/conda-04052024-3.12/lib/python3.12/multiprocessing/spawn.py", line 246, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/justnex/software/python-vens/conda-04052024-3.12/lib/python3.12/multiprocessing/spawn.py", line 297, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 286, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/home/justnex/src/tinygrad/example.py", line 16, in <module>
    z_pq = Tensor(_z_pq.astype("float32"), device=device,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justnex/src/tinygrad/tinygrad/tensor.py", line 120, in __init__
    else: data = _fromcpu(data.astype(dtype.np) if dtype is not None and dtype.np is not None else data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justnex/src/tinygrad/tinygrad/tensor.py", line 50, in _fromcpu
    ret.buffer.allocate(x)
  File "/home/justnex/src/tinygrad/tinygrad/buffer.py", line 43, in allocate
    self.allocator = Device[self.device].allocator
                     ~~~~~~^^^^^^^^^^^^^
  File "/home/justnex/src/tinygrad/tinygrad/device.py", line 24, in __getitem__
    def __getitem__(self, ix:str) -> Compiled: return self.__get_canonicalized_item(self.canonicalize(ix))
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justnex/src/tinygrad/tinygrad/device.py", line 28, in __get_canonicalized_item
    assert multiprocessing.current_process().name == "MainProcess" or ix.split(":")[0] == "DISK", f"can only open device {ix} from parent"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only open device NPY from parent

```

I would like to be able to use BEAM search for the best kernels, and for the time being, I need to load data from disk, that is dumped in `.npy/npz`. Is there some way around?

Thanks!

**Comment by PhillCli** [comment]
@wozeparrot It did remove "can only open `NPY` from the parent", but seems that's only a symptom, and not solution to the problem.

After that merged I'm getting a similar issue but with a CUDA device.

Here's a refined reproduction, without any pesky `.npz`, plain NPY, and CUDA.

```python
import numpy as np
import os
from tinygrad import Tensor, Device, dtypes

device = "CUDA" if os.getenv("CUDA") else "CLANG"
source_dtype = dtypes.float16 if os.getenv("HALF") else dtypes.bfloat16 if os.getenv("BFLOAT16") else dtypes.float32

__z_pq = np.random.rand(50, 50)
__x_1 = np.random.rand(50, 5)

z_pq = Tensor(__z_pq, device=device).cast(source_dtype).realize()
x_1 = Tensor(__x_1, device=device).cast(source_dtype).realize()

z_pq.matmul(x_1).realize()
```
failure
```log
CUDA=1 BEAM=1 BEAM_DEBUG=1 DEBUG=5 python3 example.py 
opening device NPY from pid:61338
opening device CUDA from pid:61338
*** CUDA       1 copy    20000,    CUDA <- NPY          arg   2 mem  0.00 GB tm   1175.24us/     1.18ms (    0.00 GFLOPS,    0.02 GB/s)
  0 ━┳ STORE MemBuffer(idx=0, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(50, 50), strides=(50, 1), offset=0, mask=None, contiguous=True),)))
  1  ┗━┳ CAST (dtypes.float, False)
  2    ┗━━ LOAD MemBuffer(idx=1, dtype=dtypes.double, st=ShapeTracker(views=(View(shape=(50, 50), strides=(50, 1), offset=0, mask=None, contiguous=True),)))
BEAM_SEARCH:
(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=UnaryOps.CAST, src=(LazyOp(op=BufferOps.LOAD, src=(), arg=MemBuffer(idx=1, dtype=dtypes.double, st=ShapeTracker(views=(View(shape=(50, 50), strides=(50, 1), offset=0, mask=None, contiguous=True),)))),), arg=(dtypes.float, False)),), arg=MemBuffer(idx=0, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(50, 50), strides=(50, 1), offset=0, mask=None, contiguous=True),)))),)
   0.00s:                 from   1 ->   1 actions 2500
opening device NPY from pid:61377
opening device CUDA from pid:61377
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/justnex/software/python-vens/conda-04052024-3.12/lib/python3.12/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justnex/software/python-vens/conda-04052024-3.12/lib/python3.12/multiprocessing/spawn.py", line 131, in _main
    prepare(preparation_data)
  File "/home/justnex/software/python-vens/conda-04052024-3.12/lib/python3.12/multiprocessing/spawn.py", line 246, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/justnex/software/python-vens/conda-04052024-3.12/lib/python3.12/multiprocessing/spawn.py", line 297, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 286, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/home/justnex/src/tinygrad/example.py", line 11, in <module>
    z_pq = Tensor(__z_pq, device=device).cast(source_dtype).realize()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justnex/src/tinygrad/tinygrad/tensor.py", line 166, in realize
    run_schedule(*self.schedule_with_vars(*lst))
  File "/home/justnex/src/tinygrad/tinygrad/engine/realize.py", line 108, in run_schedule
    for ei in lower_schedule(schedule):
  File "/home/justnex/src/tinygrad/tinygrad/engine/realize.py", line 66, in lower_schedule
    while len(schedule): yield lower_schedule_item(schedule.pop(0))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justnex/src/tinygrad/tinygrad/engine/realize.py", line 56, in lower_schedule_item
    if hasattr(Device[out.device].allocator, 'transfer') and out.device.split(":")[0] == si.inputs[0].device.split(":")[0]:
               ~~~~~~^^^^^^^^^^^^
  File "/home/justnex/src/tinygrad/tinygrad/device.py", line 24, in __getitem__
    def __getitem__(self, ix:str) -> Compiled: return self.__get_canonicalized_item(self.canonicalize(ix))
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justnex/src/tinygrad/tinygrad/device.py", line 28, in __get_canonicalized_item
    assert multiprocessing.current_process().name == "MainProcess" or ix.split(":")[0] in ["DISK", "NPY"], f"can only open device {ix} from parent"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: can only open device CUDA from parent
opening device NPY from pid:61355
opening device CUDA from pid:61355

```

I would like to re-open, if possible.

**Comment by wozeparrot** [comment]
Do you have a full script for this, the example snippet that you posted I cannot reproduce.

**Comment by PhillCli** [comment]
>Do you have a full script for this, the example snippet that you posted I cannot reproduce.

Sorry for the delay, @wozeparrot, I've figured it out.

The issue arises when tensor declaration blocks are not guarded by
```
if __name__ == "__main__":
```
then the child tries to re-open the device, when it initializes the module, as tensor initialization was 'global'. With `__name__ == "__main__"` it skips initialization, and only invokes `_compile_fn` from `imap_unorder` in `search.py`.


The below code works:
```python
import numpy as np
from tinygrad.helpers import getenv
from tinygrad import dtypes, Tensor

dtype_in = dtypes.half if getenv("HALF") else dtypes.bfloat16 if getenv("BFLOAT16") else dtypes.float
acc_dtype = dtypes.half if getenv("ACC_HALF") else dtypes.bfloat16 if getenv("ACC_BFLOAT16") else None

if __name__ == "__main__":
  __z_pq = np.random.rand(50, 50) 
  __x_1 = np.random.rand(50, 5)

  z_pq = Tensor(__z_pq, device="CUDA").cast(dtype_in).realize()
  x_1 = Tensor(__x_1, device="CUDA").cast(dtype_in).realize()

  z_pq.matmul(x_1, acc_dtype=acc_dtype).realize()
```

Pretty Noob issue, not sure if you want to have that in docs somewhere, might save someone from running into it.
