### ISSUE TITLE
Recursive rewrite looped on LLaMA BEAM

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#4810]
`DEBUG=2 BEAM=4 NV=1 python3 examples/llama.py --prompt "Hello." --count 20 --shard 6 --timing`

```
*** NV:5    13598 r_125_16_16_8_32                       arg   2 mem 26.39 GB tm      4.45us/   507.13ms ( 1841.73 GFLOPS,   57.55 GB/s)
   0.00s:                 from   1 ->   1 actions  125  125
   0.05s:         2.85 us from   4 ->   4 actions  125  125
   0.18s:         2.69 us from  26 ->  21 actions  125   16    8
   0.47s:         2.66 us from  34 ->  33 actions  125   16    8
   0.92s:         2.59 us from  32 ->  30 actions   32    4   16    8
   1.56s:         2.56 us from  59 ->  51 actions   32    2    2   16    8
   2.29s:         2.53 us from  57 ->  51 actions   32    2    2   16    8
   2.47s:         2.62 us         17/  45           32    2   16    2    4    2enqueue in 100915.26 ms, 507.13 ms on GPU, 41.14 GOPS, 28.80 GB, 56.78 GB/s, param 26.60 GB/s
total 100915.30 ms, 0.01 tok/s, 0.29 GB/s, param 0.13 GB/s
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/tiny/tinygrad/tinygrad/engine/search.py", line 62, in _try_compile_linearized_w_idx
    if len(x[1].uops.uops) >= getenv("BEAM_UOPS_MAX", 3000) > 0: raise RuntimeError("too many uops")
  File "/home/tiny/tinygrad/tinygrad/codegen/uops.py", line 263, in uops
    if self._uops is None: self.linearize()
  File "/home/tiny/tinygrad/tinygrad/codegen/uops.py", line 316, in linearize
    sink = self.graph_rewrite(sink, constant_folder)
  File "/home/tiny/tinygrad/tinygrad/codegen/uops.py", line 299, in graph_rewrite
    sink = rewrite(sink)
  File "/home/tiny/tinygrad/tinygrad/codegen/uops.py", line 292, in rewrite
    up.vin = tuple(rewrite(x) for x in up.vin)
  File "/home/tiny/tinygrad/tinygrad/codegen/uops.py", line 292, in <genexpr>
    up.vin = tuple(rewrite(x) for x in up.vin)
  File "/home/tiny/tinygrad/tinygrad/codegen/uops.py", line 292, in rewrite
    up.vin = tuple(rewrite(x) for x in up.vin)
  File "/home/tiny/tinygrad/tinygrad/codegen/uops.py", line 292, in <genexpr>
    up.vin = tuple(rewrite(x) for x in up.vin)
  File "/home/tiny/tinygrad/tinygrad/codegen/uops.py", line 287, in rewrite
    assert recurse_cnt < 100, f"recursive_rewrite looped {up} <--> {rewritten}"
AssertionError: recursive_rewrite looped UOps.ALU            : dtypes.float              [<UOps.CONST: 6>, <UOps.ALU: 13>] BinaryOps.ADD <--> UOps.ALU            : dtypes.float              [<UOps.CONST: 6>, <UOps.ALU: 13>] BinaryOps.ADD
"""
```

**Comment by chenyuxyz** [comment]
could not find the commit that reproduces this (going from master and -100 commits until early May)

**Comment by chenyuxyz** [comment]
open a new issue with commit hash if this happens again
