### ISSUE TITLE
Error with AMD and installing Tinygrad from Local

### ISSUE THREAD

**Issue by Hprairie** [tinygrad/tinygrad#5373]
Previously I was getting segmentation faults with my environment when I was trying to use tinygrad on a 7900 XTX with a local install. This was using the HSA ops, which have now been removed and replaced with AMD. I tried installing Tinygrad locally and am now getting a new issue. Here is the entire stack trace.

```bash
(tiny) prairie@TRX40:~/Projects/tinygrad$ DEBUG=3 python3 -c "from tinygrad import Tensor;
N = 1024; a, b = Tensor.rand(N, N), Tensor.rand(N, N);
c = (a.reshape(N, 1, N) * b.T.reshape(1, N, N)).sum(axis=2);
print((c.numpy() - (a.numpy() @ b.numpy())).mean())"
opened device AMD from pid:19617
opened device NPY from pid:19617
*** CUSTOM     1 custom_random                          arg   1 mem  0.00 GB 
*** CUSTOM     2 custom_random                          arg   1 mem  0.01 GB 
  0 ━┳ BufferOps.STORE MemBuffer(idx=0, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(1024, 1024, 1), strides=(1024, 1, 0), offset=0, mask=None, contiguous=True),)))
  1  ┗━┳ ReduceOps.SUM (2,)
  2    ┗━┳ BinaryOps.MUL None
  3      ┣━━ BufferOps.LOAD MemBuffer(idx=1, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(1024, 1024, 1024), strides=(1024, 0, 1), offset=0, mask=None, contiguous=False),)))
  4      ┗━━ BufferOps.LOAD MemBuffer(idx=2, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(1024, 1024, 1024), strides=(0, 1, 1024), offset=0, mask=None, contiguous=False),)))
error lowering BufferOps.STORE
tensor operations:
[__mul__ - __main__:3::<module>, sum - __main__:3::<module>]
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/home/prairie/Projects/tinygrad/tinygrad/tensor.py", line 3122, in _wrapper
    ret = fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/prairie/Projects/tinygrad/tinygrad/tensor.py", line 300, in numpy
    return np.frombuffer(self._data(), dtype=_to_np_dtype(self.dtype)).reshape(self.shape)
                         ^^^^^^^^^^^^
  File "/home/prairie/Projects/tinygrad/tinygrad/tensor.py", line 3101, in _wrapper
    if _METADATA.get() is not None: return fn(*args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^
  File "/home/prairie/Projects/tinygrad/tinygrad/tensor.py", line 244, in _data
    cpu = self.cast(self.dtype.scalar()).contiguous().to("CLANG").realize()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prairie/Projects/tinygrad/tinygrad/tensor.py", line 3101, in _wrapper
    if _METADATA.get() is not None: return fn(*args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^
  File "/home/prairie/Projects/tinygrad/tinygrad/tensor.py", line 203, in realize
    run_schedule(*self.schedule_with_vars(*lst), do_update_stats=do_update_stats)
  File "/home/prairie/Projects/tinygrad/tinygrad/engine/realize.py", line 200, in run_schedule
    for ei in lower_schedule(schedule):
  File "/home/prairie/Projects/tinygrad/tinygrad/engine/realize.py", line 193, in lower_schedule
    raise e
  File "/home/prairie/Projects/tinygrad/tinygrad/engine/realize.py", line 187, in lower_schedule
    try: yield lower_schedule_item(si)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prairie/Projects/tinygrad/tinygrad/engine/realize.py", line 171, in lower_schedule_item
    runner = get_runner(si.outputs[0].device, si.ast)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prairie/Projects/tinygrad/tinygrad/engine/realize.py", line 142, in get_runner
    method_cache[ckey] = method_cache[bkey] = ret = CompiledRunner(replace(prg, dname=dname))
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prairie/Projects/tinygrad/tinygrad/engine/realize.py", line 61, in __init__
    self.clprg = Device[p.dname].runtime(p.function_name, self.lib)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prairie/Projects/tinygrad/tinygrad/runtime/ops_amd.py", line 321, in __init__
    self.lib_gpu = self.device._gpu_alloc(lib_gpu_size, kfd.KFD_IOC_ALLOC_MEM_FLAGS_VRAM, public=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prairie/Projects/tinygrad/tinygrad/runtime/ops_amd.py", line 436, in _gpu_alloc
    mem = kio.alloc_memory_of_gpu(self.kfd, va_addr=addr, size=size, base=addr, length=size, gpu_id=self.gpu_id, flags=flags, mmap_offset=buf)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prairie/Projects/tinygrad/tinygrad/runtime/ops_amd.py", line 25, in kfd_ioctl
    ret = fcntl.ioctl(fd, (idir<<30) | (ctypes.sizeof(made)<<16) | (ord('K')<<8) | nr, made)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
```

Here is some of my system information. 

```bash
(tiny) prairie@TRX40:~/Projects/tinygrad$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

And here is `rocminfo`

```bash
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.13
Runtime Ext Version:     1.4
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
DMAbuf Support:          YES

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD Ryzen Threadripper 3970X 32-Core Processor
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD Ryzen Threadripper 3970X 32-Core Processor
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   3700                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            64                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    49155056(0x2ee0bf0) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    49155056(0x2ee0bf0) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    49155056(0x2ee0bf0) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    gfx1100                            
  Uuid:                    GPU-50b29228c5e4eb8b               
  Marketing Name:          Radeon RX 7900 XTX                 
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      32(0x20) KB                        
    L2:                      6144(0x1800) KB                    
    L3:                      98304(0x18000) KB                  
  Chip ID:                 29772(0x744c)                      
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   2304                               
  BDFID:                   8960                               
  Internal Node ID:        1                                  
  Compute Unit:            96                                 
  SIMDs per CU:            2                                  
  Shader Engines:          6                                  
  Shader Arrs. per Eng.:   2                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          32(0x20)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    1024(0x400)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 92                                 
  SDMA engine uCode::      20                                 
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    25149440(0x17fc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    25149440(0x17fc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1100         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done ***    
```

Let me know if there is anything else that I can help with.

**Comment by wozeparrot** [comment]
what's your rocm version? for some reason rocminfo doesn't include it

**Comment by Hprairie** [comment]
Yeah sure, here is the specs from amdgpu-install.

```bash
linux-headers-6.5.0-41-generic is already the newest version (6.5.0-41.41~22.04.2).
linux-headers-6.5.0-41-generic set to manually installed.
amdgpu-dkms is already the newest version (1:6.7.0.60100-1756574.22.04).
amdgpu-lib is already the newest version (1:6.1.60100-1756574.22.04).
amdgpu-lib32 is already the newest version (1:6.1.60100-1756574.22.04).
rocm-hip-runtime is already the newest version (6.1.0.60100-82~22.04).
rocm-opencl-runtime is already the newest version (6.1.0.60100-82~22.04).
```

**Comment by nimlgen** [comment]
Hmm, the failing allocation isn't the first one. Are you running this under any VM or something?

**Comment by Hprairie** [comment]
Nope I'm just on native Linux.

**Comment by Notnaton** [comment]
it crashes on my computer too
```
anton@desktop:~$ DEBUG=4 python3 -c "from tinygrad import Tensor;
N = 1024; a, b = Tensor.rand(N, N), Tensor.rand(N, N);
c = (a.reshape(N, 1, N) * b.T.reshape(1, N, N)).sum(axis=2);
print((c.numpy() - (a.numpy() @ b.numpy())).mean())"
opened device AMD from pid:259470
opened device NPY from pid:259470
*** CUSTOM     1 custom_random                          arg   1 mem  0.00 GB 
*** CUSTOM     2 custom_random                          arg   1 mem  0.01 GB 
float4 merging axis : [(3, 3, 1, 4), (4, 4096, 0, 4)]
float4 merging axis : [(4, 4096, 0, 4)]
r_32_16_8_16_256_4_4_4
  0 ━┳ BufferOps.STORE MemBuffer(idx=0, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(32, 16, 8, 16, 1, 4, 4, 1), strides=(32768, 64, 4096, 4, 0, 1, 1024, 0), offset=0, mask=None, contiguous=False),)))
  1  ┗━┳ ReduceOps.SUM (4, 7)
  2    ┗━┳ BinaryOps.MUL None
  3      ┣━━ BufferOps.LOAD MemBuffer(idx=1, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(32, 16, 8, 16, 256, 4, 4, 4), strides=(32768, 0, 4096, 0, 4, 0, 1024, 1), offset=0, mask=None, contiguous=False),)))
  4      ┗━━ BufferOps.LOAD MemBuffer(idx=2, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(32, 16, 8, 16, 256, 4, 4, 4), strides=(0, 64, 0, 4, 4096, 1, 0, 1024), offset=0, mask=None, contiguous=False),)))
#define INFINITY (__builtin_inff())
#define NAN (__builtin_nanf(""))
typedef long unsigned int size_t;
typedef float float2 __attribute__((ext_vector_type(2)));
static inline __attribute__((device)) float2 make_float2(float x, float y) { return {x, y}; }
typedef float float4 __attribute__((ext_vector_type(4)));
static inline __attribute__((device)) float4 make_float4(float x, float y, float z, float w) { return {x, y, z, w}; }
typedef float float8 __attribute__((ext_vector_type(8)));
static inline __attribute__((device)) float8 make_float8(float x, float y, float z, float w, float a, float b, float c, float d) { return {x, y, z, w, a, b, c, d}; }
typedef signed int int4 __attribute__((ext_vector_type(4)));
static inline __attribute__((device)) int4 make_int4(signed int x, signed int y, signed int z, signed int w) { return {x, y, z, w}; }
typedef signed int int2 __attribute__((ext_vector_type(2)));
static inline __attribute__((device)) int2 make_int2(signed int x, signed int y) { return {x, y}; }
extern "C" __attribute__((device)) __attribute__((const)) size_t __ockl_get_local_id(unsigned int);
extern "C" __attribute__((device)) __attribute__((const)) size_t __ockl_get_group_id(unsigned int);
extern "C" __attribute__((device)) __attribute__((const)) size_t __ockl_get_local_size(unsigned int);
extern "C" {
  __attribute__((device)) __attribute__((const)) float __ocml_fmax_f32(float, float);
  __attribute__((device)) __attribute__((pure)) float __ocml_exp2_f32(float);
  __attribute__((device)) __attribute__((pure)) float __ocml_log2_f32(float);
  __attribute__((device)) __attribute__((const)) float __ocml_sqrt_f32(float);
  __attribute__((device)) float __ocml_sin_f32(float);
  __attribute__((device)) __attribute__((const)) double __ocml_fmax_f64(double, double);
  __attribute__((device)) __attribute__((pure)) double __ocml_exp2_f64(double);
  __attribute__((device)) __attribute__((pure)) double __ocml_log2_f64(double);
  __attribute__((device)) __attribute__((const)) double __ocml_sqrt_f64(double);
  __attribute__((device)) double __ocml_sin_f64(double);
  __attribute__((device)) __attribute__((const)) _Float16 __ocml_fmax_f16(_Float16, _Float16);
  __attribute__((device)) __attribute__((pure)) _Float16 __ocml_exp2_f16(_Float16);
  __attribute__((device)) __attribute__((pure)) _Float16 __ocml_log2_f16(_Float16);
  __attribute__((device)) __attribute__((const)) _Float16 __ocml_sqrt_f16(_Float16);
  __attribute__((device)) _Float16 __ocml_sin_f16(_Float16);
}
extern "C" __attribute__((global))void __attribute__((amdgpu_flat_work_group_size(1, 128)))r_32_16_8_16_256_4_4_4(float* data0, const float* data1, const float* data2) {
  int gidx0 = __ockl_get_group_id(0); /* 32 */
  int lidx2 = __ockl_get_local_id(0); /* 8 */
  int gidx1 = __ockl_get_group_id(1); /* 16 */
  int lidx3 = __ockl_get_local_id(1); /* 16 */
  int alu0 = (gidx0*32768);
  int alu1 = (lidx2*4096);
  int alu2 = (gidx1*64);
  int alu3 = (lidx3*4);
  int alu4 = (alu0+alu2+alu1+alu3);
  float4 acc0 = make_float4(0.0f,0.0f,0.0f,0.0f);
  float4 acc1 = make_float4(0.0f,0.0f,0.0f,0.0f);
  float4 acc2 = make_float4(0.0f,0.0f,0.0f,0.0f);
  float4 acc3 = make_float4(0.0f,0.0f,0.0f,0.0f);
  for (int ridx0 = 0; ridx0 < 256; ridx0++) {
    int alu5 = (alu0+alu1+(ridx0*4));
    int alu6 = (alu2+alu3+(ridx0*4096));
    float4 val0 = *((float4*)(data1+alu5+1024));
    float4 val1 = *((float4*)(data1+alu5+2048));
    float4 val2 = *((float4*)(data1+alu5+3072));
    float4 val3 = *((float4*)(data1+alu5));
    float4 val4 = *((float4*)(data2+alu6+1024));
    float4 val5 = *((float4*)(data2+alu6+2048));
    float4 val6 = *((float4*)(data2+alu6+3072));
    float4 val7 = *((float4*)(data2+alu6));
    acc0 = make_float4((acc0.x+(val3.x*val7.x)+(val3.y*val4.x)+(val3.z*val5.x)+(val3.w*val6.x)),(acc0.y+(val3.x*val7.y)+(val3.y*val4.y)+(val3.z*val5.y)+(val3.w*val6.y)),(acc0.z+(val3.x*val7.z)+(val3.y*val4.z)+(val3.z*val5.z)+(val3.w*val6.z)),(acc0.w+(val3.x*val7.w)+(val3.y*val4.w)+(val3.z*val5.w)+(val3.w*val6.w)));
    acc1 = make_float4((acc1.x+(val0.x*val7.x)+(val0.y*val4.x)+(val0.z*val5.x)+(val0.w*val6.x)),(acc1.y+(val0.x*val7.y)+(val0.y*val4.y)+(val0.z*val5.y)+(val0.w*val6.y)),(acc1.z+(val0.x*val7.z)+(val0.y*val4.z)+(val0.z*val5.z)+(val0.w*val6.z)),(acc1.w+(val0.x*val7.w)+(val0.y*val4.w)+(val0.z*val5.w)+(val0.w*val6.w)));
    acc2 = make_float4((acc2.x+(val1.x*val7.x)+(val1.y*val4.x)+(val1.z*val5.x)+(val1.w*val6.x)),(acc2.y+(val1.x*val7.y)+(val1.y*val4.y)+(val1.z*val5.y)+(val1.w*val6.y)),(acc2.z+(val1.x*val7.z)+(val1.y*val4.z)+(val1.z*val5.z)+(val1.w*val6.z)),(acc2.w+(val1.x*val7.w)+(val1.y*val4.w)+(val1.z*val5.w)+(val1.w*val6.w)));
    acc3 = make_float4((acc3.x+(val2.x*val7.x)+(val2.y*val4.x)+(val2.z*val5.x)+(val2.w*val6.x)),(acc3.y+(val2.x*val7.y)+(val2.y*val4.y)+(val2.z*val5.y)+(val2.w*val6.y)),(acc3.z+(val2.x*val7.z)+(val2.y*val4.z)+(val2.z*val5.z)+(val2.w*val6.z)),(acc3.w+(val2.x*val7.w)+(val2.y*val4.w)+(val2.z*val5.w)+(val2.w*val6.w)));
  }
  *((float4*)(data0+1024+alu4)) = acc1;
  *((float4*)(data0+2048+alu4)) = acc2;
  *((float4*)(data0+3072+alu4)) = acc3;
  *((float4*)(data0+alu4)) = acc0;
}
error lowering BufferOps.STORE
tensor operations:
[__mul__ - __main__:3::<module>, sum - __main__:3::<module>]
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/home/anton/.local/lib/python3.10/site-packages/tinygrad/tensor.py", line 3122, in _wrapper
    ret = fn(*args, **kwargs)
  File "/home/anton/.local/lib/python3.10/site-packages/tinygrad/tensor.py", line 300, in numpy
    return np.frombuffer(self._data(), dtype=_to_np_dtype(self.dtype)).reshape(self.shape)
  File "/home/anton/.local/lib/python3.10/site-packages/tinygrad/tensor.py", line 3101, in _wrapper
    if _METADATA.get() is not None: return fn(*args, **kwargs)
  File "/home/anton/.local/lib/python3.10/site-packages/tinygrad/tensor.py", line 244, in _data
    cpu = self.cast(self.dtype.scalar()).contiguous().to("CLANG").realize()
  File "/home/anton/.local/lib/python3.10/site-packages/tinygrad/tensor.py", line 3101, in _wrapper
    if _METADATA.get() is not None: return fn(*args, **kwargs)
  File "/home/anton/.local/lib/python3.10/site-packages/tinygrad/tensor.py", line 203, in realize
    run_schedule(*self.schedule_with_vars(*lst), do_update_stats=do_update_stats)
  File "/home/anton/.local/lib/python3.10/site-packages/tinygrad/engine/realize.py", line 200, in run_schedule
    for ei in lower_schedule(schedule):
  File "/home/anton/.local/lib/python3.10/site-packages/tinygrad/engine/realize.py", line 193, in lower_schedule
    raise e
  File "/home/anton/.local/lib/python3.10/site-packages/tinygrad/engine/realize.py", line 187, in lower_schedule
    try: yield lower_schedule_item(si)
  File "/home/anton/.local/lib/python3.10/site-packages/tinygrad/engine/realize.py", line 171, in lower_schedule_item
    runner = get_runner(si.outputs[0].device, si.ast)
  File "/home/anton/.local/lib/python3.10/site-packages/tinygrad/engine/realize.py", line 142, in get_runner
    method_cache[ckey] = method_cache[bkey] = ret = CompiledRunner(replace(prg, dname=dname))
  File "/home/anton/.local/lib/python3.10/site-packages/tinygrad/engine/realize.py", line 61, in __init__
    self.clprg = Device[p.dname].runtime(p.function_name, self.lib)
  File "/home/anton/.local/lib/python3.10/site-packages/tinygrad/runtime/ops_amd.py", line 286, in __init__
    self.lib_gpu = self.device._gpu_alloc(lib_gpu_size, kfd.KFD_IOC_ALLOC_MEM_FLAGS_VRAM, public=True)
  File "/home/anton/.local/lib/python3.10/site-packages/tinygrad/runtime/ops_amd.py", line 401, in _gpu_alloc
    mem = kio.alloc_memory_of_gpu(self.kfd, va_addr=addr, size=size, base=addr, length=size, gpu_id=self.gpu_id, flags=flags, mmap_offset=buf)
  File "/home/anton/.local/lib/python3.10/site-packages/tinygrad/runtime/ops_amd.py", line 26, in kfd_ioctl
    ret = fcntl.ioctl(fd, (idir<<30) | (ctypes.sizeof(made)<<16) | (ord('K')<<8) | nr, made)
OSError: [Errno 22] Invalid argument
```

**Comment by Notnaton** [comment]
Enabling "Above 4G Decoding" or "Resizable BAR" in BIOS fixed this issue for me

**Comment by nimlgen** [comment]
@Hprairie did "Resizable BAR" fix the problem for you?

**Comment by Hprairie** [comment]
Sorry for the slow response, and yes this fixed it!
