### ISSUE TITLE
 Neural Networks documentation examples fail

### ISSUE THREAD

**Issue by Benetti-Hub** [tinygrad/tinygrad#5496]
The documentation on https://docs.tinygrad.org/nn/ currently fails to generate the output for the examples, instead, it gives the following errors:

```python
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/markdown_exec/formatters/python.py", line 71, in _run_python
    exec_python(code, code_block_id, exec_globals)
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/markdown_exec/formatters/_exec_python.py", line 8, in exec_python
    exec(compiled, exec_globals)  # noqa: S102
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<code block: session tensor; n1>", line 1, in <module>
    conv = nn.Conv1d(1, 1, 3)
            ^^
NameError: name 'nn' is not defined
```

This is due to the fact that [`nn.md`](https://github.com/tinygrad/tinygrad/blob/master/docs/nn.md?plain=1#L3) uses `BatchNorm2d` instead of `BatchNorm` (changing it from tinygrad.nn.BatchNorm2d to tinygrad.nn.BatchNorm fixes the issue).

Additionally, adding `mkdocs build --strict` in https://github.com/tinygrad/tinygrad/blob/master/.github/workflows/docs.yml would ensure that these kinds of errors are reflected in the outcome of the github action.

**Comment by geohot** [comment]
Fixed, would merge PR to add strict and catch these errors

**Comment by Benetti-Hub** [comment]
Thank you! PR added
