### ISSUE TITLE
Apple M1 Max cannot load llama3-8b-sfr weights (because no bfloat support?)

### ISSUE THREAD

**Issue by mcale6** [tinygrad/tinygrad#5549]
Mac OS, Metal, M1 MAX Macbook Pro, Python 3.11.6 in a _conda-env_

Running `python3 examples/llama3.py --model downloads/llama3-8b-sfr/ --no_api  `

```
loaded weights in  33.01 ms, 0.03 GB loaded at 1.02 GB/s
Traceback (most recent call last):
  File "/x/tinygrad/tinygrad/runtime/ops_metal.py", line 25, in compile
    try: library = unwrap2(self.device.device.newLibraryWithSource_options_error_(src, options, None))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/x/tinygrad/tinygrad/helpers.py", line 51, in unwrap2
    assert err is None, str(err)
           ^^^^^^^^^^^
AssertionError: Error Domain=MTLLibraryErrorDomain Code=3 "program_source:3:60: error: unknown type name 'bfloat'; did you mean 'float'?
kernel void E_131072_32_4(device half* data0, const device bfloat* data1, uint3 gid [[threadgroup_position_in_grid]], uint3 lid [[thread_position_in_threadgroup]]) {
                                                           ^~~~~~
                                                           float
program_source:10:3: error: use of undeclared identifier 'bfloat'; did you mean 'float'?
  bfloat val0 = *(data1+alu1);
  ^~~~~~
  float
program_source:11:3: error: use of undeclared identifier 'bfloat'; did you mean 'float'?
  bfloat val1 = *(data1+alu2);
  ^~~~~~
  float
program_source:12:3: error: use of undeclared identifier 'bfloat'; did you mean 'float'?
  bfloat val2 = *(data1+alu3);
  ^~~~~~
  float
program_source:13:3: error: use of undeclared identifier 'bfloat'; did you mean 'float'?
  bfloat val3 = *(data1+alu0);
  ^~~~~~
  float
" UserInfo={NSLocalizedDescription=program_source:3:60: error: unknown type name 'bfloat'; did you mean 'float'?
kernel void E_131072_32_4(device half* data0, const device bfloat* data1, uint3 gid [[threadgroup_position_in_grid]], uint3 lid [[thread_position_in_threadgroup]]) {
                                                           ^~~~~~
                                                           float
program_source:10:3: error: use of undeclared identifier 'bfloat'; did you mean 'float'?
  bfloat val0 = *(data1+alu1);
  ^~~~~~
  float
program_source:11:3: error: use of undeclared identifier 'bfloat'; did you mean 'float'?
  bfloat val1 = *(data1+alu2);
  ^~~~~~
  float
program_source:12:3: error: use of undeclared identifier 'bfloat'; did you mean 'float'?
  bfloat val2 = *(data1+alu3);
  ^~~~~~
  float
program_source:13:3: error: use of undeclared identifier 'bfloat'; did you mean 'float'?
  bfloat val3 = *(data1+alu0);
  ^~~~~~
  float
}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/x/tinygrad/examples/llama3.py", line 249, in <module>
    model = build_transformer(args.model, model_size=args.size, quantize=args.quantize, device=device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/x/tinygrad/examples/llama3.py", line 178, in build_transformer
    load_state_dict(model, weights, strict=False, consume=True)
  File "/x/tinygrad/tinygrad/nn/state.py", line 129, in load_state_dict
    else: v.replace(state_dict[k].to(v.device)).realize()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/x/tinygrad/tinygrad/tensor.py", line 3161, in _wrapper
    ret = fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/x/tinygrad/tinygrad/tensor.py", line 203, in realize
    run_schedule(*self.schedule_with_vars(*lst), do_update_stats=do_update_stats)
  File "/x/tinygrad/tinygrad/engine/realize.py", line 222, in run_schedule
    for ei in lower_schedule(schedule):
  File "/x/tinygrad/tinygrad/engine/realize.py", line 215, in lower_schedule
    raise e
  File "/x/tinygrad/tinygrad/engine/realize.py", line 209, in lower_schedule
    try: yield lower_schedule_item(si)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/x/tinygrad/tinygrad/engine/realize.py", line 193, in lower_schedule_item
    runner = get_runner(si.outputs[0].device, si.ast)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/x/tinygrad/tinygrad/engine/realize.py", line 164, in get_runner
    method_cache[ckey] = method_cache[bkey] = ret = CompiledRunner(replace(prg, dname=dname))
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/x/tinygrad/tinygrad/engine/realize.py", line 82, in __init__
    self.lib:bytes = precompiled if precompiled is not None else Device[p.dname].compiler.compile_cached(p.src)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/x/tinygrad/tinygrad/device.py", line 181, in compile_cached
    lib = self.compile(src)
          ^^^^^^^^^^^^^^^^^
  File "/x/tinygrad/tinygrad/runtime/ops_metal.py", line 26, in compile
    except AssertionError as e: raise CompileError(e) from e
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tinygrad.device.CompileError: Error Domain=MTLLibraryErrorDomain Code=3 "program_source:3:60: error: unknown type name 'bfloat'; did you mean 'float'?
kernel void E_131072_32_4(device half* data0, const device bfloat* data1, uint3 gid [[threadgroup_position_in_grid]], uint3 lid [[thread_position_in_threadgroup]]) {
                                                           ^~~~~~
                                                           float
program_source:10:3: error: use of undeclared identifier 'bfloat'; did you mean 'float'?
  bfloat val0 = *(data1+alu1);
  ^~~~~~
  float
program_source:11:3: error: use of undeclared identifier 'bfloat'; did you mean 'float'?
  bfloat val1 = *(data1+alu2);
  ^~~~~~
  float
program_source:12:3: error: use of undeclared identifier 'bfloat'; did you mean 'float'?
  bfloat val2 = *(data1+alu3);
  ^~~~~~
  float
program_source:13:3: error: use of undeclared identifier 'bfloat'; did you mean 'float'?
  bfloat val3 = *(data1+alu0);
  ^~~~~~
  float
" UserInfo={NSLocalizedDescription=program_source:3:60: error: unknown type name 'bfloat'; did you mean 'float'?
kernel void E_131072_32_4(device half* data0, const device bfloat* data1, uint3 gid [[threadgroup_position_in_grid]], uint3 lid [[thread_position_in_threadgroup]]) {
                                                           ^~~~~~
                                                           float
program_source:10:3: error: use of undeclared identifier 'bfloat'; did you mean 'float'?
  bfloat val0 = *(data1+alu1);
  ^~~~~~
  float
program_source:11:3: error: use of undeclared identifier 'bfloat'; did you mean 'float'?
  bfloat val1 = *(data1+alu2);
  ^~~~~~
  float
program_source:12:3: error: use of undeclared identifier 'bfloat'; did you mean 'float'?
  bfloat val2 = *(data1+alu3);
  ^~~~~~
  float
program_source:13:3: error: use of undeclared identifier 'bfloat'; did you mean 'float'?
  bfloat val3 = *(data1+alu0);
  ^~~~~~
  float
}
```

**Comment by nimlgen** [comment]
`bfloat` is supported since macOS 14+. What version are you running this on?

**Comment by mcale6** [comment]
version 14.5

**Comment by AlexCheema** [comment]
Same issue, same model. Works fine on my MacBook but fails on GitHub workflow runner: https://github.com/exo-explore/exo/actions/runs/10018304212/job/27693512720

**Comment by nimlgen** [comment]
The CI machines are strange... They also do not support indirect buffers. I think they are emulated.

@mcale6, you can also try setting `METAL_XCODE=1` envvar

**Comment by mcale6** [comment]
@nimlgen, `METAL_XCODE=1` fixed the problem.
