### ISSUE TITLE
Fail to run a simple example with nv backend on RTX 3060 laptop GPU

### ISSUE THREAD

**Issue by junaire** [tinygrad/tinygrad#5730]
I tried a simple code with nv backend enabled, but it fail to run.

```python
from tinygrad import Tensor

#Tensor.rand(16,3,64,64).conv2d(Tensor.rand(16,3,3,3)).numpy()

a = Tensor.rand(3,4)
b = Tensor.rand(4,3)
c = a.dot(b)
print(c.numpy())
````

```
❯ NV=1  DEBUG=6 python3 test.py
opened device NPY from pid:956012
Traceback (most recent call last):
  File "/home/jun/Documents/tinygrad/test.py", line 8, in <module>
    print(c.numpy())
  File "/home/jun/Documents/tinygrad/tinygrad/tensor.py", line 3161, in _wrapper
    ret = fn(*args, **kwargs)
  File "/home/jun/Documents/tinygrad/tinygrad/tensor.py", line 300, in numpy
    return np.frombuffer(self._data(), dtype=_to_np_dtype(self.dtype)).reshape(self.shape)
  File "/home/jun/Documents/tinygrad/tinygrad/tensor.py", line 3140, in _wrapper
    if _METADATA.get() is not None: return fn(*args, **kwargs)
  File "/home/jun/Documents/tinygrad/tinygrad/tensor.py", line 244, in _data
    cpu = self.cast(self.dtype.scalar()).contiguous().to("CLANG").realize()
  File "/home/jun/Documents/tinygrad/tinygrad/tensor.py", line 3140, in _wrapper
    if _METADATA.get() is not None: return fn(*args, **kwargs)
  File "/home/jun/Documents/tinygrad/tinygrad/tensor.py", line 203, in realize
    run_schedule(*self.schedule_with_vars(*lst), do_update_stats=do_update_stats)
  File "/home/jun/Documents/tinygrad/tinygrad/engine/realize.py", line 225, in run_schedule
    ei.run(var_vals, do_update_stats=do_update_stats)
  File "/home/jun/Documents/tinygrad/tinygrad/engine/realize.py", line 175, in run
    bufs = [cast(Buffer, x) for x in self.bufs] if jit else [cast(Buffer, x).ensure_allocated() for x in self.bufs]
  File "/home/jun/Documents/tinygrad/tinygrad/engine/realize.py", line 175, in <listcomp>
    bufs = [cast(Buffer, x) for x in self.bufs] if jit else [cast(Buffer, x).ensure_allocated() for x in self.bufs]
  File "/home/jun/Documents/tinygrad/tinygrad/device.py", line 76, in ensure_allocated
    def ensure_allocated(self) -> Buffer: return self.allocate() if not hasattr(self, '_buf') else self
  File "/home/jun/Documents/tinygrad/tinygrad/device.py", line 79, in allocate
    self.allocator = Device[self.device].allocator
  File "/home/jun/Documents/tinygrad/tinygrad/device.py", line 19, in __getitem__
    def __getitem__(self, ix:str) -> Compiled: return self.__get_canonicalized_item(self.canonicalize(ix))
  File "/home/jun/Documents/tinygrad/tinygrad/device.py", line 25, in __get_canonicalized_item
    ret = [cls for cname, cls in inspect.getmembers(importlib.import_module(f'tinygrad.runtime.ops_{x.lower()}')) if (cname.lower() == x.lower() + "device") and x in self._devices][0](ix)  # noqa: E501
  File "/home/jun/Documents/tinygrad/tinygrad/runtime/ops_nv.py", line 463, in __init__
    self._setup_nvclasses()
  File "/home/jun/Documents/tinygrad/tinygrad/runtime/ops_nv.py", line 431, in _setup_nvclasses
    clsinfo = rmctrl.gpu_get_classlist_v2(self.fd_ctl, self.root, self.device)
  File "/home/jun/Documents/tinygrad/tinygrad/runtime/ops_nv.py", line 33, in rm_control
    if made.status != 0: raise RuntimeError(f"rm_control returned {made.status}: {nv_gpu.nv_status_codes.get(made.status, 'Unknown error')}")
RuntimeError: rm_control returned 31: Invalid argument to call
```

The code works perfectly with clang backend.

tinygrad is installed from source (master branch)

```
❯ python3 -V
Python 3.10.12
```

```
❯ nvidia-smi
Fri Jul 26 22:09:26 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.42.06              Driver Version: 555.42.06      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 ...    Off |   00000000:01:00.0  On |                  N/A |
| N/A   56C    P8             17W /  110W |     535MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A    808168      G   /usr/lib/xorg/Xorg                             69MiB |
|    0   N/A  N/A    808384      G   /usr/bin/gnome-shell                           60MiB |
|    0   N/A  N/A    935188      C   /usr/local/bin/ollama                         382MiB |
+-----------------------------------------------------------------------------------------+
```

```
❯ uname -a
Linux Diana 6.5.0-44-generic #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Jun 18 14:36:16 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by geohot** [comment]
Does `CUDA` backend work? NV is only tested on 4090 and 3090 for now

**Comment by junaire** [comment]
> Does `CUDA` backend work? NV is only tested on 4090 and 3090 for now

yes, `CUDA=1` works.

**Comment by dotpredicate** [comment]
Hey, I've had this issue recently. Tinygrad targets NVIDIA driver version 550. Downgrading your driver should fix it - works on my 3060. The error in gpu_get_classlist_v2 is caused by a backwards-incompatible change in 555.

**Comment by junaire** [comment]
> Hey, I've had this issue recently. Tinygrad targets NVIDIA driver version 550. Downgrading your driver should fix it - works on my 3060. The error in gpu_get_classlist_v2 is caused by a backwards-incompatible change in 555.

what's the policy here? what do we do about these incompatible changes? should we fix it?

**Comment by geohot** [comment]
I'd definitely support fixing it. Detect the driver version and add an if statement.

**Comment by nimlgen** [comment]
@junaire can you check if #5763 solves the problem for you?

**Comment by junaire** [comment]
> @junaire can you check if #5763 solves the problem for you?

thanks for your pr, I can confirm this fixes my issue. <3
