### ISSUE TITLE
Has this software already run on MI250X or MI300X/A ?

### ISSUE THREAD

**Issue by etiennemlb** [tinygrad/tinygrad#5977]
I'm trying to run tests such as the one given on the project's README (python3 test/test_ops.py).

I'm getting a bunch of assertion error, most being of the form:

```
0: ======================================================================
0: FAIL: test_abs (__main__.TestOps.test_abs)
0: ----------------------------------------------------------------------
0: Traceback (most recent call last):
0:   File "tinygrad.mi250/tinygrad/test/test_ops.py", line 523, in test_abs
0:     helper_test_op([(45,65)], torch.abs, Tensor.abs)
0:   File "tinygrad.mi250/tinygrad/test/test_ops.py", line 29, in helper_test_op
0:     ret = tinygrad_fxn(*tst).realize()
0:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0:   File "tinygrad.mi250/tinygrad/tinygrad/tensor.py", line 201, in realize
0:     run_schedule(*self.schedule_with_vars(*lst), do_update_stats=do_update_stats)
0:   File "tinygrad.mi250/tinygrad/tinygrad/engine/realize.py", line 190, in run_schedule
0:     for ei in lower_schedule(schedule):
0:   File "tinygrad.mi250/tinygrad/tinygrad/engine/realize.py", line 183, in lower_schedule
0:     while len(schedule): yield lower_schedule_item(schedule.pop(0))
0:                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0:   File "tinygrad.mi250/tinygrad/tinygrad/engine/realize.py", line 169, in lower_schedule_item
0:     runner = get_runner(si.outputs[0].device, si.ast)
0:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0:   File "tinygrad.mi250/tinygrad/tinygrad/engine/realize.py", line 142, in get_runner
0:     method_cache[ckey] = method_cache[bkey] = ret = CompiledRunner(replace(prg, dname=dname))
0:                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0:   File "tinygrad.mi250/tinygrad/tinygrad/engine/realize.py", line 61, in __init__
0:     self.clprg = Device[p.dname].runtime(p.function_name, self.lib)
0:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0:   File "tinygrad.mi250/tinygrad/tinygrad/runtime/ops_amd.py", line 343, in __init__
0:     assert code.kernel_code_properties & 0x400 == 0x400 # ENABLE_WAVEFRONT_SIZE32
0:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0: AssertionError
```

**Comment by nimlgen** [comment]
https://docs.tinygrad.org/runtime/ - `AMD=1` supports only RDNA 3 gpus. Now tinygrad switches to `GPU=1` when gpu is not supported. Also you can try `HIP=1` (note that this is for debugging and might have worse performance in some cases).

Thanks
