### ISSUE TITLE
BEAM Search not working on metal from fresh install. `no attribute 'commandBuffer'`

### ISSUE THREAD

**Issue by BreakTheBeta** [tinygrad/tinygrad#6042]
Running example code from pdf causes no commandBuffer found error

```bash
(tinygrad) ➜  tinygrad git:(master) DEBUG=2 BEAM=2 python -c "from tinygrad import Tensor; Tensor.rand(16,3,64,64).conv2d(Tensor.rand(16,3,3,3)).numpy()"
opened device METAL from pid:20588
opened device NPY from pid:20588
*** CUSTOM     1 custom_random                            mem  0.00 GB
*** CUSTOM     2 custom_random                            mem  0.00 GB
   0.00s:                 from   1 ->   1 actions   16   16   62   62    3    3    3
error lowering MetaOps.KERNEL
tensor operations:
[conv2d]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/will/Projects/Citrus/old/tinygrad/tinygrad/tensor.py", line 3251, in _wrapper
    ret = fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/will/Projects/Citrus/old/tinygrad/tinygrad/tensor.py", line 301, in numpy
    return np.frombuffer(self._data(), dtype=_to_np_dtype(self.dtype)).reshape(self.shape)
                         ^^^^^^^^^^^^
  File "/Users/will/Projects/Citrus/old/tinygrad/tinygrad/tensor.py", line 3226, in _wrapper
    if _METADATA.get() is not None: return fn(*args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/will/Projects/Citrus/old/tinygrad/tinygrad/tensor.py", line 245, in _data
    cpu = self.cast(self.dtype.scalar()).contiguous().to("CLANG").realize()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/will/Projects/Citrus/old/tinygrad/tinygrad/tensor.py", line 3226, in _wrapper
    if _METADATA.get() is not None: return fn(*args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/will/Projects/Citrus/old/tinygrad/tinygrad/tensor.py", line 204, in realize
    run_schedule(*self.schedule_with_vars(*lst), do_update_stats=do_update_stats)
  File "/Users/will/Projects/Citrus/old/tinygrad/tinygrad/engine/realize.py", line 221, in run_schedule
    for ei in lower_schedule(schedule):
  File "/Users/will/Projects/Citrus/old/tinygrad/tinygrad/engine/realize.py", line 214, in lower_schedule
    raise e
  File "/Users/will/Projects/Citrus/old/tinygrad/tinygrad/engine/realize.py", line 208, in lower_schedule
    try: yield lower_schedule_item(si)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/will/Projects/Citrus/old/tinygrad/tinygrad/engine/realize.py", line 192, in lower_schedule_item
    runner = get_runner(si.outputs[0].device, si.ast)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/will/Projects/Citrus/old/tinygrad/tinygrad/engine/realize.py", line 157, in get_runner
    prg: Program = get_kernel(Device[dname].renderer, ast).to_program()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/will/Projects/Citrus/old/tinygrad/tinygrad/engine/realize.py", line 31, in get_kernel
    k = beam_search(kb, rawbufs, BEAM.value, bool(getenv("BEAM_ESTIMATE", 1)))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/will/Projects/Citrus/old/tinygrad/tinygrad/engine/search.py", line 159, in beam_search
    try: tms = _time_program(p, lib, var_vals, rawbufs, early_stop=beam[0][1]*3 if len(beam) else 1.0, clear_l2=hasattr(dev, 'invalidate_caches'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/will/Projects/Citrus/old/tinygrad/tinygrad/engine/search.py", line 52, in _time_program
    tms.append(cast(float, car(input_bufs, var_vals, wait=True))*factor)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/will/Projects/Citrus/old/tinygrad/tinygrad/engine/realize.py", line 104, in __call__
    return self.clprg(*[x._buf for x in rawbufs], **lra, vals=tuple(var_vals[k] for k in self.p.vars), wait=wait)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/will/Projects/Citrus/old/tinygrad/tinygrad/runtime/ops_metal.py", line 47, in __call__
    command_buffer = self.device.mtl_queue.commandBuffer()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'commandBuffer'
```

## Hardware

16inch M2 Max
MacOs 14.5

**Comment by nimlgen** [comment]
Is it reproducible for you?

**Comment by BreakTheBeta** [comment]
Yep, beam search doesn't even start

**Comment by mszep** [comment]
FWIW doesn't reproduce for me on Intel Mac, MacOs 14.6.1, python 3.12.3, using tinygrad@30035df5a43e6eb89a20c45cc8407f587f5b880f

```
⋊> ~/tinygrad on master ◦ IGNORE_BEAM_CACHE=1 DEBUG=2 BEAM=2 python -c "from tinygrad import Tensor; Tensor.rand(16,3,64,64).conv2d(Tensor.rand(16,3,3,3)).numpy()"

opened device METAL from pid:56853
opened device NPY from pid:56853
*** CUSTOM     1 custom_random                            mem  0.00 GB
*** CUSTOM     2 custom_random                            mem  0.00 GB
   0.00s:                 from   1 ->   1 actions   16   16   62   62    3    3    3
  15.68s:       770.32 us from  34 ->  34 actions   16   62   62   16    3    3    3
  29.76s:       610.80 us from  58 ->  57 actions   16   31   62   16    3    3    3    2
  48.00s:       548.48 us from  50 ->  49 actions   16   31   31   16    2    3    3    3    2
  66.07s:       513.52 us from  47 ->  46 actions   16   31   31   16    3    3    2    2    3
  81.21s:       513.52 us from  42 ->  42 actions   16   31   31   16    3    3    2    2    3
beam2  : 16 31 31 16 3 3 2 2 3          :   734.56 us  <  hc     : 4 31 31 4 2 2 3 4 4 3 3        :   797.60 us
*** METAL      3 r_16_31_31_16_3_3_2_2_3                  mem  0.00 GB tm    563.44us/     0.56ms (    94.31 GFLOPS    8.4|179.9   GB/s) ['conv2d']
opened device CLANG from pid:56853
*** CLANG      4 copy    3.94M,   CLANG <- METAL          mem  0.01 GB tm   4440.83us/     5.00ms (     0.00 GFLOPS    0.9|0.9     GB/s)
avg:    10.62 GFLOPS     1.73 GB/s           total:     4 kernels     0.05 GOPS     0.01 GB     5.00 ms
⋊> ~/tinygrad on master ◦ 
```

**Comment by chenyuxyz** [comment]
Not sure if it's still valid and metal backend has changed a lot. Closing this one. Feel free to open a new issue
