### ISSUE TITLE
BEAM Search not working as intended

### ISSUE THREAD

**Issue by peppermintcoding** [tinygrad/tinygrad#6504]
Running training script with BEAM=2 giving errors. Script is the simple mnist form the docs. Runs fine without the BEAM=2, no problems.

Run with `BEAM=2 python3 mnist.py`
[mnist.zip](https://github.com/user-attachments/files/16993549/mnist.zip)

Running on an A6000 Nvidia Laptop GPU and WSL2 Ubuntu, tinygrad 0.9.2

Error Message: 

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
Traceback (most recent call last):
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
  File "<string>", line 1, in <module>
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    exitcode = _main(fd, parent_sentinel)
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    main_content = runpy.run_path(main_path,
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/runpy.py", line 289, in run_path
    prepare(preparation_data)
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/runpy.py", line 96, in _run_module_code
    main_content = runpy.run_path(main_path,
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/runpy.py", line 289, in run_path
    _run_code(code, mod_globals, init_globals,
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/wc5sz5k/tinygrad-gpt/mnist.py", line 18, in <module>
    return _run_module_code(code, init_globals, run_name,
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/runpy.py", line 96, in _run_module_code
    X_train, Y_train, X_test, Y_test = mnist()
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/site-packages/tinygrad/nn/datasets.py", line 7, in mnist
    _run_code(code, mod_globals, init_globals,
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/runpy.py", line 86, in _run_code
    return _fetch_mnist("train-images-idx3-ubyte.gz", 0x10).reshape(-1, 1, 28, 28), _fetch_mnist("train-labels-idx1-ubyte.gz", 8), \
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/site-packages/tinygrad/nn/datasets.py", line 5, in _fetch_mnist
    exec(code, run_globals)
    def _fetch_mnist(file, offset): return Tensor(gzip.open(fetch("https://storage.googleapis.com/cvdf-datasets/mnist/"+file)).read()[offset:])
  File "/home/wc5sz5k/tinygrad-gpt/mnist.py", line 18, in <module>
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/site-packages/tinygrad/tensor.py", line 128, in __init__
    X_train, Y_train, X_test, Y_test = mnist()
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/site-packages/tinygrad/nn/datasets.py", line 7, in mnist
    return _fetch_mnist("train-images-idx3-ubyte.gz", 0x10).reshape(-1, 1, 28, 28), _fetch_mnist("train-labels-idx1-ubyte.gz", 8), \
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/site-packages/tinygrad/nn/datasets.py", line 5, in _fetch_mnist
    elif isinstance(data, bytes): data = _frompy(data, dtypes.uint8 if dtype is None else dtype)
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/site-packages/tinygrad/tensor.py", line 66, in _frompy
    def _fetch_mnist(file, offset): return Tensor(gzip.open(fetch("https://storage.googleapis.com/cvdf-datasets/mnist/"+file)).read()[offset:])
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/site-packages/tinygrad/tensor.py", line 128, in __init__
    elif isinstance(data, bytes): data = _frompy(data, dtypes.uint8 if dtype is None else dtype)
    ret.buffer.allocate(memoryview(data))
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/site-packages/tinygrad/tensor.py", line 66, in _frompy
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/site-packages/tinygrad/device.py", line 80, in allocate
    ret.buffer.allocate(memoryview(data))
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/site-packages/tinygrad/device.py", line 80, in allocate
    self.allocator = Device[self.device].allocator
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/site-packages/tinygrad/device.py", line 19, in __getitem__
    self.allocator = Device[self.device].allocator
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/site-packages/tinygrad/device.py", line 19, in __getitem__
    def __getitem__(self, ix:str) -> Compiled: return self.__get_canonicalized_item(self.canonicalize(ix))
    def __getitem__(self, ix:str) -> Compiled: return self.__get_canonicalized_item(self.canonicalize(ix))
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/site-packages/tinygrad/device.py", line 22, in __get_canonicalized_item
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/site-packages/tinygrad/device.py", line 22, in __get_canonicalized_item
    assert ((cpn:=multiprocessing.current_process().name) == "MainProcess") or ix.split(":")[0] in ["DISK", "NPY"], \
AssertionError: can only open device PYTHON from parent, not SpawnPoolWorker-882
    assert ((cpn:=multiprocessing.current_process().name) == "MainProcess") or ix.split(":")[0] in ["DISK", "NPY"], \
AssertionError: can only open device PYTHON from parent, not SpawnPoolWorker-881
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/wc5sz5k/tinygrad-gpt/mnist.py", line 18, in <module>
    X_train, Y_train, X_test, Y_test = mnist()
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/site-packages/tinygrad/nn/datasets.py", line 7, in mnist
    return _fetch_mnist("train-images-idx3-ubyte.gz", 0x10).reshape(-1, 1, 28, 28), _fetch_mnist("train-labels-idx1-ubyte.gz", 8), \
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/site-packages/tinygrad/nn/datasets.py", line 5, in _fetch_mnist
    def _fetch_mnist(file, offset): return Tensor(gzip.open(fetch("https://storage.googleapis.com/cvdf-datasets/mnist/"+file)).read()[offset:])
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/site-packages/tinygrad/tensor.py", line 128, in __init__
    elif isinstance(data, bytes): data = _frompy(data, dtypes.uint8 if dtype is None else dtype)
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/site-packages/tinygrad/tensor.py", line 66, in _frompy
    ret.buffer.allocate(memoryview(data))
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/site-packages/tinygrad/device.py", line 80, in allocate
    self.allocator = Device[self.device].allocator
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/site-packages/tinygrad/device.py", line 19, in __getitem__
    def __getitem__(self, ix:str) -> Compiled: return self.__get_canonicalized_item(self.canonicalize(ix))
  File "/home/wc5sz5k/miniconda3/envs/vllm/lib/python3.10/site-packages/tinygrad/device.py", line 22, in __get_canonicalized_item
    assert ((cpn:=multiprocessing.current_process().name) == "MainProcess") or ix.split(":")[0] in ["DISK", "NPY"], \
AssertionError: can only open device PYTHON from parent, not SpawnPoolWorker-883

This prints over and over again with more and more worker IDs.

**Comment by geohot** [comment]
PARALLEL=0 should work around, which mnist is this?

**Comment by peppermintcoding** [comment]
PARALLEL=0 fixes the problem, closing thx
