### ISSUE TITLE
Using NV causes a fault because of a timeout

### ISSUE THREAD

**Issue by dirkcgrunwald** [tinygrad/tinygrad#6947]
Tinygrad using the most recent master (which reports as 0.9.2 but it's the current master with commit head  42609300fff4aadd9d62aa9a005cff7096ee4bec

```
from tinygrad import Tensor, TinyJit, Variable, nn, Device
from tinygrad.nn.state import torch_load, load_state_dict
from tinygrad.helpers import getenv, DEBUG, fetch, Timing

print(f"Using device {Device.DEFAULT}")
##
## FlattenConsecutive from week3 of the course
##
class FlattenConsecutive:
  
  def __init__(self, n):
    self.n = n
    
  def __call__(self, x):
    B, T, C = x.shape
    x = x.view(B, T//self.n, C*self.n)
    if x.shape[1] == 1:
      x = x.squeeze(1)
    self.out = x
    return self.out

#
# Verify this is the same from week3
#
tt = Tensor.arange(4*4*4).view(4,4,4)
print(f"tt is {tt}")
fctt = FlattenConsecutive(2)(tt).numpy()
print(f"FlattenConsecutive(tt) is {fctt}")
print(fctt.shape)
```

saving & running on a system with an RTX3090 with libnvidia-compute-545:amd64 gives

```
(base) grunwald@rtx3090:~$ python3 ./bugreport.py 
Using device NV
tt is <Tensor <LB NV (4, 4, 4) int ShapeTracker(views=(View(shape=(4, 4, 4), strides=(16, 4, 1), offset=0, mask=None, contiguous=True),))> on NV with grad None>
Traceback (most recent call last):
  File "/home/grunwald/./bugreport.py", line 27, in <module>
    fctt = FlattenConsecutive(2)(tt).numpy()
  File "/home/grunwald/miniforge3/lib/python3.10/site-packages/tinygrad-0.9.2-py3.10.egg/tinygrad/tensor.py", line 3547, in _wrapper
    ret = fn(*args, **kwargs)
  File "/home/grunwald/miniforge3/lib/python3.10/site-packages/tinygrad-0.9.2-py3.10.egg/tinygrad/tensor.py", line 326, in numpy
    return np.frombuffer(self._data(), dtype=_to_np_dtype(self.dtype)).reshape(self.shape)
  File "/home/grunwald/miniforge3/lib/python3.10/site-packages/tinygrad-0.9.2-py3.10.egg/tinygrad/tensor.py", line 3522, in _wrapper
    if _METADATA.get() is not None: return fn(*args, **kwargs)
  File "/home/grunwald/miniforge3/lib/python3.10/site-packages/tinygrad-0.9.2-py3.10.egg/tinygrad/tensor.py", line 269, in _data
    cpu = self.cast(self.dtype.scalar()).contiguous().to("CLANG").realize()
  File "/home/grunwald/miniforge3/lib/python3.10/site-packages/tinygrad-0.9.2-py3.10.egg/tinygrad/tensor.py", line 3522, in _wrapper
    if _METADATA.get() is not None: return fn(*args, **kwargs)
  File "/home/grunwald/miniforge3/lib/python3.10/site-packages/tinygrad-0.9.2-py3.10.egg/tinygrad/tensor.py", line 228, in realize
    run_schedule(*self.schedule_with_vars(*lst), do_update_stats=do_update_stats)
  File "/home/grunwald/miniforge3/lib/python3.10/site-packages/tinygrad-0.9.2-py3.10.egg/tinygrad/engine/realize.py", line 222, in run_schedule
    for ei in lower_schedule(schedule):
  File "/home/grunwald/miniforge3/lib/python3.10/site-packages/tinygrad-0.9.2-py3.10.egg/tinygrad/engine/realize.py", line 215, in lower_schedule
    raise e
  File "/home/grunwald/miniforge3/lib/python3.10/site-packages/tinygrad-0.9.2-py3.10.egg/tinygrad/engine/realize.py", line 209, in lower_schedule
    try: yield lower_schedule_item(si)
  File "/home/grunwald/miniforge3/lib/python3.10/site-packages/tinygrad-0.9.2-py3.10.egg/tinygrad/engine/realize.py", line 193, in lower_schedule_item
    runner = get_runner(si.outputs[0].device, si.ast)
  File "/home/grunwald/miniforge3/lib/python3.10/site-packages/tinygrad-0.9.2-py3.10.egg/tinygrad/engine/realize.py", line 162, in get_runner
    method_cache[ckey] = method_cache[bkey] = ret = CompiledRunner(replace(prg, dname=dname))
  File "/home/grunwald/miniforge3/lib/python3.10/site-packages/tinygrad-0.9.2-py3.10.egg/tinygrad/engine/realize.py", line 85, in __init__
    self.clprg = Device[p.dname].runtime(p.function_name, self.lib)
  File "/home/grunwald/miniforge3/lib/python3.10/site-packages/tinygrad-0.9.2-py3.10.egg/tinygrad/runtime/ops_nv.py", line 238, in __init__
    if typ & 0xffff == 0x1204: self.device._ensure_has_local_memory(val + 0x240)
  File "/home/grunwald/miniforge3/lib/python3.10/site-packages/tinygrad-0.9.2-py3.10.egg/tinygrad/runtime/ops_nv.py", line 522, in _ensure_has_local_memory
    self.synchronize()
  File "/home/grunwald/miniforge3/lib/python3.10/site-packages/tinygrad-0.9.2-py3.10.egg/tinygrad/runtime/support/hcq.py", line 366, in synchronize
    self.timeline_signal.wait(self.timeline_value - 1) if not hasattr(self, '_syncdev') else self._syncdev()
  File "/home/grunwald/miniforge3/lib/python3.10/site-packages/tinygrad-0.9.2-py3.10.egg/tinygrad/runtime/support/hcq.py", line 233, in wait
    raise RuntimeError(f"Wait timeout: {timeout} ms! (the signal is not set to {value}, but {self.value})")
RuntimeError: Wait timeout: 10000 ms! (the signal is not set to 2, but 0)
(base) grunwald@rtx3090:~$ 
```

**Comment by geohot** [comment]
@nimlgen

**Comment by nimlgen** [comment]
Can you please post your dmesg right after the crash? The gpu can't execute init commands which looks strange.

**Comment by dirkcgrunwald** [comment]
This is Ubuntu 22.04.4 LTS and nvidia-smi output is

![image](https://github.com/user-attachments/assets/0c6b12ed-3111-4696-b801-c4163b1a73c4)

dmesg does report an error

```
914640.338338] NVRM: Xid (PCI:0000:02:00): 31, pid=354100, name=python3, Ch 00000008, intr 00000000. MMU Fault: ENGINE HOST0 HUBCLIENT_ESC faulted @ 0x10_00200000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_READ
```

**Comment by epicfilemcnulty** [comment]
I have the same crash on the latest master, RTX 4090 GPU, host system is debian trixie, 
`Driver Version: 535.183.06`, `CUDA Version: 12.2`,

dmesg error:

```
[22859.081855] NVRM: GPU at PCI:0000:01:00: GPU-af4f89ae-d08b-1b53-9938-c9ed209a3513
[22859.081859] NVRM: GPU Board Serial Number: 1710424007242
[22859.081860] NVRM: Xid (PCI:0000:01:00): 31, pid=14292, name=python, Ch 00000030, intr 00000000. MMU Fault: ENGINE HOST0 HUBCLIENT_ESC faulted @ 0x10_00200000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_READ
[23203.142515] NVRM: Xid (PCI:0000:01:00): 31, pid=14566, name=python, Ch 00000030, intr 00000000. MMU Fault: ENGINE HOST0 HUBCLIENT_ESC faulted @ 0x10_00200000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_READ
```

**Comment by keithyau** [comment]
Successfully solved by following here: https://github.com/tinygrad/open-gpu-kernel-modules install the open source nvidia module before running NV=1
