### ISSUE TITLE
openpilot dmonitoring model does pass compile self-tests in latest tinygrad with QCOM=1

### ISSUE THREAD

**Issue by haraschax** [tinygrad/tinygrad#6958]
```
wget https://github.com/commaai/openpilot/raw/v0.9.7/selfdrive/modeld/models/dmonitoring_model.onnx -O /tmp/monitor.onnx
PYTHONPATH=":/data/openpilot/tinygrad_repo" QCOM=1 python3 /data/openpilot/tinygrad_repo/examples/openpilot/compile3.py /tmp/monitor.onnx
```

produces
```
comma@comma-8fcff1ab:/data/openpilot$ PYTHONPATH=":/data/openpilot/tinygrad_repo" QCOM=1 python3 /data/openpilot/tinygrad_repo/examples/openpilot/compile3.py /tmp/monitor.onnx
loaded model
created tensors
run 0
opened device CLANG from pid:74679
scheduled 586 kernels
memory reduced from 40.11 MB -> 33.66 MB, 321 -> 290 bufs
run 1
scheduled 322 kernels
JIT captured 334 kernels with 2 inputs
pruned from 334 -> 141 kernels
JIT memory reduced from 30.29 MB -> 23.83 MB, 132 -> 101 bufs
run 2
JIT GRAPHing batch with 133 kernels on device <tinygrad.runtime.ops_qcom.QCOMDevice object at 0x7f9036bcd0>
*** CLANG      1 copy        4,   CLANG <- QCOM            arg  2 mem  0.05 GB tm    126.25us/     0.13ms (     0.00 GFLOPS    0.0|0.0     GB/s) 
*** CLANG      2 copy        4,   CLANG <- QCOM            arg  2 mem  0.05 GB tm     83.64us/     0.21ms (     0.00 GFLOPS    0.0|0.0     GB/s) 
*** CLANG      3 copy        4,   CLANG <- QCOM            arg  2 mem  0.05 GB tm     83.07us/     0.29ms (     0.00 GFLOPS    0.0|0.0     GB/s) 
*** CLANG      4 copy        4,   CLANG <- QCOM            arg  2 mem  0.05 GB tm     78.44us/     0.37ms (     0.00 GFLOPS    0.0|0.0     GB/s) 
*** CLANG      5 copy        4,   CLANG <- QCOM            arg  2 mem  0.05 GB tm     78.54us/     0.45ms (     0.00 GFLOPS    0.0|0.0     GB/s) 
*** CLANG      6 copy        4,   CLANG <- QCOM            arg  2 mem  0.05 GB tm     95.83us/     0.55ms (     0.00 GFLOPS    0.0|0.0     GB/s) 
*** CLANG      7 copy        4,   CLANG <- QCOM            arg  2 mem  0.05 GB tm     89.63us/     0.64ms (     0.00 GFLOPS    0.0|0.0     GB/s) 
*** CLANG      8 copy        4,   CLANG <- QCOM            arg  2 mem  0.05 GB tm     91.66us/     0.73ms (     0.00 GFLOPS    0.0|0.0     GB/s) 
*** QCOM       9 <batched 133>                             arg  2 mem  0.05 GB tm     13.96ms/    14.68ms (   107.90 GFLOPS    5.4|138.0   GB/s) 
*** CLANG     10 copy      336,   CLANG <- QCOM            arg  2 mem  0.05 GB tm    102.86us/    14.79ms (     0.00 GFLOPS    0.0|0.0     GB/s) 
captured 141 kernels
Traceback (most recent call last):
  File "/data/openpilot/tinygrad_repo/examples/openpilot/compile3.py", line 78, in <module>
    test_val = compile() if not getenv("RUN") else None
               ^^^^^^^^^
  File "/data/openpilot/tinygrad_repo/examples/openpilot/compile3.py", line 48, in compile
    np.testing.assert_equal(test_val, ret)
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/site-packages/numpy/testing/_private/utils.py", line 282, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/site-packages/numpy/testing/_private/utils.py", line 920, in assert_array_equal
    assert_array_compare(operator.__eq__, x, y, err_msg=err_msg,
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/site-packages/numpy/testing/_private/utils.py", line 797, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

Mismatched elements: 41 / 84 (48.8%)
Max absolute difference: 13.
Max relative difference: 198.11111
 x: array([[ 8.185687e-01,  1.055439e+00,  2.851110e-01,  5.819049e-01,
         5.845404e-02,  4.363403e-01, -2.348640e+00, -2.404555e+00,
        -2.629772e+00, -5.756116e+00, -5.598006e+00, -5.552535e+00,...
 y: array([[ 0.818569,  1.055439,  0.285111,  0.581905,  0.058454,  0.43634 ,
        -2.34864 , -2.404555, -2.629772, -5.756116, -5.598006, -5.552535,
         3.821026,  6.      ,  0.113281, -0.75    , -6.036133,  0.398438,...
```

Seems broken since this commit: 9eb6eef441b4688b5f07b6ac8738fe03de27e521

**Comment by wozeparrot** [comment]
Seems to pass fine with `GPU=1`

```
captured 141 kernels
jit run validated
mdl size is 16.13M
pkl size is 32.75M
**** compile done ****
enqueue  86.51 ms -- total run  88.50 ms
enqueue  17.80 ms -- total run  19.83 ms
enqueue  17.90 ms -- total run  19.87 ms
enqueue  17.82 ms -- total run  20.04 ms
enqueue  18.03 ms -- total run  19.48 ms
enqueue  18.21 ms -- total run  19.63 ms
enqueue  18.00 ms -- total run  19.55 ms
enqueue  17.76 ms -- total run  19.82 ms
enqueue  18.02 ms -- total run  19.80 ms
enqueue  18.13 ms -- total run  19.88 ms
enqueue  17.86 ms -- total run  19.72 ms
enqueue  17.64 ms -- total run  19.97 ms
enqueue  17.82 ms -- total run  19.80 ms
enqueue  17.67 ms -- total run  19.99 ms
enqueue  17.60 ms -- total run  19.94 ms
enqueue  17.77 ms -- total run  19.79 ms
enqueue  17.66 ms -- total run  19.84 ms
enqueue  18.00 ms -- total run  20.14 ms
enqueue  17.84 ms -- total run  19.76 ms
enqueue  18.46 ms -- total run  20.29 ms
{'outputs': <Tensor <LB GPU (1, 84) float (<BinaryOps.ADD: 9>, <buf real:True device:GPU size:84 dtype:dtypes.float offset:0>)> on GPU with grad None>} (1, 84) float32
**** test done ****
```
