### ISSUE TITLE
openpilot model does not compile with CLANG=1

### ISSUE THREAD

**Issue by haraschax** [tinygrad/tinygrad#6960]
To get latest tinygrad in openpilot we need to be able to compile on CPU. I assume the right backend for this is CLANG?

openpilot model does not appear to compile with CLANG:
```
CLANG=1 python3 examples/openpilot/compile3.py
```
Gives 

```
batman@workstation-harald:~/xx/openpilot/tinygrad_repo$ CLANG=1 python3 examples/openpilot/compile3.py 
loaded model               
created tensors                                                                                                            
run 0                                                                                                                      scheduled 724 kernels
memory reduced from 70.32 MB -> 64.22 MB, 409 -> 296 bufs                                                                  
<stdin>:3:18: error: unknown type name 'write_only'                                                                        
void E_32768_4_6(write_only image2d_t data0, const __fp16* restrict data1, const __fp16* restrict data2) {
                 ^                                                                                                         
<stdin>:3:39: error: expected ')'                  
void E_32768_4_6(write_only image2d_t data0, const __fp16* restrict data1, const __fp16* restrict data2) {                                                       ^                                                                                    
<stdin>:3:17: note: to match this '('                                                                                      
void E_32768_4_6(write_only image2d_t data0, const __fp16* restrict data1, const __fp16* restrict data2) {
                ^
<stdin>:4:7: error: unknown type name 'sampler_t'
const sampler_t smp = CLK_NORMALIZED_COORDS_FALSE | CLK_ADDRESS_CLAMP | CLK_FILTER_NEAREST;
      ^
<stdin>:4:23: error: use of undeclared identifier 'CLK_NORMALIZED_COORDS_FALSE'
const sampler_t smp = CLK_NORMALIZED_COORDS_FALSE | CLK_ADDRESS_CLAMP | CLK_FILTER_NEAREST;
                      ^
<stdin>:4:53: error: use of undeclared identifier 'CLK_ADDRESS_CLAMP'
const sampler_t smp = CLK_NORMALIZED_COORDS_FALSE | CLK_ADDRESS_CLAMP | CLK_FILTER_NEAREST;
                                                    ^
<stdin>:4:73: error: use of undeclared identifier 'CLK_FILTER_NEAREST'
const sampler_t smp = CLK_NORMALIZED_COORDS_FALSE | CLK_ADDRESS_CLAMP | CLK_FILTER_NEAREST;
                                                                        ^
<stdin>:19:19: error: use of undeclared identifier 'data1'
    __fp16 val0 = data1[alu0]; 
                  ^
<stdin>:20:19: error: use of undeclared identifier 'data1'
    __fp16 val1 = data1[alu1]; 
                  ^
<stdin>:21:19: error: use of undeclared identifier 'data1'
    __fp16 val2 = data1[alu2]; 
                  ^
<stdin>:22:19: error: use of undeclared identifier 'data1'
    __fp16 val3 = data1[alu3]; 
                  ^
<stdin>:23:19: error: use of undeclared identifier 'data1'
    __fp16 val4 = data1[alu4]; 
                  ^
<stdin>:24:19: error: use of undeclared identifier 'data1'
    __fp16 val5 = data1[alu5]; 
                  ^
<stdin>:25:19: error: use of undeclared identifier 'data1'
    __fp16 val6 = data1[alu6]; 
                  ^
<stdin>:26:5: error: use of undeclared identifier 'data0'
    data0[(int2){((alu11+1)%1536),alu12}] = (float4){(float)(val3),(float)(val4),(float)(val5),(float)(val6)};
    ^
<stdin>:27:19: error: use of undeclared identifier 'data1'
    __fp16 val7 = data1[alu7]; 
                  ^
<stdin>:28:19: error: use of undeclared identifier 'data1'
    __fp16 val8 = data1[alu8]; 
                  ^
<stdin>:29:19: error: use of undeclared identifier 'data1'
    __fp16 val9 = data1[alu9]; 
                  ^
<stdin>:30:20: error: use of undeclared identifier 'data1'
    __fp16 val10 = data1[alu10];
                   ^
<stdin>:31:5: error: use of undeclared identifier 'data0'
    data0[(int2){((alu11+2)%1536),alu12}] = (float4){(float)(val7),(float)(val8),(float)(val9),(float)(val10)};
    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
Traceback (most recent call last):
  File "/home/batman/xx/openpilot/tinygrad_repo/examples/openpilot/compile3.py", line 78, in <module>
    test_val = compile() if not getenv("RUN") else None
               ^^^^^^^^^
  File "/home/batman/xx/openpilot/tinygrad_repo/examples/openpilot/compile3.py", line 45, in compile
    ret = next(iter(run_onnx_jit(**new_inputs).values())).cast('float32').numpy()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/batman/xx/openpilot/tinygrad_repo/tinygrad/engine/jit.py", line 231, in __call__
    if len(params:=get_parameters(ret)): Tensor.realize(params[0], *params[1:])
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/batman/xx/openpilot/tinygrad_repo/tinygrad/tensor.py", line 3547, in _wrapper
    ret = fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/batman/xx/openpilot/tinygrad_repo/tinygrad/tensor.py", line 228, in realize
    run_schedule(*self.schedule_with_vars(*lst), do_update_stats=do_update_stats)
  File "/home/batman/xx/openpilot/tinygrad_repo/tinygrad/engine/realize.py", line 223, in run_schedule
    for ei in lower_schedule(schedule):
  File "/home/batman/xx/openpilot/tinygrad_repo/tinygrad/engine/realize.py", line 216, in lower_schedule
    raise e
  File "/home/batman/xx/openpilot/tinygrad_repo/tinygrad/engine/realize.py", line 210, in lower_schedule
    try: yield lower_schedule_item(si)
               ^^^^^^^^^^^^^^^^^^^^^^^

File "/home/batman/xx/openpilot/tinygrad_repo/tinygrad/engine/realize.py", line 194, in lower_schedule_item
    runner = get_runner(si.outputs[0].device, si.ast)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/batman/xx/openpilot/tinygrad_repo/tinygrad/engine/realize.py", line 163, in get_runner
    method_cache[ckey] = method_cache[bkey] = ret = CompiledRunner(replace(prg, dname=dname))
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/batman/xx/openpilot/tinygrad_repo/tinygrad/engine/realize.py", line 84, in __init__
    self.lib:bytes = precompiled if precompiled is not None else Device[p.dname].compiler.compile_cached(p.src)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/batman/xx/openpilot/tinygrad_repo/tinygrad/device.py", line 187, in compile_cached
    lib = self.compile(src)
          ^^^^^^^^^^^^^^^^^
  File "/home/batman/xx/openpilot/tinygrad_repo/tinygrad/runtime/ops_clang.py", line 15, in compile
    subprocess.check_output(['clang', '-shared', *self.args, '-O2', '-Wall', '-Werror', '-x', 'c', '-fPIC', '-ffreestanding
', '-nostdlib',
  File "/home/batman/.pyenv/versions/3.11.4/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/batman/.pyenv/versions/3.11.4/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['clang', '-shared', '-march=native', '-O2', '-Wall', '-Werror', '-x', 'c', '-fPIC'
, '-ffreestanding', '-nostdlib', '-', '-o', '/tmp/tmppft3ja0c']' returned non-zero exit status 1.
```

**Comment by geohot** [comment]
You have to set IMAGE=0

**Comment by geohot** [comment]
Confirmed working (though I'm not exactly sure why you need this? for CI?)

**Comment by haraschax** [comment]
Got it.

And yes we want CPU compilation for CI. I tried LLVM but also had issues, but I see you're looking into that, thanks!
