### ISSUE TITLE
openpilot model with JITBEAM=2 LLVM=1 fails!

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#6997]
`DEBUG=2 JITBEAM=2 IMAGE=0 LLVM=1 python3 examples/openpilot/compile3.py`

```
*** LLVM     167 r_64_128_4_2                              arg  5 mem  0.11 GB tm     11.96us/    86.26ms (    10.99 GFLOPS   22.2|33.0    GB/s) 
*** LLVM     168 r_2_32_4n1                                arg  5 mem  0.11 GB tm      2.33us/    86.26ms (     0.22 GFLOPS    0.7|0.9     GB/s) 
*** LLVM     169 E_271_4_3_2                               arg 16 mem  0.11 GB tm     24.12us/    86.28ms (     3.64 GFLOPS    3.8|14.6    GB/s) 
*** CLANG    170 copy    26016,   CLANG <- LLVM            arg  2 mem  0.11 GB tm     11.42us/    86.29ms (     0.00 GFLOPS    2.3|2.3     GB/s) 
captured 169 kernels
Traceback (most recent call last):
  File "/Users/light/tinygrad/examples/openpilot/compile3.py", line 78, in <module>
    test_val = compile() if not getenv("RUN") else None
               ^^^^^^^^^
  File "/Users/light/tinygrad/examples/openpilot/compile3.py", line 48, in compile
    np.testing.assert_equal(test_val, ret)
  File "/opt/homebrew/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 333, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/numpy/_utils/__init__.py", line 85, in wrapper
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 1021, in assert_array_equal
    assert_array_compare(operator.__eq__, actual, desired, err_msg=err_msg,
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 885, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

Mismatched elements: 5219 / 6504 (80.2%)
Max absolute difference among violations: 0.00488281
Max relative difference among violations: 0.00277316
 ACTUAL: array([[-1.940113e+02,  2.045345e+01, -3.234731e-02, ...,  1.752914e-04,
         3.037935e-02, -1.543247e-02]], dtype=float32)
 DESIRED: array([[-1.940112e+02,  2.045344e+01, -3.234717e-02, ...,  1.753168e-04,
         3.037941e-02, -1.543242e-02]], dtype=float32)
```

**Comment by chenyuxyz** [comment]
the script is comparing the 0th run with the last run, JITBEAM only beam and changes compute after first run. It passes if change `if i == 0: test_val = np.copy(ret)` to `if i == 1: test_val = np.copy(ret)`. Use `BEAM` instead of `JITBEAM` should work too but it takes much longer

**Comment by geohot** [comment]
Ahh, good point. Closing

**Comment by geohot** [comment]
Changed in master
