### ISSUE TITLE
Metal backend does not like .min() or .max() on uchar tensors

### ISSUE THREAD

**Issue by StanislavNikolov** [tinygrad/tinygrad#7036]
Simple repro:
```py
from tinygrad import Tensor
t = Tensor([[1, 2], [3, 4]], dtype='uchar')
print((t*t).max().item())
```

Replacing setting dtype='float' works as expected and prints 16. Calling `.sum()` instead of `.max()` also produces the exptected result (30). Using clang as a backend also works (CLANG=1). So this only happens on min/max + uchar + metal. 

Error stack trace:
```
Traceback (most recent call last):
  File "/Users/stjo/projects/026-nn-celluar-automaton/fail.py", line 3, in <module>
    print((t*t).max().item())
          ~~~~~~~~~~~~~~~~^^
  File "/Users/stjo/projects/026-nn-celluar-automaton/.venv/lib/python3.13/site-packages/tinygrad/tensor.py", line 3549, in _wrapper
    ret = fn(*args, **kwargs)
  File "/Users/stjo/projects/026-nn-celluar-automaton/.venv/lib/python3.13/site-packages/tinygrad/tensor.py", line 297, in item
    return self._data().cast(self.dtype.fmt)[0]
           ~~~~~~~~~~^^
  File "/Users/stjo/projects/026-nn-celluar-automaton/.venv/lib/python3.13/site-packages/tinygrad/tensor.py", line 3524, in _wrapper
    if _METADATA.get() is not None: return fn(*args, **kwargs)
                                           ~~^^^^^^^^^^^^^^^^^
  File "/Users/stjo/projects/026-nn-celluar-automaton/.venv/lib/python3.13/site-packages/tinygrad/tensor.py", line 268, in _data
    cpu = self.cast(self.dtype.scalar()).contiguous().to("CLANG").realize()
  File "/Users/stjo/projects/026-nn-celluar-automaton/.venv/lib/python3.13/site-packages/tinygrad/tensor.py", line 3524, in _wrapper
    if _METADATA.get() is not None: return fn(*args, **kwargs)
                                           ~~^^^^^^^^^^^^^^^^^
  File "/Users/stjo/projects/026-nn-celluar-automaton/.venv/lib/python3.13/site-packages/tinygrad/tensor.py", line 227, in realize
    run_schedule(*self.schedule_with_vars(*lst), do_update_stats=do_update_stats)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stjo/projects/026-nn-celluar-automaton/.venv/lib/python3.13/site-packages/tinygrad/engine/realize.py", line 216, in run_schedule
    for ei in lower_schedule(schedule):
              ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/stjo/projects/026-nn-celluar-automaton/.venv/lib/python3.13/site-packages/tinygrad/engine/realize.py", line 209, in lower_schedule
    raise e
  File "/Users/stjo/projects/026-nn-celluar-automaton/.venv/lib/python3.13/site-packages/tinygrad/engine/realize.py", line 203, in lower_schedule
    try: yield lower_schedule_item(si)
               ~~~~~~~~~~~~~~~~~~~^^^^
  File "/Users/stjo/projects/026-nn-celluar-automaton/.venv/lib/python3.13/site-packages/tinygrad/engine/realize.py", line 188, in lower_schedule_item
    runner = get_runner(si.outputs[0].device, si.ast)
  File "/Users/stjo/projects/026-nn-celluar-automaton/.venv/lib/python3.13/site-packages/tinygrad/engine/realize.py", line 156, in get_runner
    method_cache[ckey] = method_cache[bkey] = ret = CompiledRunner(replace(prg, dname=dname))
                                                    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stjo/projects/026-nn-celluar-automaton/.venv/lib/python3.13/site-packages/tinygrad/engine/realize.py", line 83, in __init__
    self.lib:bytes = precompiled if precompiled is not None else Device[p.dname].compiler.compile_cached(p.src)
                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/Users/stjo/projects/026-nn-celluar-automaton/.venv/lib/python3.13/site-packages/tinygrad/device.py", line 187, in compile_cached
    lib = self.compile(src)
  File "/Users/stjo/projects/026-nn-celluar-automaton/.venv/lib/python3.13/site-packages/tinygrad/runtime/ops_metal.py", line 74, in compile
    error_check(compileError, CompileError)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stjo/projects/026-nn-celluar-automaton/.venv/lib/python3.13/site-packages/tinygrad/runtime/ops_metal.py", line 58, in error_check
    raise error_constructor(bytes(msg(msg(error, "localizedDescription", restype=objc_instance), "UTF8String", restype=ctypes.c_char_p)).decode())
tinygrad.device.CompileError: program_source:8:24: error: call to 'max' is ambiguous
  unsigned char alu1 = max(alu0,(val2*val2));
                       ^~~
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/32023/Libraries/lib/clang/32023.335/include/metal/metal_integer:665:18: note: candidate function
METAL_FUNC uchar max(uchar x, uchar y)
                 ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/32023/Libraries/lib/clang/32023.335/include/metal/metal_integer:2477:16: note: candidate function
METAL_FUNC int max(int x, int y)
               ^
program_source:10:24: error: call to 'max' is ambiguous
  unsigned char alu2 = max(alu1,(val3*val3));
                       ^~~
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/32023/Libraries/lib/clang/32023.335/include/metal/metal_integer:665:18: note: candidate function
METAL_FUNC uchar max(uchar x, uchar y)
                 ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/32023/Libraries/lib/clang/32023.335/include/metal/metal_integer:2477:16: note: candidate function
METAL_FUNC int max(int x, int y)
```

**Comment by geohot** [comment]
Can you add a failing test?

My suggested fix is to add a rewrite rule to rewrite MAX to CMPLT + WHERE

**Comment by geohot** [comment]
This bug is annoying enough that I did it. https://github.com/tinygrad/tinygrad/pull/7037/files
