### ISSUE TITLE
Overlapped setitem failed on some devices

### ISSUE THREAD

**Issue by MaxWolf-01** [tinygrad/tinygrad#7161]
The following piece of code creates different behavior, depending on which environment variable (CLANG, NV, GPU, ...) is set.
With CLANG=1 the test fails.
With GPU=1 or CUDA=1 the test passes (which it should - the code seems correct).
Tested on latest tinygrad from source (https://github.com/tinygrad/tinygrad/commit/30989fb459f38f0443abed3343f37e475622f069) ; Ubuntu 22.04; 3070 Ti Laptop GPU

CASE `GPU=1`, `CUDA=1`: Test passes

CASE `CLANG=1`: Test fails
```
Traceback (most recent call last):
  File "...", line 68, in <module>
    test_buffered_tensor_queue()
  File "...", line 54, in test_buffered_tensor_queue
    assert res == [[4.0], [3.0], [2.0], [1.0]], res
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: [[4.0], [3.0], [3.0], [3.0]]
```

Code to reproduce:
```python
from collections import deque

from tinygrad import Tensor
from tinygrad.dtype import DType, dtypes


class BufferedTensorQueue:
    __slots__ = "shape", "_buffered", "_queue"

    def __init__(self, size: int, shape: tuple[int, ...], dtype: DType | None = None) -> None:
        self.shape = shape
        self._buffered: deque[Tensor] = deque(maxlen=size)
        self._queue = Tensor.zeros((size, *shape), dtype=dtype).contiguous()

    def __len__(self) -> int:
        """Returns the number of buffered tensors."""
        return len(self._buffered)

    def get(self) -> Tensor:
        return self._queue

    def buffer(self, item: Tensor) -> None:
        assert item.shape == self.shape, f"Expected shape {self.shape}, got {item.shape}."
        self._buffered.appendleft(item)

    def enqueue_buffered(self) -> None:
        """Enqueues the buffered elements and clears the buffer."""
        if len(self._buffered) == 0:
            return
        buffered = Tensor.cat(*self._buffered).unsqueeze(-1)
        replace = len(self._buffered)
        self._queue[replace:] = self._queue[:-replace]  # todo sth is going wrong here - test fails, might be tiny issue
        self._queue[:replace] = buffered
        self._buffered.clear()


def test_buffered_tensor_queue(this_fails: bool = False) -> None:
    # import os
    # os.environ.setdefault("GPU", "1") # test passes
    # os.environ.setdefault("CLANG", "1")  # test fails
    # no os.environ aka defaults to "NV=1" -> timeout

    tq = BufferedTensorQueue(4, shape=(1,), dtype=dtypes.float32)
    assert tq.get().tolist() == [[0.0], [0.0], [0.0], [0.0]]
    tq.buffer(Tensor([1]))
    tq.buffer(Tensor([2]))
    tq.buffer(Tensor([3]))
    tq.enqueue_buffered()
    res = tq.get().tolist()
    assert res == [[3.0], [2.0], [1.0], [0.0]], res
    tq.buffer(Tensor([4]))
    tq.enqueue_buffered()
    res = tq.get().tolist()
    assert res == [[4.0], [3.0], [2.0], [1.0]], res
    tq.buffer(Tensor([5]))
    tq.buffer(Tensor([6]))
    tq.buffer(Tensor([7]))
    tq.enqueue_buffered()
    expected_queue = [[7.0], [6.0], [5.0], [4.0]]
    assert tq.get().tolist() == expected_queue
    tq.buffer(Tensor([0]))
    tq.enqueue_buffered()
    expected_queue = [[0.0], [7.0], [6.0], [5.0]]
    assert tq.get().tolist() == expected_queue


if __name__ == "__main__":
    test_buffered_tensor_queue()
```

**Comment by geohot** [comment]
Do you have a simpler failing test? Can you submit a PR with that failing test?

**Comment by chenyuxyz** [comment]
added test is fixed. closing now. feel free to open new issue / tests if you found more!
