### ISSUE TITLE
alu of tensors on different devices give incomprehensible errors

### ISSUE THREAD

**Issue by chenyuxyz** [tinygrad/tinygrad#7699]
```
from tinygrad import Tensor, Device
a = Tensor([0, 1, 2, 3], device=f"{Device.DEFAULT}")
b = Tensor([0, 1, 2, 3], device=f"{Device.DEFAULT}:1")
print(f"{(a+b).tolist()}")
```

```
Traceback (most recent call last):
  File "/Users/chenyu/code/tinygrad/test.py", line 5, in <module>
    print(f"{(a+b).tolist()}")
             ^^^^^^^^^^^^^^
  File "/Users/chenyu/code/tinygrad/tinygrad/tensor.py", line 3663, in _wrapper
    ret = fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/chenyu/code/tinygrad/tinygrad/tensor.py", line 306, in tolist
    return self.data().tolist()
           ^^^^^^^^^^^
  File "/Users/chenyu/code/tinygrad/tinygrad/tensor.py", line 3638, in _wrapper
    if _METADATA.get() is not None: return fn(*args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/chenyu/code/tinygrad/tinygrad/tensor.py", line 280, in data
    return self._data().cast(self.dtype.fmt, self.shape)
           ^^^^^^^^^^^^
  File "/Users/chenyu/code/tinygrad/tinygrad/tensor.py", line 3638, in _wrapper
    if _METADATA.get() is not None: return fn(*args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/chenyu/code/tinygrad/tinygrad/tensor.py", line 264, in _data
    cpu = self.cast(self.dtype.base).contiguous().to("CLANG").realize()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenyu/code/tinygrad/tinygrad/tensor.py", line 3638, in _wrapper
    if _METADATA.get() is not None: return fn(*args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/chenyu/code/tinygrad/tinygrad/tensor.py", line 223, in realize
    run_schedule(*self.schedule_with_vars(*lst), do_update_stats=do_update_stats)
  File "/Users/chenyu/code/tinygrad/tinygrad/engine/realize.py", line 215, in run_schedule
    for ei in lower_schedule(schedule):
  File "/Users/chenyu/code/tinygrad/tinygrad/engine/realize.py", line 208, in lower_schedule
    raise e
  File "/Users/chenyu/code/tinygrad/tinygrad/engine/realize.py", line 202, in lower_schedule
    try: yield lower_schedule_item(si)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenyu/code/tinygrad/tinygrad/engine/realize.py", line 185, in lower_schedule_item
    assert len(set(x.device for x in si.bufs)) == 1 or si.ast.op is Ops.COPY
                                                       ^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by Leorasz** [comment]
Is the issue just to add a better-to-understand error message?

**Comment by chenyuxyz** [comment]
need to update to
```
from tinygrad import Tensor, Device
a = Tensor([0, 1, 2, 3], device=f"METAL")
b = Tensor([0, 1, 2, 3], device=f"CLANG")
print(f"{(a+b).tolist()}")
```

and it gives
```
  File "/Users/chenyu/code/tinygrad/tinygrad/runtime/ops_metal.py", line 171, in __call__
    for i,a in enumerate(bufs): msg("setBuffer:offset:atIndex:")(encoder, a.buf, a.offset, i)
                                                                          ^^^^^
AttributeError: 'c_ubyte_Array_16' object has no attribute 'buf'
-[_MTLCommandEncoder dealloc]:134: failed assertion `Command encoder released without endEncoding'
[1]    84414 abort      DEBUG=2 python test.py
```

**Comment by chenyuxyz** [comment]
currently it prints
```
RuntimeError: all buffers must be on the same device: (<buf real:False device:METAL size:4 dtype:dtypes.int>, <buf real:False device:METAL size:4 dtype:dtypes.int>, <buf real:False device:CLANG size:4 dtype:dtypes.int>)
```
which is good enough i think
