### ISSUE TITLE
QCOM driver timeout in openpilot

### ISSUE THREAD

**Issue by adeebshihadeh** [tinygrad/tinygrad#8242]
```
Traceback (most recent call last):
  File "/data/openpilot/selfdrive/modeld/modeld.py", line 325, in <module>
    main(demo=args.demo)
  File "/data/openpilot/selfdrive/modeld/modeld.py", line 290, in main
    model_output = model.run(buf_main, buf_extra, model_transform_main, model_transform_extra, inputs, prepare_only)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/selfdrive/modeld/modeld.py", line 129, in run
    self.output = self.model_run(**self.tensor_inputs).numpy().flatten()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/tinygrad/tensor.py", line 3836, in _wrapper
    ret = fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/tinygrad/tensor.py", line 325, in numpy
    return np.frombuffer(self._data(), dtype=_to_np_dtype(self.dtype.base)).reshape(self.shape)
                         ^^^^^^^^^^^^
  File "/data/openpilot/tinygrad/tensor.py", line 3811, in _wrapper
    if _METADATA.get() is not None: return fn(*args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/tinygrad/tensor.py", line 268, in _data
    cpu = self.cast(self.dtype.base).contiguous().to("CLANG").realize()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/tinygrad/tensor.py", line 3811, in _wrapper
    if _METADATA.get() is not None: return fn(*args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/tinygrad/tensor.py", line 227, in realize
    run_schedule(*self.schedule_with_vars(*lst), do_update_stats=do_update_stats)
  File "/data/openpilot/tinygrad/engine/realize.py", line 217, in run_schedule
    ei.run(var_vals, do_update_stats=do_update_stats)
  File "/data/openpilot/tinygrad/engine/realize.py", line 168, in run
    et = self.prg(bufs, var_vals, wait=wait or DEBUG >= 2)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/tinygrad/engine/realize.py", line 133, in __call__
    self.copy(dest, src)
  File "/data/openpilot/tinygrad/engine/realize.py", line 128, in copy
    dest.copyin(src.as_buffer(allow_zero_copy=True))  # may allocate a CPU buffer depending on allow_zero_copy
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/tinygrad/device.py", line 118, in as_buffer
    return self.allocator._as_buffer(self._buf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/tinygrad/runtime/ops_qcom.py", line 321, in _as_buffer
    self.dev.synchronize()
  File "/data/openpilot/tinygrad/runtime/support/hcq.py", line 368, in synchronize
    else: raise e
          ^^^^^^^
  File "/data/openpilot/tinygrad/runtime/support/hcq.py", line 365, in synchronize
    try: self.timeline_signal.wait(self.timeline_value - 1)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/tinygrad/runtime/support/hcq.py", line 213, in wait
    raise RuntimeError(f"Wait timeout: {timeout} ms! (the signal is not set to {value}, but {self.value})")
RuntimeError: Wait timeout: 30000 ms! (the signal is not set to 724, but 724)
Traceback (most recent call last):
  File "/data/openpilot/selfdrive/modeld/modeld.py", line 325, in <module>
    main(demo=args.demo)
  File "/data/openpilot/selfdrive/modeld/modeld.py", line 290, in main
    model_output = model.run(buf_main, buf_extra, model_transform_main, model_transform_extra, inputs, prepare_only)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/selfdrive/modeld/modeld.py", line 129, in run
    self.output = self.model_run(**self.tensor_inputs).numpy().flatten()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/tinygrad/tensor.py", line 3836, in _wrapper
    ret = fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/tinygrad/tensor.py", line 325, in numpy
    return np.frombuffer(self._data(), dtype=_to_np_dtype(self.dtype.base)).reshape(self.shape)
                         ^^^^^^^^^^^^
  File "/data/openpilot/tinygrad/tensor.py", line 3811, in _wrapper
    if _METADATA.get() is not None: return fn(*args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/tinygrad/tensor.py", line 268, in _data
    cpu = self.cast(self.dtype.base).contiguous().to("CLANG").realize()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/tinygrad/tensor.py", line 3811, in _wrapper
    if _METADATA.get() is not None: return fn(*args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/tinygrad/tensor.py", line 227, in realize
    run_schedule(*self.schedule_with_vars(*lst), do_update_stats=do_update_stats)
  File "/data/openpilot/tinygrad/engine/realize.py", line 217, in run_schedule
    ei.run(var_vals, do_update_stats=do_update_stats)
  File "/data/openpilot/tinygrad/engine/realize.py", line 168, in run
    et = self.prg(bufs, var_vals, wait=wait or DEBUG >= 2)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/tinygrad/engine/realize.py", line 133, in __call__
    self.copy(dest, src)
  File "/data/openpilot/tinygrad/engine/realize.py", line 128, in copy
    dest.copyin(src.as_buffer(allow_zero_copy=True))  # may allocate a CPU buffer depending on allow_zero_copy
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/tinygrad/device.py", line 118, in as_buffer
    return self.allocator._as_buffer(self._buf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/tinygrad/runtime/ops_qcom.py", line 321, in _as_buffer
    self.dev.synchronize()
  File "/data/openpilot/tinygrad/runtime/support/hcq.py", line 368, in synchronize
    else: raise e
          ^^^^^^^
  File "/data/openpilot/tinygrad/runtime/support/hcq.py", line 365, in synchronize
    try: self.timeline_signal.wait(self.timeline_value - 1)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/tinygrad/runtime/support/hcq.py", line 213, in wait
    raise RuntimeError(f"Wait timeout: {timeout} ms! (the signal is not set to {value}, but {self.value})")
RuntimeError: Wait timeout: 30000 ms! (the signal is not set to 724, but 724)
```

**Comment by geohot** [comment]
@nimlgen ?

**Comment by nimlgen** [comment]
@adeebshihadeh, some timeout logic has been fixed to handle such timeouts correctly (`the signal is not set to 724, but 724`).

There is also the `HCQDEV_WAIT_TIMEOUT_MS` environment variable, which configures this timeout.

It would be great to know if this issue is reproducible for you. I think a 30-second spike is pretty bad for your workloads. Have you been running anything else on the gpu?

**Comment by geohot** [comment]
I really doubt it actually lagged 30s. @adeebshihadeh can you find a repro?
