### ISSUE TITLE
FUSE_ARANGE=1 infinite loop in _toposort

### ISSUE THREAD

**Issue by chenyuxyz** [tinygrad/tinygrad#8427]
was testing #6795 with `FUSE_ARANGE=1`. on 5755ac1f7286822fd557fd13820317980ee8602d it hung with 

```
tinygrad git:(master) ✗ FUSE_ARANGE=1 GPU=1 python test.py
^CTraceback (most recent call last):
  File "/Users/chenyu/code/tinygrad/tinygrad/ops.py", line 265, in _toposort
    for parent in u.src: nodes.update(_toposort(parent, cache))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenyu/code/tinygrad/tinygrad/ops.py", line 265, in _toposort
    for parent in u.src: nodes.update(_toposort(parent, cache))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenyu/code/tinygrad/tinygrad/ops.py", line 265, in _toposort
    for parent in u.src: nodes.update(_toposort(parent, cache))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 997 more times]
KeyboardInterrupt
```

**Comment by Qazalin** [comment]
Can you include test.py? I ran it in `FUSE_ARANGE=1 python3 -m pytest test/models/test_resnet.py` it was green.

**Comment by chenyuxyz** [comment]
it's the code in #6795 
```
import os
os.environ['GPU'] = '1'
from tinygrad.tensor import Tensor
from tinygrad import Tensor, TinyJit, Context, GlobalCounters

def perspective_warp_example(kwargs):
  src = kwargs['src']
  idx = kwargs['idx']
  dst = src[idx, idx]
  return {'dst': dst}

inputs = {}
h_dst, w_dst = 256, 512
h_src, w_src = 1208, 1928
inputs['src'] = Tensor.randn((h_src, w_src), dtype='uint8')
inputs['idx'] = Tensor.rand((h_dst, w_dst)).mul(w_src).clip(0, w_src - 1).cast('int')

full_jit = TinyJit(lambda **kwargs: perspective_warp_example(kwargs), prune=True)
GlobalCounters.reset()
with Context(DEBUG=2):
  ret = next(iter(full_jit(**inputs).values())).numpy()
print(full_jit(**inputs))
```

**Comment by chenyuxyz** [comment]
now it gives the same error to other `FUSE_ARANGE=1` error, `RuntimeError: UOp verification failed at 61 on Ops.SINK dtypes.void 1 [<Ops.STORE: 45>] None`

**Comment by Qazalin** [comment]
Yeah this means view_right is incomplete, otherwise STORE should never be the parent of a VIEW once it hits the AST.
