### ISSUE TITLE
sdxl.py: maximum recursion depth exceeded (24.04 Py 3.12.3)

### ISSUE THREAD

**Issue by FeepingCreature** [tinygrad/tinygrad#8457]
edit: This is probably the Python recursion limit bug but I don't understand why it still happens on Ubuntu's 3.12.3.

edit: Is it the recursion limit bug...? `RewriteContext.rewrite` doesn't have a cache annotation. It shouldn't use C stack. But then why does it ignore setrecursionlimit?

```
tinygrad/examples $ python3 sdxl.py --weight ~/sd_xl_base_1.0.safetensors 
ram used:  6.93 GB, sigmas: 100% ...  2515/2515 [00:04<00:00, 510.56it/s]
loaded weights in 4993.60 ms, 6.93 GB loaded at 1.39 GB/s
created batch
```Traceback (most recent call last):
  File "/home/feep/tinygrad/tinygrad/ops.py", line 897, in rewrite
    new_src = tuple(map(self.rewrite, n.src))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/feep/tinygrad/tinygrad/ops.py", line 897, in rewrite
    new_src = tuple(map(self.rewrite, n.src))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/feep/tinygrad/tinygrad/ops.py", line 897, in rewrite
    new_src = tuple(map(self.rewrite, n.src))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 997 more times]
RecursionError: maximum recursion depth exceeded
```

Happens with 8a8eaa1ed9be7d250b33dc628bd7d6e7c5b4f712 (Wed Dec 18 16:29:12) on Linux 6.12.7 with Radeon 7900 XTX, Python 3.12.3.

edit: By crashing earlier, the start of the backtrace seems to be:
```
Traceback (most recent call last):
  File "/home/feep/tinygrad/examples/sdxl.py", line 409, in <module>
    z = sampler(model.denoise, randn, c, uc, args.steps, timing=args.timing)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/feep/tinygrad/examples/sdxl.py", line 350, in __call__
    x, old_denoised = self.sampler_step(
                      ^^^^^^^^^^^^^^^^^^
  File "/home/feep/tinygrad/examples/sdxl.py", line 322, in sampler_step
    denoised = self.guider(denoiser, x, sigma, c, uc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/feep/tinygrad/examples/sdxl.py", line 302, in __call__
    x_u, x_c = denoiser(Tensor.cat(x, x), Tensor.cat(s, s), c_out).chunk(2)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/feep/tinygrad/examples/sdxl.py", line 281, in denoise
    return run(self.model.diffusion_model, *prep(x*c_in, c_noise, cond["crossattn"], cond["vector"], c_out, x))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/feep/tinygrad/examples/sdxl.py", line 279, in prep
    return tuple(t.cast(dtypes.float16).realize() for t in tensors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/feep/tinygrad/examples/sdxl.py", line 279, in <genexpr>
    return tuple(t.cast(dtypes.float16).realize() for t in tensors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/feep/tinygrad/tinygrad/tensor.py", line 3863, in _wrapper
    ret = fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/feep/tinygrad/tinygrad/tensor.py", line 226, in realize
    run_schedule(*self.schedule_with_vars(*lst), do_update_stats=do_update_stats)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/feep/tinygrad/tinygrad/tensor.py", line 3838, in _wrapper
    if _METADATA.get() is not None: return fn(*args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^
  File "/home/feep/tinygrad/tinygrad/tensor.py", line 215, in schedule_with_vars
    schedule, var_vals = create_schedule_with_vars(flatten([x.lazydata.lbs for x in (self,)+lst]))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/feep/tinygrad/tinygrad/ops.py", line 834, in __wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/feep/tinygrad/tinygrad/engine/schedule.py", line 509, in create_schedule_with_vars
    big_graph = graph_rewrite(big_graph, remove_movement_ops+ops_folding+do_realize, ctx)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/feep/tinygrad/tinygrad/ops.py", line 925, in graph_rewrite
    return RewriteContext(pm, ctx).bottom_up_rewrite(sink) if bottom_up else RewriteContext(pm, ctx).rewrite(sink)
                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/feep/tinygrad/tinygrad/ops.py", line 908, in rewrite
    new_src = tuple(map(self.rewrite, n.src))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/feep/tinygrad/tinygrad/ops.py", line 908, in rewrite
    new_src = tuple(map(self.rewrite, n.src))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/feep/tinygrad/tinygrad/ops.py", line 908, in rewrite
    new_src = tuple(map(self.rewrite, n.src))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 397 more times]
```
I don't understand why it RecursionErrors after ~1000 frames even if I raise the setting.

**Comment by chenyuxyz** [comment]
does it fail on a later version of 3.12? i think there are some recursion limit issue in the earlier versions of 3.12

**Comment by FeepingCreature** [comment]
I'm playing with an iterative version of RewriteContext, and it shows a stack hwm of 5000: no wonder it didn't work. I could have sworn I tried it with 3.12.5. This might be a separate Python bug. I'll try to see if I can get the iterative version compact enough for a pr.

**Comment by FeepingCreature** [comment]
Hm, is +37 lines worth a PR to fix a (hopefully temporary) Python issue?

```
diff --git a/tinygrad/ops.py b/tinygrad/ops.py
index c9616f774..bccc8a0a9 100644
--- a/tinygrad/ops.py
+++ b/tinygrad/ops.py
@@ -887,6 +887,42 @@ def launch_viz(env_str:str, data:str):
 
 # *** simple graph rewrite engine ***
 
+class IterativeRewriteContext:
+    def __init__(self, pm, ctx):
+        self.pm: PatternMatcher = pm
+        self.ctx = ctx
+        self.replace: Dict[UOp, UOp] = {}
+    def rewrite(self, n: UOp) -> UOp:
+        stack = [(n, [], False)] # n, map result, returning from recursive call
+        ret = None
+        while stack:
+            n, results, returning = stack[-1]
+            if len(results) < len(n.src):
+                if returning:
+                    stack[-1] = (n, results, False)
+                    results.append(ret)
+                elif (cached := self.replace.get(n.src[len(results)])) is not None:
+                    results.append(cached)
+                else:
+                    stack[-1] = (n, results, True)
+                    stack.append((n.src[len(results)], [], False))
+            elif returning:
+                self.replace[n] = ret
+                stack.pop()
+            else:
+                new_src = tuple(results)
+                if new_src == n.src:
+                    new_n = self.pm.rewrite(n, self.ctx)
+                else:
+                    new_n = UOp(n.op, n.dtype, new_src, n.arg)
+                if (ret := n if new_n is None else self.replace.get(new_n)) is not None:
+                    self.replace[n] = ret
+                    stack.pop()
+                else:
+                    stack[-1] = (n, results, True)
+                    stack.append((new_n, [], False))
+        return ret;
+
 class RewriteContext:
   def __init__(self, pm, ctx):
     self.pm: PatternMatcher = pm
@@ -910,7 +946,7 @@ def graph_rewrite(sink:UOp, pm:PatternMatcher, ctx=None, bottom_up=False) -> UOp
   if TRACK_MATCH_STATS >= 2 and not bottom_up and len(tracked_ctxs) != 0: # TODO: make viz work with bottom_up=True
     with Context(PICKLE_BUFFERS=0):
       tracked_ctxs[-1].append(TrackedGraphRewrite(((frm:=sys._getframe(1)).f_code.co_filename, frm.f_lineno), pickle.dumps(sink)))
-  return RewriteContext(pm, ctx).bottom_up_rewrite(sink) if bottom_up else RewriteContext(pm, ctx).rewrite(sink)
+  return RewriteContext(pm, ctx).bottom_up_rewrite(sink) if bottom_up else IterativeRewriteContext(pm, ctx).rewrite(sink)
 
 # ***** uop type spec *****
 
````

**Comment by chenyuxyz** [comment]
should be fixed with a later python version, feel free to open a new issue if that's not the case
